-- Migration: affiliate content-program application/approval gate.
--
-- Adds the video-creator (content CPM) application gate to `affiliates`.
-- Both EARNING (the hourly poller only accrues for approved affiliates) and
-- PAYOUT of `source='content'` commissions require `contentProgramStatus =
-- 'approved'`. An affiliate applies (status -> 'pending', requires >= 1
-- verified handle) and a super admin approves/rejects on the per-creator
-- admin page.
--
-- NOTE: authored to match the SQLite sibling generated by
-- `bun run db:migrate:desktop` (no central PG dev DB is reachable from the
-- authoring environment; apply with `bun run db:migrate:deploy` against the
-- cloud database). See prisma/schema.prisma "AFFILIATE / MLM PROGRAM".

-- CreateEnum
CREATE TYPE "ContentProgramStatus" AS ENUM ('none', 'pending', 'approved', 'rejected');

-- AlterTable
ALTER TABLE "affiliates"
    ADD COLUMN "contentProgramStatus" "ContentProgramStatus" NOT NULL DEFAULT 'none',
    ADD COLUMN "contentAppliedAt" TIMESTAMP(3),
    ADD COLUMN "contentReviewedAt" TIMESTAMP(3),
    ADD COLUMN "contentReviewedBy" TEXT,
    ADD COLUMN "contentRejectionReason" TEXT;

-- Backfill: affiliates that already have a verified social handle (or any
-- content commissions) were earning under the pre-gate behaviour; approve
-- them so the new gate doesn't strand existing earners.
UPDATE "affiliates" SET "contentProgramStatus" = 'approved', "contentReviewedAt" = NOW()
WHERE "id" IN (SELECT DISTINCT "affiliateId" FROM "affiliate_social_accounts" WHERE "verificationStatus" = 'verified')
   OR "id" IN (SELECT DISTINCT "affiliateId" FROM "affiliate_commissions" WHERE "source" = 'content');
