-- Migration: add_integration_credential_chains
-- Generated: 2026-10-05T01:23:03.169Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_integration_credential_chains`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "integration_credential_policies" ADD COLUMN "readChain" TEXT;
ALTER TABLE "integration_credential_policies" ADD COLUMN "writeChain" TEXT;

