/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as FormsFormIdSubmissionsRouteImport } from './routes/forms.$formId.submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdSubmissionsRoute = FormsFormIdSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => FormsFormIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f/$slug' | '/forms/$formId' | '/forms/$formId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f/$slug' | '/forms/$formId' | '/forms/$formId/submissions'
  id:
    | '__root__'
    | '/'
    | '/f/$slug'
    | '/forms/$formId'
    | '/forms/$formId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FSlugRoute: typeof FSlugRoute
  FormsFormIdRoute: typeof FormsFormIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/submissions': {
      id: '/forms/$formId/submissions'
      path: '/submissions'
      fullPath: '/forms/$formId/submissions'
      preLoaderRoute: typeof FormsFormIdSubmissionsRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
  }
}

interface FormsFormIdRouteChildren {
  FormsFormIdSubmissionsRoute: typeof FormsFormIdSubmissionsRoute
}

const FormsFormIdRouteChildren: FormsFormIdRouteChildren = {
  FormsFormIdSubmissionsRoute: FormsFormIdSubmissionsRoute,
}

const FormsFormIdRouteWithChildren = FormsFormIdRoute._addFileChildren(
  FormsFormIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FSlugRoute: FSlugRoute,
  FormsFormIdRoute: FormsFormIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
