-- Migration: affiliate content-CPM tracking (Instagram / TikTok).
--
-- Extends the native affiliate system so affiliates can connect social
-- handles whose posts are polled hourly for view counts; positive view
-- deltas accrue CPM commissions that ride the existing approval/payout
-- machinery. Additive and opt-in: the new `source` column defaults to
-- `referral` so every existing commission row and the entire
-- subscription-referral engine are unchanged.
--
-- NOTE: this PG migration was authored to match the SQLite sibling
-- generated by `bun run db:migrate:desktop` (no central PG dev DB is
-- reachable from the authoring environment; apply with
-- `bun run db:migrate:deploy` against the cloud database). See
-- prisma/schema.prisma "AFFILIATE / MLM PROGRAM" section and
-- apps/api/src/services/affiliate-content.service.ts for full semantics.

-- CreateEnum
CREATE TYPE "SocialPlatform" AS ENUM ('instagram', 'tiktok');

-- CreateEnum
CREATE TYPE "SocialAccountVerificationStatus" AS ENUM ('pending', 'verified', 'rejected');

-- CreateEnum
CREATE TYPE "CommissionSource" AS ENUM ('referral', 'content');

-- AlterTable
ALTER TABLE "affiliate_commissions"
    ADD COLUMN "source" "CommissionSource" NOT NULL DEFAULT 'referral',
    ADD COLUMN "contentRunId" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "affiliate_commissions_source_contentRunId_affiliateId_key" ON "affiliate_commissions"("source", "contentRunId", "affiliateId");

-- CreateTable
CREATE TABLE "affiliate_social_accounts" (
    "id" TEXT NOT NULL,
    "affiliateId" TEXT NOT NULL,
    "platform" "SocialPlatform" NOT NULL,
    "handle" TEXT NOT NULL,
    "providerUserId" TEXT,
    "verificationStatus" "SocialAccountVerificationStatus" NOT NULL DEFAULT 'pending',
    "verificationCode" TEXT NOT NULL,
    "verifiedAt" TIMESTAMP(3),
    "lastPolledAt" TIMESTAMP(3),
    "lastError" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "affiliate_social_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "affiliate_social_accounts_platform_handle_key" ON "affiliate_social_accounts"("platform", "handle");
CREATE INDEX "affiliate_social_accounts_affiliateId_idx" ON "affiliate_social_accounts"("affiliateId");
CREATE INDEX "affiliate_social_accounts_verificationStatus_idx" ON "affiliate_social_accounts"("verificationStatus");

-- AddForeignKey
ALTER TABLE "affiliate_social_accounts" ADD CONSTRAINT "affiliate_social_accounts_affiliateId_fkey" FOREIGN KEY ("affiliateId") REFERENCES "affiliates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "affiliate_posts" (
    "id" TEXT NOT NULL,
    "socialAccountId" TEXT NOT NULL,
    "platform" "SocialPlatform" NOT NULL,
    "providerPostId" TEXT NOT NULL,
    "url" TEXT,
    "caption" TEXT,
    "postedAt" TIMESTAMP(3),
    "lastViews" INTEGER NOT NULL DEFAULT 0,
    "paidViews" INTEGER NOT NULL DEFAULT 0,
    "lastLikes" INTEGER NOT NULL DEFAULT 0,
    "lastComments" INTEGER NOT NULL DEFAULT 0,
    "lastShares" INTEGER NOT NULL DEFAULT 0,
    "lastPolledAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "affiliate_posts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "affiliate_posts_platform_providerPostId_key" ON "affiliate_posts"("platform", "providerPostId");
CREATE INDEX "affiliate_posts_socialAccountId_idx" ON "affiliate_posts"("socialAccountId");

-- AddForeignKey
ALTER TABLE "affiliate_posts" ADD CONSTRAINT "affiliate_posts_socialAccountId_fkey" FOREIGN KEY ("socialAccountId") REFERENCES "affiliate_social_accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "affiliate_post_snapshots" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "views" INTEGER NOT NULL DEFAULT 0,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "comments" INTEGER NOT NULL DEFAULT 0,
    "shares" INTEGER NOT NULL DEFAULT 0,
    "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "affiliate_post_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "affiliate_post_snapshots_postId_capturedAt_idx" ON "affiliate_post_snapshots"("postId", "capturedAt");

-- AddForeignKey
ALTER TABLE "affiliate_post_snapshots" ADD CONSTRAINT "affiliate_post_snapshots_postId_fkey" FOREIGN KEY ("postId") REFERENCES "affiliate_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
