-- Migration: add_model_to_chat_messages
-- Generated: 2026-06-19T05:46:17.461Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_model_to_chat_messages`.
-- The generator emitted the full schema diff, which also included the
-- pre-existing accepted drift tracked in scripts/check-desktop-schema-drift.ts
-- (agent_configs, agent_eval_sets, budget_alerts, eval_runs, model_experiments,
-- subagent_model_overrides, usage_wallets, workspace_grants, signup_attributions).
-- Those table redefinitions were trimmed so this migration carries ONLY the
-- intended chat_messages change; the accepted-drift tables stay on the
-- allow-list and are addressed separately.

-- AlterTable
ALTER TABLE "chat_messages" ADD COLUMN "model" TEXT;
