-- Migration: add_user_buddy_look
-- Generated: 2026-10-01T02:25:56Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_user_buddy_look`.
-- The generator also re-emitted the signup_attributions index redefinition,
-- which is PRE-EXISTING drift already on the ACCEPTED_DRIFT allow-list in
-- scripts/check-desktop-schema-drift.ts, so it is intentionally omitted
-- (matching the 20260608203850_add_user_admin_scopes convention).
--
-- The only intended change is users.buddyLook (the JSON-encoded Shogo buddy
-- look, see prisma/schema.local.prisma).

-- AlterTable
ALTER TABLE "users" ADD COLUMN "buddyLook" TEXT;
