-- Migration: rbac_project_visibility
-- Generated: 2026-10-09T04:52:06.829Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name rbac_project_visibility`
-- and then hand-edited:
--   * `projects` already drifts from the migration history (see ACCEPTED_DRIFT in
--     scripts/check-desktop-schema-drift.ts), so Prisma emitted a full table
--     redefinition. A plain ADD COLUMN is equivalent and far less invasive.
--   * The unrelated `signup_attributions` RedefineIndex (also accepted drift) was
--     dropped: SQLite refuses to DROP an autoindex.
--   * The Member dedupe / project-owner -> admin data migration below must run
--     before the partial unique indexes are created.

-- Collapse duplicate workspace-scoped memberships, keeping the highest role and
-- preserving the billing-admin flag from any duplicate.
UPDATE "members" SET "isBillingAdmin" = true
WHERE "projectId" IS NULL AND "isBillingAdmin" = false AND EXISTS (
  SELECT 1 FROM "members" m2
  WHERE m2."userId" = "members"."userId" AND m2."workspaceId" = "members"."workspaceId"
    AND m2."projectId" IS NULL AND m2."isBillingAdmin" = true
);
DELETE FROM "members" WHERE "projectId" IS NULL AND "id" NOT IN (
  SELECT "id" FROM (
    SELECT "id", ROW_NUMBER() OVER (
      PARTITION BY "userId", "workspaceId"
      ORDER BY CASE "role" WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'member' THEN 2 ELSE 3 END, "createdAt"
    ) AS rn
    FROM "members" WHERE "projectId" IS NULL
  ) WHERE rn = 1
);

-- Collapse duplicate project-scoped memberships the same way.
DELETE FROM "members" WHERE "projectId" IS NOT NULL AND "id" NOT IN (
  SELECT "id" FROM (
    SELECT "id", ROW_NUMBER() OVER (
      PARTITION BY "userId", "projectId"
      ORDER BY CASE "role" WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'member' THEN 2 ELSE 3 END, "createdAt"
    ) AS rn
    FROM "members" WHERE "projectId" IS NOT NULL
  ) WHERE rn = 1
);

-- Project roles are admin / member / viewer; fold project-level owner into admin.
UPDATE "members" SET "role" = 'admin' WHERE "projectId" IS NOT NULL AND "role" = 'owner';

-- AlterTable
ALTER TABLE "projects" ADD COLUMN "visibility" TEXT NOT NULL DEFAULT 'workspace';

-- CreateIndex
CREATE UNIQUE INDEX "members_workspace_scope_key" ON "members"("userId", "workspaceId") WHERE "projectId" IS NULL;

-- CreateIndex
CREATE UNIQUE INDEX "members_project_scope_key" ON "members"("userId", "projectId") WHERE "projectId" IS NOT NULL;
