// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/db/index.ts',
    'src/react/index.ts',
    'src/agent/index.ts',
    'src/generators/index.ts',
    'src/email/index.ts',
    'src/email/server.ts',
    'src/tools/index.ts',
    'src/tools/server.ts',
    'src/memory/index.ts',
    'src/memory/server.ts',
    'src/voice/index.ts',
    'src/voice/server.ts',
    'src/voice/react/index.ts',
    'src/voice/native/index.ts',
    'src/voice/route/index.ts',
    'src/voice/route/signed-url.ts',
    'src/voice/route/tts-preview.ts',
    'src/voice/route/agent.ts',
    'src/voice/route/audio-tags.ts',
    'src/cli/deploy.ts',
    'src/cli/pkg.ts',
    // Back-compat shims for symbols that moved to @shogo-ai/{core,agent}.
    // Each compiles to a tiny re-export chunk; the actual implementation
    // lives in the published per-package dist.
    'src/logger.ts',
    'src/instrumentation.ts',
    'src/stream-buffer.ts',
    'src/chat-message.ts',
    'src/model-catalog/index.ts',
    'src/loop-detector.ts',
    'src/microcompact.ts',
    'src/prefix-fingerprint.ts',
    'src/tool-orchestration.ts',
    'src/hooks/index.ts',
    'src/model-router/index.ts',
    'src/pi-adapter.ts',
    'src/agent-loop.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: false,
  target: 'es2020',
  outDir: 'dist',
  external: [
    'react',
    'react-native',
    'mobx',
    'mobx-react-lite',
    '@elevenlabs/react',
    '@elevenlabs/react-native',
    'three',
    'expo-gl',
    'expo-three',
    '@prisma/client',
    '@prisma/internals',
    '@prisma/adapter-pg',
    '@prisma/adapter-libsql',
    'nodemailer',
    '@aws-sdk/client-ses',
    'better-sqlite3',
    'bun:sqlite',
    '@ai-sdk/openai-compatible',
    '@ai-sdk/provider',
    '@ai-sdk/provider-utils',
    '@ai-sdk/react',
    'ai',
    '@opentelemetry/api',
    '@opentelemetry/sdk-node',
    '@opentelemetry/exporter-trace-otlp-http',
    '@opentelemetry/sdk-trace-base',
    '@opentelemetry/resources',
    '@opentelemetry/semantic-conventions',
    '@mariozechner/pi-ai',
    '@mariozechner/pi-agent-core',
    // Extracted Shogo packages — back-compat re-export shims must
    // resolve to the published packages at runtime, not be inlined.
    '@shogo-ai/core',
    '@shogo-ai/core/logger',
    '@shogo-ai/core/instrumentation',
    '@shogo-ai/core/stream-buffer',
    '@shogo-ai/core/chat-message',
    '@shogo-ai/agent',
    '@shogo-ai/agent/agent-loop',
    '@shogo-ai/agent/pi-adapter',
    '@shogo-ai/agent/model-catalog',
    '@shogo-ai/agent/model-router',
    '@shogo-ai/agent/tool-orchestration',
    '@shogo-ai/agent/loop-detector',
    '@shogo-ai/agent/microcompact',
    '@shogo-ai/agent/prefix-fingerprint',
    '@shogo-ai/agent/hooks',
    '@shogo-ai/db',
    '@shogo-ai/email',
    '@shogo-ai/email/server',
    '@shogo-ai/voice',
    '@shogo-ai/voice/server',
    '@shogo-ai/voice/react',
    '@shogo-ai/voice/native',
    '@shogo-ai/voice/route',
    '@shogo-ai/voice/route/signed-url',
    '@shogo-ai/voice/route/tts-preview',
    '@shogo-ai/voice/route/agent',
    '@shogo-ai/voice/route/audio-tags',
    '@shogo-ai/cli',
    '@shogo-ai/cli/deploy',
    '@shogo-ai/cli/pkg',
  ],
})
