// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/db/index.ts',
    'src/react/index.ts',
    'src/agent/index.ts',
    'src/generators/index.ts',
    'src/email/index.ts',
    'src/email/server.ts',
    'src/tools/index.ts',
    'src/tools/server.ts',
    'src/memory/index.ts',
    'src/memory/server.ts',
    'src/voice/index.ts',
    'src/voice/server.ts',
    'src/voice/react/index.ts',
    'src/voice/native/index.ts',
    'src/voice/route/index.ts',
    'src/voice/route/signed-url.ts',
    'src/voice/route/tts-preview.ts',
    'src/voice/route/agent.ts',
    'src/voice/route/audio-tags.ts',
    'src/cli/deploy.ts',
    'src/cli/pkg.ts',
    'src/logger.ts',
    'src/instrumentation.ts',
    'src/stream-buffer.ts',
    'src/chat-message.ts',
    'src/model-catalog/index.ts',
    'src/loop-detector.ts',
    'src/microcompact.ts',
    'src/prefix-fingerprint.ts',
    'src/tool-orchestration.ts',
    'src/hooks/index.ts',
    'src/hooks/bundled/command-logger/handler.ts',
    'src/hooks/bundled/session-memory/handler.ts',
    'src/model-router/index.ts',
    'src/pi-adapter.ts',
    'src/agent-loop.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: false,
  target: 'es2020',
  outDir: 'dist',
  // Copy bundled hook metadata (HOOK.md) into dist so loadAllHooks works
  // when the SDK is consumed from `dist/` (production). Source-mode
  // consumers (tsconfig paths, `development` export condition) read the
  // .md files directly from `src/`.
  onSuccess:
    'mkdir -p dist/hooks/bundled/command-logger dist/hooks/bundled/session-memory && ' +
    'cp src/hooks/bundled/command-logger/HOOK.md dist/hooks/bundled/command-logger/HOOK.md && ' +
    'cp src/hooks/bundled/session-memory/HOOK.md dist/hooks/bundled/session-memory/HOOK.md',
  external: [
    'react',
    'react-native',
    'mobx',
    'mobx-react-lite',
    '@elevenlabs/react',
    '@elevenlabs/react-native',
    'three',
    'expo-gl',
    'expo-three',
    '@prisma/client',
    '@prisma/internals',
    '@prisma/adapter-pg',
    '@prisma/adapter-libsql',
    'nodemailer',
    '@aws-sdk/client-ses',
    'better-sqlite3',
    'bun:sqlite',
    '@ai-sdk/openai-compatible',
    '@ai-sdk/provider',
    '@ai-sdk/provider-utils',
    '@ai-sdk/react',
    'ai',
    '@opentelemetry/api',
    '@opentelemetry/sdk-node',
    '@opentelemetry/exporter-trace-otlp-http',
    '@opentelemetry/sdk-trace-base',
    '@opentelemetry/resources',
    '@opentelemetry/semantic-conventions',
    '@mariozechner/pi-ai',
    '@mariozechner/pi-agent-core',
  ],
})
