-- Migration: agent_config_model_default_auto
-- Generated: 2026-10-08T05:04:32.668Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name agent_config_model_default_auto`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_agent_configs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "heartbeatInterval" INTEGER NOT NULL DEFAULT 1800,
    "heartbeatEnabled" BOOLEAN NOT NULL DEFAULT false,
    "nextHeartbeatAt" DATETIME,
    "lastHeartbeatAt" DATETIME,
    "quietHoursStart" TEXT,
    "quietHoursEnd" TEXT,
    "quietHoursTimezone" TEXT,
    "channels" TEXT NOT NULL DEFAULT '[]',
    "modelProvider" TEXT NOT NULL DEFAULT 'anthropic',
    "modelName" TEXT NOT NULL DEFAULT 'auto',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "agent_configs_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_agent_configs" ("channels", "createdAt", "heartbeatEnabled", "heartbeatInterval", "id", "lastHeartbeatAt", "modelName", "modelProvider", "nextHeartbeatAt", "projectId", "quietHoursEnd", "quietHoursStart", "quietHoursTimezone", "updatedAt") SELECT "channels", "createdAt", "heartbeatEnabled", "heartbeatInterval", "id", "lastHeartbeatAt", "modelName", "modelProvider", "nextHeartbeatAt", "projectId", "quietHoursEnd", "quietHoursStart", "quietHoursTimezone", "updatedAt" FROM "agent_configs";
DROP TABLE "agent_configs";
ALTER TABLE "new_agent_configs" RENAME TO "agent_configs";
CREATE UNIQUE INDEX "agent_configs_projectId_key" ON "agent_configs"("projectId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

