// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
//
// Unit tests for `checkServerTsxDrift` + `healServerTsxDrift`.
//
// Drift = `server.tsx` is on disk but `shogo.config.json` declares a
// `customRoutesPath` and the file doesn't import / mount it. Heal mode
// is hybrid: SDK-generated files signal `regenerate` (caller runs
// `shogo generate`); hand-edited files are patched in place so the
// user's other edits are preserved.

import { describe, test, expect, beforeEach, afterEach } from 'bun:test'
import { mkdirSync, rmSync, existsSync, writeFileSync, readFileSync } from 'fs'
import { join } from 'path'
import { checkServerTsxDrift, healServerTsxDrift } from '../server-tsx-drift'

const TMP_ROOT = join(__dirname, '..', '..', '.test-tmp-server-tsx-drift')
let tmpDir: string
let counter = 0

function makeWorkspace(): string {
  counter++
  const dir = join(TMP_ROOT, `w-${counter}-${Date.now()}`)
  mkdirSync(dir, { recursive: true })
  return dir
}

function writeConfig(
  dir: string,
  opts: { customRoutesPath?: string | null; apiBasePath?: string } = {},
): void {
  const { customRoutesPath, apiBasePath } = opts
  const serverConfig: Record<string, unknown> = {}
  if (customRoutesPath !== null && customRoutesPath !== undefined) {
    serverConfig.customRoutesPath = customRoutesPath
  }
  if (apiBasePath !== undefined) {
    serverConfig.apiBasePath = apiBasePath
  }
  const config = {
    schema: './prisma/schema.prisma',
    outputs: [
      {
        dir: '.',
        generate: ['server'],
        fileExtension: 'tsx',
        serverConfig,
      },
    ],
  }
  writeFileSync(join(dir, 'shogo.config.json'), JSON.stringify(config, null, 2), 'utf-8')
}

function writeCustomRoutes(dir: string): void {
  writeFileSync(
    join(dir, 'custom-routes.ts'),
    "import { Hono } from 'hono'\nconst app = new Hono()\nexport default app\n",
    'utf-8',
  )
}

const IN_SYNC_SDK_SERVER = `/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import customRoutes from './custom-routes'

const app = new Hono()

app.get('/health', (c) => c.json({ ok: true }))
app.route('/api', createAllRoutes(prisma))
app.route('/api', customRoutes)

app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
Bun.serve({ port, fetch: app.fetch })
`

const STALE_SDK_SERVER = `/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'

const app = new Hono()

app.get('/health', (c) => c.json({ ok: true }))
app.route('/api', createAllRoutes(prisma))

app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
Bun.serve({ port, fetch: app.fetch })
`

const HAND_EDITED_SERVER = `import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import { createAllRoutes } from './src/generated/routes'
import { prisma } from './src/lib/db'
import { myCustomMiddleware } from './src/middleware'

const app = new Hono()

// Hand-rolled auth middleware — must run before any routes mount.
app.use('*', myCustomMiddleware())

app.get('/health', (c) => c.json({ ok: true }))
app.get('/dashboard', async (c) => {
  const stats = await prisma.user.count()
  return c.json({ stats })
})
app.route('/api', createAllRoutes(prisma))

app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
export default { port, fetch: app.fetch }
`

const HAND_EDITED_DOUBLE_QUOTES = `import { Hono } from "hono"
import { serveStatic } from "hono/bun"
import { createAllRoutes } from "./src/generated/routes"
import { prisma } from "./src/lib/db"

const app = new Hono()

app.get("/health", (c) => c.json({ ok: true }))
app.route("/api", createAllRoutes(prisma))

app.use("/*", serveStatic({ root: "./dist" }))
app.get("*", serveStatic({ path: "./dist/index.html" }))

const port = Number(process.env.PORT) || 3001
export default { port, fetch: app.fetch }
`

beforeEach(() => {
  tmpDir = makeWorkspace()
})

afterEach(() => {
  rmSync(TMP_ROOT, { recursive: true, force: true })
})

describe('checkServerTsxDrift', () => {
  test('in-sync SDK server (has import + mount) → drifted: false', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), IN_SYNC_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(false)
  })

  test('stale SDK server (missing import + mount) → drifted: true, looksAutoGenerated: true', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(true)
    expect(drift.looksAutoGenerated).toBe(true)
    expect(drift.customRoutesPath).toBe('./custom-routes')
    expect(drift.apiBasePath).toBe('/api')
    expect(drift.serverTsxPath).toBe(join(tmpDir, 'server.tsx'))
  })

  test('hand-edited server (missing import + mount) → drifted: true, looksAutoGenerated: false', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), HAND_EDITED_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(true)
    expect(drift.looksAutoGenerated).toBe(false)
  })

  test('customRoutesPath not configured → drifted: false', () => {
    writeConfig(tmpDir, { customRoutesPath: null })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(false)
  })

  test('custom-routes.ts not present → drifted: false', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(false)
  })

  test('server.tsx missing → drifted: false (missing-file path runs generate)', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(false)
  })

  test('shogo.config.json missing → drifted: false', () => {
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(false)
  })

  test('custom apiBasePath is honoured', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes', apiBasePath: '/v1' })
    writeCustomRoutes(tmpDir)
    // Build a fixture that mounts customRoutes under /api (the wrong
    // base) — should still drift because the config now says /v1.
    const misMounted = STALE_SDK_SERVER.replace(
      "app.route('/api', createAllRoutes(prisma))",
      `app.route('/api', createAllRoutes(prisma))
import customRoutes from './custom-routes'
app.route('/api', customRoutes)`,
    )
    writeFileSync(join(tmpDir, 'server.tsx'), misMounted, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(true)
    expect(drift.apiBasePath).toBe('/v1')
  })
})

describe('healServerTsxDrift', () => {
  test('stale SDK output → mode: regenerate (file untouched)', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    expect(drift.drifted).toBe(true)
    const heal = healServerTsxDrift(tmpDir, drift)

    expect(heal.mode).toBe('regenerate')
    // File on disk is unchanged — caller will run `shogo generate` to
    // overwrite it.
    const onDisk = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    expect(onDisk).toBe(STALE_SDK_SERVER)
  })

  test('hand-edited file → mode: patched, file gains exactly 2 lines, other content byte-identical', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), HAND_EDITED_SERVER, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)

    expect(heal.mode).toBe('patched')

    const after = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    // The two required lines are present.
    expect(after).toContain("import customRoutes from './custom-routes'")
    expect(after).toMatch(/app\.route\(\s*['"]\/api['"]\s*,\s*customRoutes\s*\)/)
    // Hand edits are preserved verbatim — middleware, dashboard route,
    // CRUD mount, static catch-all, custom comments.
    expect(after).toContain("import { myCustomMiddleware } from './src/middleware'")
    expect(after).toContain("app.use('*', myCustomMiddleware())")
    expect(after).toContain('Hand-rolled auth middleware')
    expect(after).toContain("app.get('/dashboard'")
    expect(after).toContain('await prisma.user.count()')
    expect(after).toContain("app.route('/api', createAllRoutes(prisma))")
    expect(after).toContain("app.use('/*', serveStatic({ root: './dist' }))")
    // The mount went in BEFORE the static catch-all so that custom
    // routes win over the SPA fallback.
    const mountIdx = after.search(/app\.route\(\s*['"]\/api['"]\s*,\s*customRoutes\s*\)/)
    const staticIdx = after.indexOf("app.use('/*', serveStatic")
    expect(mountIdx).toBeGreaterThan(0)
    expect(staticIdx).toBeGreaterThan(0)
    expect(mountIdx).toBeLessThan(staticIdx)
  })

  test('idempotent: running heal twice → patched, then noop', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), HAND_EDITED_SERVER, 'utf-8')

    const drift1 = checkServerTsxDrift(tmpDir)
    const heal1 = healServerTsxDrift(tmpDir, drift1)
    expect(heal1.mode).toBe('patched')

    // After the first heal, `checkServerTsxDrift` returns
    // { drifted: false } — but if the caller (gateway-tools) raced
    // they'd still hand us the stale `drift` object. The heal should
    // be a no-op in that case.
    const heal2 = healServerTsxDrift(tmpDir, drift1)
    expect(heal2.mode).toBe('noop')

    const drift2 = checkServerTsxDrift(tmpDir)
    expect(drift2.drifted).toBe(false)
  })

  test('double-quote fixture → patched import uses double quotes', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    writeFileSync(join(tmpDir, 'server.tsx'), HAND_EDITED_DOUBLE_QUOTES, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('patched')

    const after = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    expect(after).toContain('import customRoutes from "./custom-routes"')
    expect(after).toContain('app.route("/api", customRoutes)')
    // Did NOT introduce single quotes for the new lines.
    expect(after).not.toContain("import customRoutes from './custom-routes'")
  })

  test('no app.route, no static catch-all → inserts mount before export default', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeCustomRoutes(tmpDir)
    const minimal = `import { Hono } from 'hono'

const app = new Hono()

app.get('/health', (c) => c.json({ ok: true }))

const port = Number(process.env.PORT) || 3001
export default { port, fetch: app.fetch }
`
    writeFileSync(join(tmpDir, 'server.tsx'), minimal, 'utf-8')

    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('patched')

    const after = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    expect(after).toContain("import customRoutes from './custom-routes'")
    const mountIdx = after.search(/app\.route\(\s*['"]\/api['"]\s*,\s*customRoutes\s*\)/)
    const exportIdx = after.indexOf('export default')
    expect(mountIdx).toBeGreaterThan(0)
    expect(mountIdx).toBeLessThan(exportIdx)
  })

  test('drifted: false in → mode: noop (caller must check drift.drifted first)', () => {
    const heal = healServerTsxDrift(tmpDir, { drifted: false })
    expect(heal.mode).toBe('noop')
  })

  test('missing required drift fields → mode: failed', () => {
    const heal = healServerTsxDrift(tmpDir, {
      drifted: true,
      // missing customRoutesPath / apiBasePath / serverTsxPath
    })
    expect(heal.mode).toBe('failed')
  })
})

describe('server-tsx-drift gap coverage', () => {
  beforeEach(() => { tmpDir = makeWorkspace() })
  afterEach(() => { try { rmSync(tmpDir, { recursive: true, force: true }) } catch {} })

  test('DA:96 — malformed shogo.config.json → drifted: false (config catch returns null)', () => {
    writeFileSync(join(tmpDir, 'shogo.config.json'), '{ this is not: valid json', 'utf-8')
    writeFileSync(join(tmpDir, 'server.tsx'), STALE_SDK_SERVER, 'utf-8')
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    expect(checkServerTsxDrift(tmpDir).drifted).toBe(false)
  })

  test('DA:155 — readFileSync(server.tsx) throws → drifted: false (file is a directory)', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    mkdirSync(join(tmpDir, 'server.tsx'), { recursive: true })
    expect(checkServerTsxDrift(tmpDir).drifted).toBe(false)
  })

  test('DA:228 — heal readFileSync throws → mode: failed', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    // Synthesize a drifted result manually then make server.tsx unreadable.
    const drift = {
      drifted: true,
      looksAutoGenerated: false,
      serverTsxPath: join(tmpDir, 'server.tsx'),
      customRoutesPath: './custom-routes',
      apiBasePath: '/api',
    } as const
    mkdirSync(join(tmpDir, 'server.tsx'), { recursive: true })
    const heal = healServerTsxDrift(tmpDir, drift as any)
    expect(heal.mode).toBe('failed')
    if (heal.mode === 'failed') expect(heal.reason).toMatch(/read failed/)
  })

  test('DA:252-256 — no import anchor → failed with import-insertion reason', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    writeFileSync(
      join(tmpDir, 'server.tsx'),
      "const app = { route: () => {} }\nexport default app\n",
      'utf-8',
    )
    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('failed')
    if (heal.mode === 'failed') expect(heal.reason).toMatch(/customRoutes import/)
  })

  test('DA:264-268 — no mount anchor → failed with mount-insertion reason', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    writeFileSync(
      join(tmpDir, 'server.tsx'),
      "import { something } from 'somewhere'\nconst x = 1\n",
      'utf-8',
    )
    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('failed')
    if (heal.mode === 'failed') expect(heal.reason).toMatch(/app\.route mount/)
  })

  test('DA:274 — writeFileSync throws → failed with write-failed reason', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    writeFileSync(join(tmpDir, 'server.tsx'), HAND_EDITED_SERVER, 'utf-8')
    const { chmodSync } = require('fs')
    chmodSync(join(tmpDir, 'server.tsx'), 0o444)
    try {
      const drift = checkServerTsxDrift(tmpDir)
      const heal = healServerTsxDrift(tmpDir, drift)
      expect(heal.mode).toBe('failed')
      if (heal.mode === 'failed') expect(heal.reason).toMatch(/write failed/)
    } finally {
      chmodSync(join(tmpDir, 'server.tsx'), 0o644)
    }
  })

  test('DA:298-300 — pickQuoteStyle falls back to count when no Hono import', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    const src = "import x from 'a'\nimport y from 'b'\nconst app = { route: () => {} }\napp.route('/api', null)\nexport default app\n"
    writeFileSync(join(tmpDir, 'server.tsx'), src, 'utf-8')
    const drift = checkServerTsxDrift(tmpDir)
    healServerTsxDrift(tmpDir, drift)
    const patched = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    expect(patched).toContain("import customRoutes from './custom-routes'")
  })

  test('DA:362-363 — insertMount anchor 2 fires after existing app.route lines', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes', apiBasePath: '/api' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    const src = [
      "import { Hono } from 'hono'",
      "const app = new Hono()",
      "app.route('/api', { fetch: () => {} })",
      "export default app",
      '',
    ].join('\n')
    writeFileSync(join(tmpDir, 'server.tsx'), src, 'utf-8')
    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('patched')
    const patched = readFileSync(join(tmpDir, 'server.tsx'), 'utf-8')
    const lines = patched.split('\n')
    const apiRouteIdx = lines.findIndex(l => l.includes("app.route('/api'") && !l.includes('customRoutes'))
    const mountIdx = lines.findIndex(l => l.includes('customRoutes') && l.includes('app.route'))
    expect(mountIdx).toBeGreaterThan(apiRouteIdx)
  })

  test('DA:377-379 — insertMount fallback fires when no anchor matches (mount returns source)', () => {
    writeConfig(tmpDir, { customRoutesPath: './custom-routes', apiBasePath: '/api' })
    writeFileSync(join(tmpDir, 'custom-routes.ts'), 'export default {}', 'utf-8')
    // Has import but no app.route, no static catch-all, no export default, no Bun.serve.
    const src = "import { something } from 'somewhere'\nconst foo = 1\n"
    writeFileSync(join(tmpDir, 'server.tsx'), src, 'utf-8')
    const drift = checkServerTsxDrift(tmpDir)
    const heal = healServerTsxDrift(tmpDir, drift)
    expect(heal.mode).toBe('failed')
    if (heal.mode === 'failed') expect(heal.reason).toMatch(/app\.route mount/)
  })
})
