-- Migration: add_meeting_notes
-- Generated: 2026-09-30T00:56:00.045Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_meeting_notes`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- CreateTable
CREATE TABLE "meeting_templates" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "instructions" TEXT NOT NULL,
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "meeting_templates_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_meetings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT,
    "audioPath" TEXT NOT NULL DEFAULT '',
    "transcript" TEXT,
    "summary" TEXT,
    "notes" TEXT,
    "enhancedNotes" TEXT,
    "actionItems" TEXT,
    "enhanceStatus" TEXT,
    "enhanceError" TEXT,
    "templateId" TEXT,
    "duration" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'recording',
    "source" TEXT NOT NULL DEFAULT 'desktop',
    "app" TEXT,
    "recordingId" TEXT,
    "userId" TEXT,
    "shareToken" TEXT,
    "sharedAt" DATETIME,
    "projectId" TEXT,
    "workspaceId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "meetings_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "meetings_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_meetings" ("audioPath", "createdAt", "duration", "id", "projectId", "status", "summary", "title", "transcript", "updatedAt", "workspaceId") SELECT "audioPath", "createdAt", "duration", "id", "projectId", "status", "summary", "title", "transcript", "updatedAt", "workspaceId" FROM "meetings";
DROP TABLE "meetings";
ALTER TABLE "new_meetings" RENAME TO "meetings";
CREATE UNIQUE INDEX "meetings_workspaceId_recordingId_key" ON "meetings"("workspaceId", "recordingId");
CREATE UNIQUE INDEX "meetings_shareToken_key" ON "meetings"("shareToken");
CREATE INDEX "meetings_workspaceId_idx" ON "meetings"("workspaceId");
CREATE INDEX "meetings_workspaceId_createdAt_idx" ON "meetings"("workspaceId", "createdAt");
CREATE INDEX "meetings_projectId_idx" ON "meetings"("projectId");
CREATE INDEX "meetings_userId_idx" ON "meetings"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "meeting_templates_workspaceId_idx" ON "meeting_templates"("workspaceId");
