-- Migration: add_slack_agent
-- Generated: 2026-09-15T07:10:50.532Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_slack_agent`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).
--
-- Manual edit: the raw diff also emitted an unrelated `RedefineIndex` for
-- `signup_attributions` (DROP INDEX "sqlite_autoindex_signup_attributions_2"
-- + recreate as a named unique index) — pre-existing drift between that
-- table's original inline-UNIQUE creation SQL and Prisma's canonical
-- named-index form, unrelated to this Slack schema change. SQLite refuses to
-- DROP an autoindex backing a UNIQUE/PK constraint directly (`index
-- associated with UNIQUE or PRIMARY KEY constraint cannot be dropped`), which
-- fails `bun run check:migrations`. Removed here since fixing that drift
-- needs its own RedefineTables migration, not a bare DROP INDEX; the
-- constraint's runtime behavior (unique on `userId`) is unaffected either way.

-- CreateTable
CREATE TABLE "slack_workspace_installations" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "slackTeamId" TEXT NOT NULL,
    "slackTeamName" TEXT,
    "botAccessTokenEncrypted" TEXT NOT NULL,
    "botUserId" TEXT,
    "installerUserId" TEXT,
    "defaultProjectId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "slack_workspace_installations_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "slack_workspace_installations_defaultProjectId_fkey" FOREIGN KEY ("defaultProjectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "slack_user_links" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slackTeamId" TEXT NOT NULL,
    "slackUserId" TEXT NOT NULL,
    "shogoUserId" TEXT NOT NULL,
    "personalDefaultProjectId" TEXT,
    "lastUsedProjectId" TEXT,
    "activeDmChannelId" TEXT,
    "activeDmThreadTs" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "slack_user_links_slackTeamId_fkey" FOREIGN KEY ("slackTeamId") REFERENCES "slack_workspace_installations" ("slackTeamId") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "slack_user_links_shogoUserId_fkey" FOREIGN KEY ("shogoUserId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "slack_user_links_personalDefaultProjectId_fkey" FOREIGN KEY ("personalDefaultProjectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "slack_user_links_lastUsedProjectId_fkey" FOREIGN KEY ("lastUsedProjectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "slack_channel_settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slackTeamId" TEXT NOT NULL,
    "slackChannelId" TEXT NOT NULL,
    "defaultProjectId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "slack_channel_settings_slackTeamId_fkey" FOREIGN KEY ("slackTeamId") REFERENCES "slack_workspace_installations" ("slackTeamId") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "slack_channel_settings_defaultProjectId_fkey" FOREIGN KEY ("defaultProjectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "slack_project_routing_rules" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slackTeamId" TEXT NOT NULL,
    "keyword" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "slack_project_routing_rules_slackTeamId_fkey" FOREIGN KEY ("slackTeamId") REFERENCES "slack_workspace_installations" ("slackTeamId") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "slack_project_routing_rules_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_agent_configs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "heartbeatInterval" INTEGER NOT NULL DEFAULT 1800,
    "heartbeatEnabled" BOOLEAN NOT NULL DEFAULT false,
    "nextHeartbeatAt" DATETIME,
    "lastHeartbeatAt" DATETIME,
    "quietHoursStart" TEXT,
    "quietHoursEnd" TEXT,
    "quietHoursTimezone" TEXT,
    "channels" TEXT NOT NULL DEFAULT '[]',
    "modelProvider" TEXT NOT NULL DEFAULT 'anthropic',
    "modelName" TEXT NOT NULL DEFAULT 'claude-haiku-4-5',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "agent_configs_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_agent_configs" ("channels", "createdAt", "heartbeatEnabled", "heartbeatInterval", "id", "lastHeartbeatAt", "modelName", "modelProvider", "nextHeartbeatAt", "projectId", "quietHoursEnd", "quietHoursStart", "quietHoursTimezone", "updatedAt") SELECT "channels", "createdAt", "heartbeatEnabled", "heartbeatInterval", "id", "lastHeartbeatAt", "modelName", "modelProvider", "nextHeartbeatAt", "projectId", "quietHoursEnd", "quietHoursStart", "quietHoursTimezone", "updatedAt" FROM "agent_configs";
DROP TABLE "agent_configs";
ALTER TABLE "new_agent_configs" RENAME TO "agent_configs";
CREATE UNIQUE INDEX "agent_configs_projectId_key" ON "agent_configs"("projectId");
CREATE TABLE "new_agent_eval_sets" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "projectId" TEXT,
    "agentType" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "examples" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "agent_eval_sets_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "agent_eval_sets_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_agent_eval_sets" ("agentType", "createdAt", "createdBy", "description", "enabled", "examples", "id", "name", "projectId", "updatedAt", "workspaceId") SELECT "agentType", "createdAt", "createdBy", "description", "enabled", "examples", "id", "name", "projectId", "updatedAt", "workspaceId" FROM "agent_eval_sets";
DROP TABLE "agent_eval_sets";
ALTER TABLE "new_agent_eval_sets" RENAME TO "agent_eval_sets";
CREATE INDEX "agent_eval_sets_workspaceId_agentType_idx" ON "agent_eval_sets"("workspaceId", "agentType");
CREATE INDEX "agent_eval_sets_workspaceId_projectId_idx" ON "agent_eval_sets"("workspaceId", "projectId");
CREATE TABLE "new_budget_alerts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "creditLimit" REAL NOT NULL,
    "periodType" TEXT NOT NULL DEFAULT 'monthly',
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "autoThrottle" BOOLEAN NOT NULL DEFAULT false,
    "throttleToModel" TEXT,
    "notifyEmail" BOOLEAN NOT NULL DEFAULT true,
    "lastTriggeredAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "budget_alerts_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_budget_alerts" ("autoThrottle", "createdAt", "creditLimit", "enabled", "id", "lastTriggeredAt", "name", "notifyEmail", "periodType", "throttleToModel", "updatedAt", "workspaceId") SELECT "autoThrottle", "createdAt", "creditLimit", "enabled", "id", "lastTriggeredAt", "name", "notifyEmail", "periodType", "throttleToModel", "updatedAt", "workspaceId" FROM "budget_alerts";
DROP TABLE "budget_alerts";
ALTER TABLE "new_budget_alerts" RENAME TO "budget_alerts";
CREATE INDEX "budget_alerts_workspaceId_idx" ON "budget_alerts"("workspaceId");
CREATE TABLE "new_eval_runs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "track" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "workers" INTEGER NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "label" TEXT,
    "tags" TEXT NOT NULL DEFAULT '[]',
    "triggeredBy" TEXT,
    "pid" INTEGER,
    "jobName" TEXT,
    "error" TEXT,
    "summary" TEXT,
    "cost" TEXT,
    "byCategory" TEXT,
    "resources" TEXT,
    "progress" TEXT,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_eval_runs" ("byCategory", "completedAt", "cost", "createdAt", "error", "id", "jobName", "label", "model", "pid", "progress", "resources", "startedAt", "status", "summary", "tags", "track", "triggeredBy", "updatedAt", "workers") SELECT "byCategory", "completedAt", "cost", "createdAt", "error", "id", "jobName", "label", "model", "pid", "progress", "resources", "startedAt", "status", "summary", coalesce("tags", '[]') AS "tags", "track", "triggeredBy", "updatedAt", "workers" FROM "eval_runs";
DROP TABLE "eval_runs";
ALTER TABLE "new_eval_runs" RENAME TO "eval_runs";
CREATE INDEX "eval_runs_status_idx" ON "eval_runs"("status");
CREATE INDEX "eval_runs_createdAt_idx" ON "eval_runs"("createdAt");
CREATE TABLE "new_model_experiments" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "projectId" TEXT,
    "name" TEXT NOT NULL,
    "agentType" TEXT NOT NULL,
    "modelA" TEXT NOT NULL,
    "modelB" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'running',
    "splitPercentage" INTEGER NOT NULL DEFAULT 50,
    "expectedEndAt" DATETIME,
    "totalRunsA" INTEGER NOT NULL DEFAULT 0,
    "totalRunsB" INTEGER NOT NULL DEFAULT 0,
    "totalCostA" REAL NOT NULL DEFAULT 0,
    "totalCostB" REAL NOT NULL DEFAULT 0,
    "totalTokensA" INTEGER NOT NULL DEFAULT 0,
    "totalTokensB" INTEGER NOT NULL DEFAULT 0,
    "successRateA" REAL NOT NULL DEFAULT 0,
    "successRateB" REAL NOT NULL DEFAULT 0,
    "avgLatencyMsA" REAL NOT NULL DEFAULT 0,
    "avgLatencyMsB" REAL NOT NULL DEFAULT 0,
    "escalationsA" INTEGER NOT NULL DEFAULT 0,
    "escalationsB" INTEGER NOT NULL DEFAULT 0,
    "loopDetectedA" INTEGER NOT NULL DEFAULT 0,
    "loopDetectedB" INTEGER NOT NULL DEFAULT 0,
    "hitMaxTurnsA" INTEGER NOT NULL DEFAULT 0,
    "hitMaxTurnsB" INTEGER NOT NULL DEFAULT 0,
    "responseEmptyA" INTEGER NOT NULL DEFAULT 0,
    "responseEmptyB" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "model_experiments_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "model_experiments_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_model_experiments" ("agentType", "avgLatencyMsA", "avgLatencyMsB", "createdAt", "escalationsA", "escalationsB", "expectedEndAt", "hitMaxTurnsA", "hitMaxTurnsB", "id", "loopDetectedA", "loopDetectedB", "modelA", "modelB", "name", "projectId", "responseEmptyA", "responseEmptyB", "splitPercentage", "status", "successRateA", "successRateB", "totalCostA", "totalCostB", "totalRunsA", "totalRunsB", "totalTokensA", "totalTokensB", "updatedAt", "workspaceId") SELECT "agentType", "avgLatencyMsA", "avgLatencyMsB", "createdAt", "escalationsA", "escalationsB", "expectedEndAt", "hitMaxTurnsA", "hitMaxTurnsB", "id", "loopDetectedA", "loopDetectedB", "modelA", "modelB", "name", "projectId", "responseEmptyA", "responseEmptyB", "splitPercentage", "status", "successRateA", "successRateB", "totalCostA", "totalCostB", "totalRunsA", "totalRunsB", "totalTokensA", "totalTokensB", "updatedAt", "workspaceId" FROM "model_experiments";
DROP TABLE "model_experiments";
ALTER TABLE "new_model_experiments" RENAME TO "model_experiments";
CREATE INDEX "model_experiments_workspaceId_idx" ON "model_experiments"("workspaceId");
CREATE INDEX "model_experiments_status_idx" ON "model_experiments"("status");
CREATE INDEX "model_experiments_workspaceId_agentType_status_idx" ON "model_experiments"("workspaceId", "agentType", "status");
CREATE TABLE "new_projects" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "workspaceId" TEXT NOT NULL,
    "tier" TEXT NOT NULL DEFAULT 'starter',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "schemas" TEXT NOT NULL DEFAULT '[]',
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "folderId" TEXT,
    "publishedSubdomain" TEXT,
    "publishedAt" DATETIME,
    "publishStatus" TEXT NOT NULL DEFAULT 'idle',
    "publishError" TEXT,
    "publishStatusAt" DATETIME,
    "publishedCommitSha" TEXT,
    "publishedTag" TEXT,
    "publishedAlwaysOn" BOOLEAN NOT NULL DEFAULT false,
    "accessLevel" TEXT NOT NULL DEFAULT 'anyone',
    "sitePasswordHash" TEXT,
    "category" TEXT,
    "siteTitle" TEXT,
    "siteDescription" TEXT,
    "thumbnailUrl" TEXT,
    "templateId" TEXT,
    "knativeServiceName" TEXT,
    "settings" TEXT,
    "lastMessageAt" DATETIME,
    "workingMode" TEXT NOT NULL DEFAULT 'managed',
    "runtimeEnabled" BOOLEAN NOT NULL DEFAULT true,
    "slackEnabled" BOOLEAN NOT NULL DEFAULT true,
    "trustLevel" TEXT NOT NULL DEFAULT 'trusted',
    "preferredInstanceId" TEXT,
    "preferredInstancePolicy" TEXT NOT NULL DEFAULT 'pinned',
    "cloudSyncMode" TEXT NOT NULL DEFAULT 'git_only',
    CONSTRAINT "projects_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "projects_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "folders" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "projects_preferredInstanceId_fkey" FOREIGN KEY ("preferredInstanceId") REFERENCES "instances" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_projects" ("accessLevel", "category", "cloudSyncMode", "createdAt", "createdBy", "description", "folderId", "id", "knativeServiceName", "lastMessageAt", "name", "preferredInstanceId", "preferredInstancePolicy", "publishError", "publishStatus", "publishStatusAt", "publishedAlwaysOn", "publishedAt", "publishedCommitSha", "publishedSubdomain", "publishedTag", "runtimeEnabled", "schemas", "settings", "siteDescription", "sitePasswordHash", "siteTitle", "status", "templateId", "thumbnailUrl", "tier", "trustLevel", "updatedAt", "workingMode", "workspaceId") SELECT "accessLevel", "category", "cloudSyncMode", "createdAt", "createdBy", "description", "folderId", "id", "knativeServiceName", "lastMessageAt", "name", "preferredInstanceId", "preferredInstancePolicy", "publishError", "publishStatus", "publishStatusAt", "publishedAlwaysOn", "publishedAt", "publishedCommitSha", "publishedSubdomain", "publishedTag", "runtimeEnabled", "schemas", "settings", "siteDescription", "sitePasswordHash", "siteTitle", "status", "templateId", "thumbnailUrl", "tier", "trustLevel", "updatedAt", "workingMode", "workspaceId" FROM "projects";
DROP TABLE "projects";
ALTER TABLE "new_projects" RENAME TO "projects";
CREATE UNIQUE INDEX "projects_publishedSubdomain_key" ON "projects"("publishedSubdomain");
CREATE INDEX "projects_workspaceId_idx" ON "projects"("workspaceId");
CREATE INDEX "projects_folderId_idx" ON "projects"("folderId");
CREATE INDEX "projects_preferredInstanceId_idx" ON "projects"("preferredInstanceId");
CREATE TABLE "new_subagent_model_overrides" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "projectId" TEXT,
    "agentType" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "provider" TEXT,
    "updatedBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "subagent_model_overrides_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "subagent_model_overrides_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_subagent_model_overrides" ("agentType", "createdAt", "id", "model", "projectId", "provider", "updatedAt", "updatedBy", "workspaceId") SELECT "agentType", "createdAt", "id", "model", "projectId", "provider", "updatedAt", "updatedBy", "workspaceId" FROM "subagent_model_overrides";
DROP TABLE "subagent_model_overrides";
ALTER TABLE "new_subagent_model_overrides" RENAME TO "subagent_model_overrides";
CREATE INDEX "subagent_model_overrides_workspaceId_idx" ON "subagent_model_overrides"("workspaceId");
CREATE INDEX "subagent_model_overrides_projectId_idx" ON "subagent_model_overrides"("projectId");
CREATE UNIQUE INDEX "subagent_model_overrides_workspaceId_projectId_agentType_key" ON "subagent_model_overrides"("workspaceId", "projectId", "agentType");
CREATE TABLE "new_usage_wallets" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "monthlyIncludedUsd" REAL NOT NULL DEFAULT 0,
    "dailyIncludedUsd" REAL NOT NULL DEFAULT 0,
    "monthlyIncludedAllocationUsd" REAL NOT NULL DEFAULT 0,
    "dailyUsedThisMonthUsd" REAL NOT NULL DEFAULT 0,
    "overageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "overageHardLimitUsd" REAL,
    "overageAccumulatedUsd" REAL NOT NULL DEFAULT 0,
    "overageBilledUsd" REAL NOT NULL DEFAULT 0,
    "alertsSentThisPeriod" TEXT,
    "stripeMeteredItemId" TEXT,
    "anniversaryDay" INTEGER NOT NULL,
    "lastDailyReset" DATETIME NOT NULL,
    "lastMonthlyReset" DATETIME NOT NULL,
    "fiveHourWindowStart" DATETIME,
    "fiveHourUsedUsd" REAL NOT NULL DEFAULT 0,
    "weeklyWindowStart" DATETIME,
    "weeklyUsedUsd" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "usage_wallets_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_usage_wallets" ("alertsSentThisPeriod", "anniversaryDay", "createdAt", "dailyIncludedUsd", "dailyUsedThisMonthUsd", "fiveHourUsedUsd", "fiveHourWindowStart", "id", "lastDailyReset", "lastMonthlyReset", "monthlyIncludedAllocationUsd", "monthlyIncludedUsd", "overageAccumulatedUsd", "overageBilledUsd", "overageEnabled", "overageHardLimitUsd", "stripeMeteredItemId", "updatedAt", "weeklyUsedUsd", "weeklyWindowStart", "workspaceId") SELECT "alertsSentThisPeriod", "anniversaryDay", "createdAt", "dailyIncludedUsd", "dailyUsedThisMonthUsd", "fiveHourUsedUsd", "fiveHourWindowStart", "id", "lastDailyReset", "lastMonthlyReset", "monthlyIncludedAllocationUsd", "monthlyIncludedUsd", "overageAccumulatedUsd", "overageBilledUsd", "overageEnabled", "overageHardLimitUsd", "stripeMeteredItemId", "updatedAt", "weeklyUsedUsd", "weeklyWindowStart", "workspaceId" FROM "usage_wallets";
DROP TABLE "usage_wallets";
ALTER TABLE "new_usage_wallets" RENAME TO "usage_wallets";
CREATE UNIQUE INDEX "usage_wallets_workspaceId_key" ON "usage_wallets"("workspaceId");
CREATE TABLE "new_workspace_grants" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "freeSeats" INTEGER NOT NULL DEFAULT 0,
    "monthlyIncludedUsd" REAL NOT NULL DEFAULT 0,
    "planId" TEXT,
    "startsAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" DATETIME,
    "note" TEXT,
    "createdByUserId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "workspace_grants_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_workspace_grants" ("createdAt", "createdByUserId", "expiresAt", "freeSeats", "id", "monthlyIncludedUsd", "note", "planId", "startsAt", "updatedAt", "workspaceId") SELECT "createdAt", "createdByUserId", "expiresAt", "freeSeats", "id", "monthlyIncludedUsd", "note", "planId", "startsAt", "updatedAt", "workspaceId" FROM "workspace_grants";
DROP TABLE "workspace_grants";
ALTER TABLE "new_workspace_grants" RENAME TO "workspace_grants";
CREATE INDEX "workspace_grants_workspaceId_expiresAt_idx" ON "workspace_grants"("workspaceId", "expiresAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "slack_workspace_installations_workspaceId_key" ON "slack_workspace_installations"("workspaceId");

-- CreateIndex
CREATE UNIQUE INDEX "slack_workspace_installations_slackTeamId_key" ON "slack_workspace_installations"("slackTeamId");

-- CreateIndex
CREATE INDEX "slack_workspace_installations_defaultProjectId_idx" ON "slack_workspace_installations"("defaultProjectId");

-- CreateIndex
CREATE INDEX "slack_user_links_shogoUserId_idx" ON "slack_user_links"("shogoUserId");

-- CreateIndex
CREATE INDEX "slack_user_links_personalDefaultProjectId_idx" ON "slack_user_links"("personalDefaultProjectId");

-- CreateIndex
CREATE INDEX "slack_user_links_lastUsedProjectId_idx" ON "slack_user_links"("lastUsedProjectId");

-- CreateIndex
CREATE UNIQUE INDEX "slack_user_links_slackTeamId_slackUserId_key" ON "slack_user_links"("slackTeamId", "slackUserId");

-- CreateIndex
CREATE INDEX "slack_channel_settings_defaultProjectId_idx" ON "slack_channel_settings"("defaultProjectId");

-- CreateIndex
CREATE UNIQUE INDEX "slack_channel_settings_slackTeamId_slackChannelId_key" ON "slack_channel_settings"("slackTeamId", "slackChannelId");

-- CreateIndex
CREATE INDEX "slack_project_routing_rules_projectId_idx" ON "slack_project_routing_rules"("projectId");

-- CreateIndex
CREATE UNIQUE INDEX "slack_project_routing_rules_slackTeamId_keyword_key" ON "slack_project_routing_rules"("slackTeamId", "keyword");

