-- Migration: add_remote_ssh_hosts
-- Generated: 2026-09-29T04:57:34.703Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_remote_ssh_hosts`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- CreateTable
CREATE TABLE "remote_hosts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "label" TEXT NOT NULL,
    "sshTarget" TEXT NOT NULL,
    "port" INTEGER,
    "identityFile" TEXT,
    "platform" TEXT,
    "lastConnectedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_projects" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "hidden" BOOLEAN NOT NULL DEFAULT false,
    "description" TEXT,
    "workspaceId" TEXT NOT NULL,
    "tier" TEXT NOT NULL DEFAULT 'starter',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "schemas" TEXT NOT NULL DEFAULT '[]',
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "folderId" TEXT,
    "publishedSubdomain" TEXT,
    "publishedAt" DATETIME,
    "publishStatus" TEXT NOT NULL DEFAULT 'idle',
    "publishError" TEXT,
    "publishStatusAt" DATETIME,
    "publishedCommitSha" TEXT,
    "publishedTag" TEXT,
    "publishedAlwaysOn" BOOLEAN NOT NULL DEFAULT false,
    "accessLevel" TEXT NOT NULL DEFAULT 'anyone',
    "sitePasswordHash" TEXT,
    "category" TEXT,
    "siteTitle" TEXT,
    "siteDescription" TEXT,
    "thumbnailUrl" TEXT,
    "templateId" TEXT,
    "knativeServiceName" TEXT,
    "settings" TEXT,
    "lastMessageAt" DATETIME,
    "workingMode" TEXT NOT NULL DEFAULT 'managed',
    "runtimeEnabled" BOOLEAN NOT NULL DEFAULT true,
    "slackEnabled" BOOLEAN NOT NULL DEFAULT true,
    "trustLevel" TEXT NOT NULL DEFAULT 'trusted',
    "preferredInstanceId" TEXT,
    "preferredInstancePolicy" TEXT NOT NULL DEFAULT 'pinned',
    "cloudSyncMode" TEXT NOT NULL DEFAULT 'git_only',
    "remoteHostId" TEXT,
    CONSTRAINT "projects_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "projects_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "folders" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "projects_preferredInstanceId_fkey" FOREIGN KEY ("preferredInstanceId") REFERENCES "instances" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "projects_remoteHostId_fkey" FOREIGN KEY ("remoteHostId") REFERENCES "remote_hosts" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_projects" ("accessLevel", "category", "cloudSyncMode", "createdAt", "createdBy", "description", "folderId", "hidden", "id", "knativeServiceName", "lastMessageAt", "name", "preferredInstanceId", "preferredInstancePolicy", "publishError", "publishStatus", "publishStatusAt", "publishedAlwaysOn", "publishedAt", "publishedCommitSha", "publishedSubdomain", "publishedTag", "runtimeEnabled", "schemas", "settings", "siteDescription", "sitePasswordHash", "siteTitle", "slackEnabled", "status", "templateId", "thumbnailUrl", "tier", "trustLevel", "updatedAt", "workingMode", "workspaceId") SELECT "accessLevel", "category", "cloudSyncMode", "createdAt", "createdBy", "description", "folderId", "hidden", "id", "knativeServiceName", "lastMessageAt", "name", "preferredInstanceId", "preferredInstancePolicy", "publishError", "publishStatus", "publishStatusAt", "publishedAlwaysOn", "publishedAt", "publishedCommitSha", "publishedSubdomain", "publishedTag", "runtimeEnabled", "schemas", "settings", "siteDescription", "sitePasswordHash", "siteTitle", "slackEnabled", "status", "templateId", "thumbnailUrl", "tier", "trustLevel", "updatedAt", "workingMode", "workspaceId" FROM "projects";
DROP TABLE "projects";
ALTER TABLE "new_projects" RENAME TO "projects";
CREATE UNIQUE INDEX "projects_publishedSubdomain_key" ON "projects"("publishedSubdomain");
CREATE INDEX "projects_workspaceId_idx" ON "projects"("workspaceId");
CREATE INDEX "projects_workspaceId_hidden_idx" ON "projects"("workspaceId", "hidden");
CREATE INDEX "projects_folderId_idx" ON "projects"("folderId");
CREATE INDEX "projects_preferredInstanceId_idx" ON "projects"("preferredInstanceId");
CREATE INDEX "projects_remoteHostId_idx" ON "projects"("remoteHostId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "remote_hosts_sshTarget_idx" ON "remote_hosts"("sshTarget");
