// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * server.tsx drift detection + hybrid self-heal.
 *
 * The auto-mount infrastructure (`generateServer()` →
 * `shogo.config.json#serverConfig.customRoutesPath`) produces a
 * `server.tsx` that imports `custom-routes.ts` and mounts it under
 * `/api/`. That works for fresh workspaces. It silently breaks for
 * **drifted** workspaces — workspaces whose on-disk `server.tsx`
 * predates the addition of `customRoutesPath` to `shogo.config.json`,
 * or whose `server.tsx` was hand-edited and lost the mount.
 *
 * `PreviewManager.startApiServer()` only re-runs `shogo generate` when
 * `server.tsx` is missing entirely; otherwise it spawns whatever's on
 * disk. A stale file with no `app.route('/api', customRoutes)` causes
 * `/api/<route>` requests to fall through to the static catch-all,
 * which returns the SPA's `index.html` with HTTP 200 — masking the
 * problem as a routing issue rather than a missing import.
 *
 * This module supplies two helpers:
 *   - `checkServerTsxDrift(cwd)` — read-only detection. Reads
 *     `shogo.config.json`, locates the `server` output entry, and
 *     verifies the on-disk `server.tsx` contains both the
 *     `customRoutes` import and the mount line.
 *   - `healServerTsxDrift(cwd, drift)` — hybrid heal. Stale SDK-
 *     generated files (identified by the SDK's auto-gen header) are
 *     signalled for full regeneration (`{ mode: 'regenerate' }`); the
 *     caller runs `runShogoGenerate()` or `sync()`. Hand-edited files
 *     are patched in place — exactly two lines inserted, every other
 *     byte preserved.
 *
 * Both helpers are pure I/O on the workspace directory; no
 * dependencies on `PreviewManager`, so they're trivially unit-testable.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const LOG_PREFIX = 'server-tsx-drift'

/** Marker emitted by `generateServer()` — see
 *  `packages/sdk/src/generators/server-generator.ts:75`. Used by the
 *  heal helper to decide between regenerating (machine-written →
 *  overwrite is safe) and patching (hand-edited → preserve everything
 *  else). */
const SDK_AUTOGEN_MARKER = 'Auto-generated by @shogo-ai/sdk'

export interface DriftResult {
  drifted: boolean
  reason?: string
  customRoutesPath?: string
  apiBasePath?: string
  serverTsxPath?: string
  /** Only set when `drifted === true`. Drives the heal mode. */
  looksAutoGenerated?: boolean
}

export interface HealResult {
  mode: 'regenerate' | 'patched' | 'noop' | 'failed'
  reason?: string
  serverTsxPath?: string
}

interface ServerOutputEntry {
  dir?: string
  generate?: string[]
  fileExtension?: 'ts' | 'tsx'
  serverConfig?: {
    customRoutesPath?: string
    apiBasePath?: string
  }
}

interface ShogoConfig {
  outputs?: ServerOutputEntry[]
}

/**
 * Locate the `outputs[]` entry that emits the server, returning the
 * resolved server file path + the config values the drift check
 * cares about. Returns `null` when the workspace doesn't declare a
 * `'server'` output at all — in that case there's nothing to check.
 */
function resolveServerOutput(cwd: string): {
  serverTsxPath: string
  customRoutesPath: string
  apiBasePath: string
} | null {
  const configPath = join(cwd, 'shogo.config.json')
  if (!existsSync(configPath)) return null

  let parsed: ShogoConfig
  try {
    parsed = JSON.parse(readFileSync(configPath, 'utf-8')) as ShogoConfig
  } catch {
    // Malformed `shogo.config.json` — bail. The runtime will surface
    // the syntax error through the regular regenerate path.
    return null
  }

  const entry = parsed.outputs?.find(
    (o) => Array.isArray(o.generate) && o.generate.includes('server'),
  )
  if (!entry) return null

  const customRoutesPath = entry.serverConfig?.customRoutesPath
  if (!customRoutesPath) return null

  const apiBasePath = entry.serverConfig?.apiBasePath ?? '/api'
  const ext = entry.fileExtension ?? 'tsx'
  const outDir = entry.dir ? join(cwd, entry.dir) : cwd
  const serverTsxPath = join(outDir, `server.${ext}`)

  return { serverTsxPath, customRoutesPath, apiBasePath }
}

/**
 * Detect whether `server.tsx` is out of sync with `shogo.config.json`'s
 * `customRoutesPath` setting.
 *
 * Returns `{ drifted: false }` (silently) for any state where there's
 * nothing to fix:
 *   - No `shogo.config.json` (pre-bootstrap workspace).
 *   - No `'server'` output entry, or no `customRoutesPath` configured.
 *   - `server.tsx` doesn't exist (the missing-file branch in
 *     `startApiServer` already runs `shogo generate`).
 *   - No `custom-routes.{ts,tsx}` on disk (nothing to mount).
 *
 * Returns `{ drifted: true, ... }` when `server.tsx` is present but
 * lacks either the import of `customRoutes` or the mount line. The
 * `looksAutoGenerated` flag drives the heal mode.
 */
export function checkServerTsxDrift(cwd: string): DriftResult {
  const resolved = resolveServerOutput(cwd)
  if (!resolved) return { drifted: false }

  const { serverTsxPath, customRoutesPath, apiBasePath } = resolved

  if (!existsSync(serverTsxPath)) {
    // Let the missing-file path in `startApiServer` handle it.
    return { drifted: false }
  }

  const customRoutesTs = join(cwd, 'custom-routes.ts')
  const customRoutesTsx = join(cwd, 'custom-routes.tsx')
  if (!existsSync(customRoutesTs) && !existsSync(customRoutesTsx)) {
    // No file to mount — the import would 404 anyway. Skip.
    return { drifted: false }
  }

  let source: string
  try {
    source = readFileSync(serverTsxPath, 'utf-8')
  } catch {
    return { drifted: false }
  }

  // Quote-style-agnostic checks. `import customRoutes from '<path>'`
  // is what `generateServer()` emits, but a hand-edit might use a
  // different alias — what we really care about is the `from '<path>'`
  // (so the file imports from the right module) AND that *some*
  // identifier ends up on the right-hand side of an `app.route` call
  // mounting it. We require both because either alone is meaningless.
  const importsCustomRoutesPath =
    source.includes(`from '${customRoutesPath}'`) ||
    source.includes(`from "${customRoutesPath}"`)
  const mountsCustomRoutes =
    new RegExp(
      `app\\.route\\(\\s*['"]${escapeRegExp(apiBasePath)}['"]\\s*,\\s*customRoutes\\s*\\)`,
    ).test(source)

  if (importsCustomRoutesPath && mountsCustomRoutes) {
    return { drifted: false }
  }

  const looksAutoGenerated = source.includes(SDK_AUTOGEN_MARKER)

  const missing: string[] = []
  if (!importsCustomRoutesPath) missing.push(`import from '${customRoutesPath}'`)
  if (!mountsCustomRoutes) missing.push(`app.route('${apiBasePath}', customRoutes)`)

  return {
    drifted: true,
    reason: `server.tsx is missing: ${missing.join(' and ')}`,
    customRoutesPath,
    apiBasePath,
    serverTsxPath,
    looksAutoGenerated,
  }
}

/**
 * Hybrid heal:
 *   - SDK-generated files (have the auto-gen header) → signal
 *     `{ mode: 'regenerate' }`. The caller runs `runShogoGenerate()`
 *     (boot) or `sync()` (gateway-tools); `writeServerEntry()` will
 *     overwrite the file. Safe because it was machine-written.
 *   - Hand-edited files → patch in place. Insert
 *     `import customRoutes from '<customRoutesPath>'` after the last
 *     top-level `import ... from ...` line, and
 *     `app.route('<apiBasePath>', customRoutes)` at the first usable
 *     anchor (before the static catch-all, after another `app.route`,
 *     or before `export default` / `Bun.serve`). Every other byte of
 *     the file is preserved.
 *
 * Idempotent: if both lines are already present (caller raced, or
 * `drift` was stale) returns `{ mode: 'noop' }`. Failures return
 * `{ mode: 'failed', reason }` so the caller can surface a clear
 * error instead of silently spawning the unhealed file.
 */
export function healServerTsxDrift(cwd: string, drift: DriftResult): HealResult {
  if (!drift.drifted) {
    return { mode: 'noop', reason: 'no drift detected' }
  }
  const { serverTsxPath, customRoutesPath, apiBasePath } = drift
  if (!serverTsxPath || !customRoutesPath || !apiBasePath) {
    return { mode: 'failed', reason: 'incomplete drift result' }
  }

  if (drift.looksAutoGenerated) {
    return { mode: 'regenerate', serverTsxPath }
  }

  let source: string
  try {
    source = readFileSync(serverTsxPath, 'utf-8')
  } catch (err: any) {
    return { mode: 'failed', reason: `read failed: ${err?.message ?? err}`, serverTsxPath }
  }

  const importsCustomRoutesPath =
    source.includes(`from '${customRoutesPath}'`) ||
    source.includes(`from "${customRoutesPath}"`)
  const mountsCustomRoutes =
    new RegExp(
      `app\\.route\\(\\s*['"]${escapeRegExp(apiBasePath)}['"]\\s*,\\s*customRoutes\\s*\\)`,
    ).test(source)
  if (importsCustomRoutesPath && mountsCustomRoutes) {
    return { mode: 'noop', serverTsxPath }
  }

  const quote = pickQuoteStyle(source)
  const importLine = `import customRoutes from ${quote}${customRoutesPath}${quote}`
  const mountLine = `app.route(${quote}${apiBasePath}${quote}, customRoutes)`

  let patched = source

  if (!importsCustomRoutesPath) {
    patched = insertImport(patched, importLine)
    if (patched === source) {
      return {
        mode: 'failed',
        reason: 'could not locate a place to insert the customRoutes import',
        serverTsxPath,
      }
    }
  }

  if (!mountsCustomRoutes) {
    const before = patched
    patched = insertMount(patched, mountLine, apiBasePath)
    if (patched === before) {
      return {
        mode: 'failed',
        reason: 'could not locate a place to insert the app.route mount',
        serverTsxPath,
      }
    }
  }

  try {
    writeFileSync(serverTsxPath, patched, 'utf-8')
  } catch (err: any) {
    return { mode: 'failed', reason: `write failed: ${err?.message ?? err}`, serverTsxPath }
  }

  console.warn(
    `[${LOG_PREFIX}] Patched ${serverTsxPath} in place: inserted ${importLine}; ${mountLine}.`,
  )
  return { mode: 'patched', serverTsxPath }
}

/**
 * Pick the quote style for new lines we insert. We try the `import
 * { Hono } from ...` line first — that's near-universally present in
 * every Hono entry file — and fall back to whichever quote appears
 * more often across the file's existing `from` clauses. Defaults to
 * single quotes (matching the SDK template and the codebase's
 * dominant style).
 */
function pickQuoteStyle(source: string): "'" | '"' {
  const honoSingle = /import\s*\{\s*Hono\s*\}\s*from\s*'/m.test(source)
  if (honoSingle) return "'"
  const honoDouble = /import\s*\{\s*Hono\s*\}\s*from\s*"/m.test(source)
  if (honoDouble) return '"'

  const single = (source.match(/from\s*'/g) ?? []).length
  const dbl = (source.match(/from\s*"/g) ?? []).length
  return dbl > single ? '"' : "'"
}

/**
 * Insert `importLine` after the last top-level `^import .*from .+$`
 * line in `source`. Returns the original string unchanged when no
 * `import` line is found (caller treats that as a heal failure).
 */
function insertImport(source: string, importLine: string): string {
  const lines = source.split('\n')
  let lastImportIdx = -1
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    // Match top-level static imports only. Ignore lines that start
    // with whitespace (those are inside something), and skip dynamic
    // `import(...)` calls.
    if (/^import\b.*\bfrom\b.+['"]\s*;?\s*$/.test(line)) {
      lastImportIdx = i
    }
  }
  if (lastImportIdx === -1) return source

  lines.splice(lastImportIdx + 1, 0, importLine)
  return lines.join('\n')
}

/**
 * Insert `mountLine` at the first valid anchor:
 *   1. Immediately before the static catch-all
 *      (`app.use('/*', serveStatic` or `app.get('*', serveStatic`).
 *   2. Else, immediately after the last existing
 *      `app.route('<apiBasePath>', ...)` line.
 *   3. Else, before the final `export default` or `Bun.serve(` line.
 *
 * Returns the original string unchanged if none of those anchors
 * exist.
 */
function insertMount(source: string, mountLine: string, apiBasePath: string): string {
  const lines = source.split('\n')

  const apiBaseEsc = escapeRegExp(apiBasePath)
  const staticCatchAllRe = /^\s*app\.(use|get)\(\s*['"](?:\/\*|\*)['"]\s*,\s*serveStatic/
  const appRouteApiRe = new RegExp(
    `^\\s*app\\.route\\(\\s*['"]${apiBaseEsc}['"]\\s*,`,
  )
  const exportDefaultRe = /^\s*export\s+default\b/
  const bunServeRe = /^\s*Bun\.serve\s*\(/

  // Anchor 1: static catch-all
  for (let i = 0; i < lines.length; i++) {
    if (staticCatchAllRe.test(lines[i])) {
      lines.splice(i, 0, mountLine, '')
      return lines.join('\n')
    }
  }

  // Anchor 2: after the last `app.route('<apiBasePath>', ...)`
  let lastApiRouteIdx = -1
  for (let i = 0; i < lines.length; i++) {
    if (appRouteApiRe.test(lines[i])) lastApiRouteIdx = i
  }
  if (lastApiRouteIdx !== -1) {
    lines.splice(lastApiRouteIdx + 1, 0, mountLine)
    return lines.join('\n')
  }

  // Anchor 3: before the final `export default` / `Bun.serve(`
  let exitIdx = -1
  for (let i = 0; i < lines.length; i++) {
    if (exportDefaultRe.test(lines[i]) || bunServeRe.test(lines[i])) {
      exitIdx = i
      break
    }
  }
  if (exitIdx !== -1) {
    lines.splice(exitIdx, 0, mountLine, '')
    return lines.join('\n')
  }

  return source
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
