-- Migration: add_github_token_auth
-- Generated: 2026-10-04T08:25:53.811Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_github_token_auth`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_github_connections" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "repoOwner" TEXT NOT NULL,
    "repoName" TEXT NOT NULL,
    "repoFullName" TEXT NOT NULL,
    "defaultBranch" TEXT NOT NULL DEFAULT 'main',
    "installationId" INTEGER,
    "repoId" INTEGER,
    "isPrivate" BOOLEAN NOT NULL DEFAULT true,
    "syncEnabled" BOOLEAN NOT NULL DEFAULT true,
    "lastPushAt" DATETIME,
    "lastPullAt" DATETIME,
    "lastSyncError" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "authType" TEXT NOT NULL DEFAULT 'app',
    "encryptedToken" TEXT,
    "tokenLogin" TEXT,
    CONSTRAINT "github_connections_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_github_connections" ("createdAt", "defaultBranch", "id", "installationId", "isPrivate", "lastPullAt", "lastPushAt", "lastSyncError", "projectId", "repoFullName", "repoId", "repoName", "repoOwner", "syncEnabled", "updatedAt") SELECT "createdAt", "defaultBranch", "id", "installationId", "isPrivate", "lastPullAt", "lastPushAt", "lastSyncError", "projectId", "repoFullName", "repoId", "repoName", "repoOwner", "syncEnabled", "updatedAt" FROM "github_connections";
DROP TABLE "github_connections";
ALTER TABLE "new_github_connections" RENAME TO "github_connections";
CREATE UNIQUE INDEX "github_connections_projectId_key" ON "github_connections"("projectId");
CREATE INDEX "github_connections_installationId_idx" ON "github_connections"("installationId");
CREATE INDEX "github_connections_repoFullName_idx" ON "github_connections"("repoFullName");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

