-- Migration: add_channels_daily_driver
-- Generated: 2026-09-30T13:13:56.432Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_channels_daily_driver`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "conversation_attachments" ADD COLUMN "extractedText" TEXT;

-- CreateTable
CREATE TABLE "chat_user_settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "statusEmoji" TEXT,
    "statusText" TEXT,
    "statusExpiresAt" DATETIME,
    "dndUntil" DATETIME,
    "quietHours" TEXT,
    "timezone" TEXT,
    "notifyDefault" TEXT NOT NULL DEFAULT 'mentions',
    "keywords" TEXT,
    "emailDigest" TEXT NOT NULL DEFAULT 'off',
    "lastDigestAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "conversation_pins" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conversationId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "pinnedById" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "conversation_pins_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "conversation_pins_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "conversation_messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "saved_messages" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "saved_messages_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "conversation_messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "conversation_drafts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "threadRootId" TEXT NOT NULL DEFAULT '',
    "text" TEXT NOT NULL,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "conversation_drafts_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "scheduled_messages" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "threadRootId" TEXT,
    "alsoSentToChannel" BOOLEAN NOT NULL DEFAULT false,
    "text" TEXT NOT NULL,
    "sendAt" DATETIME NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "sentMessageId" TEXT,
    "error" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "scheduled_messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "chat_reminders" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "remindAt" DATETIME NOT NULL,
    "messageId" TEXT,
    "conversationId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "firedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "chat_inbox_items" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "conversationId" TEXT,
    "messageId" TEXT,
    "actorUserId" TEXT,
    "title" TEXT NOT NULL,
    "preview" TEXT NOT NULL,
    "readAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "custom_emoji" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "user_groups" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "handle" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "user_group_members" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "groupId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_group_members_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "user_groups" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "conversation_message_embeddings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "messageId" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "embedding" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "conversation_message_embeddings_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "conversation_messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_conversation_members" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conversationId" TEXT NOT NULL,
    "memberType" TEXT NOT NULL DEFAULT 'user',
    "userId" TEXT,
    "projectId" TEXT,
    "projectAgentId" TEXT,
    "role" TEXT NOT NULL DEFAULT 'member',
    "lastReadSeq" INTEGER NOT NULL DEFAULT 0,
    "lastReadAt" DATETIME,
    "notifyLevel" TEXT NOT NULL DEFAULT 'default',
    "muted" BOOLEAN NOT NULL DEFAULT false,
    "starred" BOOLEAN NOT NULL DEFAULT false,
    "agentTrigger" TEXT NOT NULL DEFAULT 'mention',
    "agentKeywords" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "conversation_members_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "conversation_members_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_conversation_members" ("agentKeywords", "agentTrigger", "conversationId", "createdAt", "id", "lastReadAt", "lastReadSeq", "memberType", "muted", "notifyLevel", "projectAgentId", "projectId", "role", "starred", "updatedAt", "userId") SELECT "agentKeywords", "agentTrigger", "conversationId", "createdAt", "id", "lastReadAt", "lastReadSeq", "memberType", "muted", "notifyLevel", "projectAgentId", "projectId", "role", "starred", "updatedAt", "userId" FROM "conversation_members";
DROP TABLE "conversation_members";
ALTER TABLE "new_conversation_members" RENAME TO "conversation_members";
CREATE INDEX "conversation_members_userId_idx" ON "conversation_members"("userId");
CREATE INDEX "conversation_members_conversationId_memberType_idx" ON "conversation_members"("conversationId", "memberType");
CREATE UNIQUE INDEX "conversation_members_conversationId_userId_key" ON "conversation_members"("conversationId", "userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "chat_user_settings_emailDigest_idx" ON "chat_user_settings"("emailDigest");

-- CreateIndex
CREATE UNIQUE INDEX "chat_user_settings_workspaceId_userId_key" ON "chat_user_settings"("workspaceId", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "conversation_pins_messageId_key" ON "conversation_pins"("messageId");

-- CreateIndex
CREATE INDEX "conversation_pins_conversationId_createdAt_idx" ON "conversation_pins"("conversationId", "createdAt");

-- CreateIndex
CREATE INDEX "saved_messages_userId_createdAt_idx" ON "saved_messages"("userId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "saved_messages_userId_messageId_key" ON "saved_messages"("userId", "messageId");

-- CreateIndex
CREATE INDEX "conversation_drafts_userId_updatedAt_idx" ON "conversation_drafts"("userId", "updatedAt");

-- CreateIndex
CREATE UNIQUE INDEX "conversation_drafts_userId_conversationId_threadRootId_key" ON "conversation_drafts"("userId", "conversationId", "threadRootId");

-- CreateIndex
CREATE INDEX "scheduled_messages_status_sendAt_idx" ON "scheduled_messages"("status", "sendAt");

-- CreateIndex
CREATE INDEX "scheduled_messages_userId_status_idx" ON "scheduled_messages"("userId", "status");

-- CreateIndex
CREATE INDEX "chat_reminders_status_remindAt_idx" ON "chat_reminders"("status", "remindAt");

-- CreateIndex
CREATE INDEX "chat_reminders_userId_status_idx" ON "chat_reminders"("userId", "status");

-- CreateIndex
CREATE INDEX "chat_inbox_items_userId_workspaceId_createdAt_idx" ON "chat_inbox_items"("userId", "workspaceId", "createdAt");

-- CreateIndex
CREATE INDEX "chat_inbox_items_userId_readAt_idx" ON "chat_inbox_items"("userId", "readAt");

-- CreateIndex
CREATE INDEX "chat_inbox_items_messageId_idx" ON "chat_inbox_items"("messageId");

-- CreateIndex
CREATE UNIQUE INDEX "custom_emoji_workspaceId_name_key" ON "custom_emoji"("workspaceId", "name");

-- CreateIndex
CREATE UNIQUE INDEX "user_groups_workspaceId_handle_key" ON "user_groups"("workspaceId", "handle");

-- CreateIndex
CREATE INDEX "user_group_members_userId_idx" ON "user_group_members"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "user_group_members_groupId_userId_key" ON "user_group_members"("groupId", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "conversation_message_embeddings_messageId_key" ON "conversation_message_embeddings"("messageId");

-- CreateIndex
CREATE INDEX "conversation_message_embeddings_workspaceId_createdAt_idx" ON "conversation_message_embeddings"("workspaceId", "createdAt");
