-- Migration: add_license_keys
-- Source:    prisma/schema.local.prisma
--
-- Generated by `bun run db:migrate:desktop --name add_license_keys`
-- (i.e. `prisma migrate diff --from-migrations apps/desktop/prisma/migrations
--  --to-schema prisma/schema.local.prisma --script`) and TRIMMED by hand
-- to only contain the license_keys change. The raw diff also emitted
-- RedefineTables blocks for ~10 pre-existing ACCEPTED_DRIFT tables
-- (`agent_configs`, `agent_eval_sets`, `budget_alerts`, `eval_runs`,
-- `model_experiments`, `projects`, `signup_attributions`,
-- `subagent_model_overrides`, `usage_wallets`, `workspace_grants`) which
-- are documented in scripts/check-desktop-schema-drift.ts as pre-existing
-- tech debt and intentionally left alone here — see the precedent in
-- apps/desktop/prisma/migrations/20260521192222_add_region_to_analytics_digest/.
--
-- This is the SQLite mirror of
-- prisma/migrations/20260523000000_add_license_keys/migration.sql.

-- CreateTable
CREATE TABLE "license_keys" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "codeHash" TEXT NOT NULL,
    "codePrefix" TEXT NOT NULL,
    "batchId" TEXT,
    "planId" TEXT NOT NULL,
    "monthlyIncludedUsd" REAL NOT NULL DEFAULT 0,
    "freeSeats" INTEGER NOT NULL DEFAULT 0,
    "durationDays" INTEGER,
    "expiresAt" DATETIME,
    "redeemedAt" DATETIME,
    "redeemedByWorkspaceId" TEXT,
    "redeemedByUserId" TEXT,
    "redeemedGrantId" TEXT,
    "note" TEXT,
    "createdByUserId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "license_keys_redeemedGrantId_fkey" FOREIGN KEY ("redeemedGrantId") REFERENCES "workspace_grants" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "license_keys_codeHash_key" ON "license_keys"("codeHash");

-- CreateIndex
CREATE UNIQUE INDEX "license_keys_redeemedByWorkspaceId_key" ON "license_keys"("redeemedByWorkspaceId");

-- CreateIndex
CREATE UNIQUE INDEX "license_keys_redeemedGrantId_key" ON "license_keys"("redeemedGrantId");

-- CreateIndex
CREATE INDEX "license_keys_batchId_idx" ON "license_keys"("batchId");

-- CreateIndex
CREATE INDEX "license_keys_redeemedAt_idx" ON "license_keys"("redeemedAt");
