-- Migration: add_affiliate_content_cpm_per_creator
-- Generated: 2026-06-08T21:17:29.466Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_affiliate_content_cpm_per_creator`.
-- Hand-trimmed to the single additive change for this PR: a per-creator
-- content-CPM override column on `affiliates`. The generator also emitted
-- RedefineTables / RedefineIndex churn for unrelated tables that are already
-- in the desktop schema's ACCEPTED_DRIFT set (agent_configs, eval_runs,
-- signup_attributions, etc.); those are intentionally omitted so this
-- migration replays cleanly. See the original content-CPM migration for the
-- same trimming rationale.

-- AlterTable
ALTER TABLE "affiliates" ADD COLUMN "contentCpmCents" INTEGER;
