-- Migration: add_message_agent_chain
-- Generated: 2026-09-30T18:22:12.156Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_message_agent_chain`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "conversation_messages" ADD COLUMN "agentChain" TEXT;
