// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Extract Custom Routes Migration
 *
 * One-shot migration that runs on workspace boot AFTER
 * {@link migrateSkillServerToRoot}. It restores the pre-merge two-file
 * design where:
 *   - `server.tsx` is auto-generated by the SDK from `shogo.config.json`
 *     (single source of truth for CORS, route mounting, static serving).
 *   - `custom-routes.ts` is the editable surface for non-CRUD routes
 *     (proxies, aggregation, webhooks, etc.).
 *
 * Workspaces from the merge era have a static `server.tsx` (either the
 * old runtime template, or one extended by the previous skill-server
 * migration with a `// MIGRATED-CUSTOM-ROUTES` block). We need to:
 *   1. Pull any custom code (the migrated block, or any non-template
 *      routes/imports) into `custom-routes.ts`.
 *   2. Delete the static `server.tsx` so the next `shogo generate` cycle
 *      re-emits it from the SDK template (now driven by
 *      `shogo.config.json`).
 *
 * Idempotent: silently no-ops when there's nothing to extract — i.e.
 *   - no `server.tsx` (already SDK-managed in a fresh workspace), or
 *   - `shogo.config.json` exists AND a populated `custom-routes.ts`
 *     already exists (we've extracted before).
 *
 * On any failure the workspace is left untouched (we never delete
 * `server.tsx` until the extraction has succeeded), and the error is
 * surfaced to the caller for logging.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

const LOG_PREFIX = 'extract-custom-routes'

/** Marker comment used by `migrateSkillServerToRoot` to fence migrated routes. */
const CUSTOM_ROUTES_MARKER = '// MIGRATED-CUSTOM-ROUTES'

export interface ExtractCustomRoutesResult {
  /** True only when an extraction was actually performed. */
  migrated: boolean
  /** True when migrated content was found via the // MIGRATED-CUSTOM-ROUTES marker. */
  hadMarker?: boolean
  /** Path of the resulting `custom-routes.ts` (when migrated). */
  customRoutesPath?: string
  /** Path of the deleted `server.tsx` (when migrated). */
  deletedServerPath?: string
  /** Path of the snapshot of the original `server.tsx`. */
  snapshotPath?: string
  /** Notes file written next to the snapshot. */
  notesPath?: string
  /** True when extracted content references skill-server-style imports
   *  (e.g. `from '../db'`) and was inlined commented out for review. */
  needsReview?: boolean
  /** ISO timestamp when the migration ran. */
  at?: string
  /** Error message if the migration failed. The workspace is unchanged. */
  error?: string
}

/**
 * The default scaffold the runtime template ships in `custom-routes.ts`.
 * Mirrors `templates/runtime-template/custom-routes.ts` so we can detect
 * "user hasn't touched this file" idempotently.
 *
 * Kept as a single source-of-truth string rather than imported from the
 * template directory because this migration runs in production pods
 * where the template path is `/opt/shogo/...` and we don't want a
 * runtime FS dependency for an idempotency check.
 */
const DEFAULT_CUSTOM_ROUTES_SCAFFOLD = `// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under \`/api/<model>s\`). Anything you mount on the exported
 * Hono app shows up at \`/api/...\` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: \`app.get('/dashboard', ...)\`
 *   - External proxies (LLM, payments, weather): \`app.post('/llm', ...)\`
 *   - Webhooks: \`app.post('/webhooks/stripe', ...)\`
 *   - Auth flows: \`app.post('/auth/login', ...)\`
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * \`server.tsx\` (no schema regeneration, no \`prisma db push\`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from \`./src/lib/db\`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit \`server.tsx\` — it is auto-generated by the SDK from
 * \`shogo.config.json\` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'

const app = new Hono()

// Add your custom routes here. They mount under \`/api/\`.
// Example:
//   app.get('/hello', (c) => c.json({ message: 'Hello!' }))

export default app
`

/**
 * Detect whether a `server.tsx` matches one of the known stock templates
 * (post-merge runtime template, or the SDK's `generateServer()` output)
 * closely enough that no real custom code lives in it. Used to short-
 * circuit extraction when the file is just template — we still delete it
 * to let the SDK re-emit a fresh one.
 *
 * "Stock" here means: the file imports `createAllRoutes` from
 * `./src/generated/routes` or `./src/generated`, has no // MIGRATED-CUSTOM-
 * ROUTES marker, and no app.<verb>(...) calls beyond the standard
 * `/health` endpoint and route mounts.
 */
function isStockServerTsx(source: string): boolean {
  if (source.includes(CUSTOM_ROUTES_MARKER)) return false
  if (!/createAllRoutes/.test(source)) return false

  // Look for verb registrations besides the canonical /health and /*
  // static handlers. Anything else is likely user-authored.
  const verbCalls = [...source.matchAll(/\bapp\.(get|post|put|patch|delete|all|use|route)\s*\(\s*['"]([^'"]+)['"]/g)]
  for (const m of verbCalls) {
    const verb = m[1]
    const path = m[2]
    if (path === '/health') continue
    if (path === '/*' || path === '*') continue
    if (verb === 'route' && path === '/api') continue
    if (verb === 'use' && path === '*') continue
    // Anything left is user-added.
    return false
  }
  return true
}

/**
 * Extract a `// MIGRATED-CUSTOM-ROUTES` block (the format
 * {@link injectCustomRoutes} produces) into a standalone
 * `custom-routes.ts` body. Returns `null` when no marker is present.
 *
 * The block format we emit looks like:
 *   // MIGRATED-CUSTOM-ROUTES — from .shogo/server/custom-routes.ts on YYYY-MM-DD
 *   // ...preamble...
 *   const customRoutesApp = new Hono()
 *   customRoutesApp.get(...)
 *   ...
 *   app.route('/api', customRoutesApp)
 *
 * To turn it back into a free-standing file we:
 *   - rename `customRoutesApp` → `app`
 *   - drop the trailing `app.route('/api', customRoutesApp)` mount
 *   - prepend `import { Hono } from 'hono'` and append `export default app`
 */
function extractMigratedBlock(serverTsx: string, when: Date): {
  body: string
  needsReview: boolean
} | null {
  const idx = serverTsx.indexOf(CUSTOM_ROUTES_MARKER)
  if (idx === -1) return null

  const block = serverTsx.slice(idx).trim()

  // The block's commented-out variant (when imports were unsafe) has a
  // `/* ... */` body — keep it intact and surface needsReview so the
  // agent knows manual work is needed.
  const isCommented = /\/\*[\s\S]*\*\//.test(block) && !/\bcustomRoutesApp\b/.test(block)

  if (isCommented) {
    const body = [
      '// SPDX-License-Identifier: Apache-2.0',
      '// Copyright (C) 2026 Shogo Technologies, Inc.',
      '/**',
      ' * Custom API Routes (extracted from server.tsx — needs manual review).',
      ' *',
      ` * Extracted on ${when.toISOString().slice(0, 10)} by extract-custom-routes`,
      ' * migration. The original block is preserved verbatim below; port',
      " * imports to root paths (e.g. `import { prisma } from './src/lib/db'`)",
      ' * and uncomment.',
      ' */',
      '',
      "import { Hono } from 'hono'",
      '',
      'const app = new Hono()',
      '',
      block,
      '',
      'export default app',
      '',
    ].join('\n')
    return { body, needsReview: true }
  }

  // Strip the mount line so it isn't part of the extracted file.
  const withoutMount = block
    .replace(/\n\s*app\.route\(\s*['"]\/api['"]\s*,\s*customRoutesApp\s*\)\s*;?\s*$/m, '')
    .replace(/customRoutesApp/g, 'app')

  const body = [
    '// SPDX-License-Identifier: Apache-2.0',
    '// Copyright (C) 2026 Shogo Technologies, Inc.',
    '/**',
    ' * Custom API Routes',
    ' *',
    ` * Extracted from server.tsx on ${when.toISOString().slice(0, 10)} by`,
    ' * extract-custom-routes migration.',
    ' */',
    '',
    "import { Hono } from 'hono'",
    '',
    withoutMount.trim(),
    '',
    'export default app',
    '',
  ].join('\n')
  return { body, needsReview: false }
}

/**
 * Run the migration. Idempotent: silently no-ops when there's nothing
 * to extract.
 */
export function extractCustomRoutes(workspaceDir: string): ExtractCustomRoutesResult {
  const serverPath = join(workspaceDir, 'server.tsx')
  if (!existsSync(serverPath)) {
    // Nothing to do — workspace is already SDK-managed.
    return { migrated: false }
  }

  const customRoutesPath = join(workspaceDir, 'custom-routes.ts')
  const customRoutesTsxPath = join(workspaceDir, 'custom-routes.tsx')
  const customRoutesExists = existsSync(customRoutesPath) || existsSync(customRoutesTsxPath)

  // Already migrated: a populated custom-routes file is already in place.
  // We still need to delete server.tsx if the SDK should own it now.
  // But to be safe we leave it alone — the SDK's `skipIfExists: true`
  // means it won't be re-emitted anyway, and the agent may have edited
  // it intentionally on a workspace that doesn't use the new layout.
  // Detect this by checking for shogo.config.json (the marker that the
  // workspace is on the new template).
  const shogoConfigPath = join(workspaceDir, 'shogo.config.json')
  if (!existsSync(shogoConfigPath)) {
    // Pre-shogo.config.json workspace; leave its hand-crafted server.tsx
    // alone. The next `shogo generate` will emit `shogo.config.json` and
    // the migration will run on the following boot.
    return { migrated: false }
  }

  const now = new Date()
  const stamp = now.toISOString().replace(/[:.]/g, '-')
  const snapshotDir = join(workspaceDir, '.shogo', `server-tsx-extracted-${stamp}`)
  const result: ExtractCustomRoutesResult = {
    migrated: false,
    at: now.toISOString(),
  }

  try {
    const serverSrc = readFileSync(serverPath, 'utf-8')

    if (customRoutesExists && isStockServerTsx(serverSrc)) {
      // We've already done the extraction in a prior run; just clean up
      // the leftover stock server.tsx so the SDK can re-emit it.
      mkdirSync(snapshotDir, { recursive: true })
      writeFileSync(join(snapshotDir, 'server.tsx'), serverSrc, 'utf-8')
      writeFileSync(
        join(snapshotDir, 'MIGRATION_NOTES.md'),
        buildNotes({ stockOnly: true, hadMarker: false, needsReview: false, at: result.at! }),
        'utf-8',
      )
      // Atomically replace via unlink — Bun's fs has rmSync but to keep
      // dependencies minimal we use writeFileSync + unlinkSync.
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { unlinkSync } = require('fs') as typeof import('fs')
      unlinkSync(serverPath)
      result.migrated = true
      result.deletedServerPath = serverPath
      result.snapshotPath = snapshotDir
      result.notesPath = join(snapshotDir, 'MIGRATION_NOTES.md')
      result.hadMarker = false
      console.log(`[${LOG_PREFIX}] Removed stock server.tsx (custom-routes.ts already in place)`)
      return result
    }

    // Look for explicitly-marked migrated content from
    // `migrateSkillServerToRoot`. If absent and the file is non-stock,
    // treat the whole user-added body as custom code (excluding the
    // auto-generated boilerplate).
    const extracted = extractMigratedBlock(serverSrc, now)

    let customRoutesBody: string
    let hadMarker = false
    let needsReview = false

    if (extracted) {
      hadMarker = true
      customRoutesBody = extracted.body
      needsReview = extracted.needsReview
    } else if (isStockServerTsx(serverSrc)) {
      // Stock server.tsx with no marker — write the default scaffold
      // unless the user already created one.
      customRoutesBody = customRoutesExists
        ? readFileSync(existsSync(customRoutesPath) ? customRoutesPath : customRoutesTsxPath, 'utf-8')
        : DEFAULT_CUSTOM_ROUTES_SCAFFOLD
    } else {
      // Hand-edited server.tsx with no marker. We can't reliably tell
      // user code from template code, so commented out the entire file
      // so the agent can manually port the bits they want into
      // custom-routes.ts.
      hadMarker = false
      needsReview = true
      customRoutesBody = [
        '// SPDX-License-Identifier: Apache-2.0',
        '// Copyright (C) 2026 Shogo Technologies, Inc.',
        '/**',
        ' * Custom API Routes (extracted from a hand-edited server.tsx —',
        ' * needs manual review).',
        ' *',
        ` * Extracted on ${now.toISOString().slice(0, 10)} by`,
        ' * extract-custom-routes migration. The original `server.tsx`',
        ' * was preserved at:',
        ` *   ${snapshotDir}/server.tsx`,
        ' *',
        ' * Port any custom routes you authored from that file into the',
        ' * Hono app exported below — they will mount under /api/.',
        ' */',
        '',
        "import { Hono } from 'hono'",
        '',
        'const app = new Hono()',
        '',
        '// TODO(extract-custom-routes): port routes from snapshot server.tsx',
        '',
        'export default app',
        '',
      ].join('\n')
    }

    // Write everything atomically: snapshot first, custom-routes.ts
    // second (only if it doesn't already exist with non-default content),
    // then delete server.tsx. If any step throws we exit the catch with
    // the original workspace intact.
    mkdirSync(snapshotDir, { recursive: true })
    writeFileSync(join(snapshotDir, 'server.tsx'), serverSrc, 'utf-8')

    if (!customRoutesExists) {
      writeFileSync(customRoutesPath, customRoutesBody, 'utf-8')
    } else {
      // The user already has a custom-routes file. Append the extracted
      // content as a comment block so we don't lose anything.
      const existing = readFileSync(
        existsSync(customRoutesPath) ? customRoutesPath : customRoutesTsxPath,
        'utf-8',
      )
      const target = existsSync(customRoutesPath) ? customRoutesPath : customRoutesTsxPath
      const merged = existing.trimEnd() + '\n\n/* ' +
        `Extracted from server.tsx on ${now.toISOString().slice(0, 10)}\n` +
        '   Review and merge by hand. The original server.tsx is at:\n' +
        `   ${snapshotDir}/server.tsx\n` +
        customRoutesBody +
        '\n*/\n'
      writeFileSync(target, merged, 'utf-8')
      needsReview = true
    }

    writeFileSync(
      join(snapshotDir, 'MIGRATION_NOTES.md'),
      buildNotes({ stockOnly: false, hadMarker, needsReview, at: result.at! }),
      'utf-8',
    )

    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { unlinkSync } = require('fs') as typeof import('fs')
    unlinkSync(serverPath)

    result.migrated = true
    result.hadMarker = hadMarker
    result.needsReview = needsReview
    result.customRoutesPath = customRoutesPath
    result.deletedServerPath = serverPath
    result.snapshotPath = snapshotDir
    result.notesPath = join(snapshotDir, 'MIGRATION_NOTES.md')
    console.log(
      `[${LOG_PREFIX}] Extracted custom routes from server.tsx → custom-routes.ts ` +
        `(snapshot at ${snapshotDir}${needsReview ? ', needs review' : ''})`,
    )
    return result
  } catch (err: any) {
    const message = err instanceof Error ? err.message : String(err)
    console.error(`[${LOG_PREFIX}] Migration failed: ${message}`)
    return { ...result, error: message }
  }
}

interface NotesInput {
  stockOnly: boolean
  hadMarker: boolean
  needsReview: boolean
  at: string
}

function buildNotes(input: NotesInput): string {
  const lines: string[] = [
    '# extract-custom-routes Migration',
    '',
    `Ran at ${input.at}`,
    '',
  ]
  if (input.stockOnly) {
    lines.push(
      'The workspace already had a populated `custom-routes.ts`, and the',
      '`server.tsx` snapshotted here was just the stock template. We',
      'removed it so the SDK can re-emit a fresh one (driven by',
      '`shogo.config.json`).',
    )
  } else if (input.hadMarker) {
    lines.push(
      'A `// MIGRATED-CUSTOM-ROUTES` block was extracted from `server.tsx`',
      'into `custom-routes.ts`. The block came from the earlier',
      '`migrate-skill-server-to-root` migration and contains routes the',
      'agent ported from `.shogo/server/custom-routes.ts`.',
    )
  } else {
    lines.push(
      '`server.tsx` had hand edits with no `// MIGRATED-CUSTOM-ROUTES`',
      'fence, so we could not safely auto-extract them. The original',
      'file is preserved here in full — port any custom routes by hand',
      'into `custom-routes.ts`.',
    )
  }

  if (input.needsReview) {
    lines.push(
      '',
      '⚠️  **Manual review required.** The extracted content references',
      'imports or symbols we could not adapt automatically. Open',
      '`custom-routes.ts` and fix anything inside a `TODO(extract-custom-routes)`',
      'comment.',
    )
  }
  return lines.join('\n') + '\n'
}
