// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Desktop Cloud-Login Bridge Page
 *
 * The Shogo desktop app opens this page in the system browser after the user
 * clicks "Sign in to Shogo Cloud". Once the user is authenticated (via
 * Better Auth — we redirect to /sign-in?next=/auth/local-link if not), we:
 *
 *   1. Fetch the workspaces the signed-in user belongs to. If the user has
 *      more than one workspace and the desktop didn't pre-select one via
 *      the `workspaceId` query param, render a picker and wait for the user
 *      to choose. With a single workspace (or a valid pre-selection) we
 *      skip the picker and proceed straight to mint.
 *   2. Mint a device-tagged API key for the chosen workspace
 *      (POST /api/api-keys/device — cloud dedupes any previous key for this
 *      deviceId within the same workspace).
 *   3. Redirect back to the desktop app via a shogo://auth-callback deep
 *      link that carries the fresh key + original state nonce.
 *   4. Leave a "Return to your Shogo desktop app" fallback screen so the
 *      user has recourse if the deep link doesn't fire.
 *
 * Query params we consume:
 *   state           — opaque nonce generated by local API, echoed back
 *   callback        — usually "shogo://auth-callback" (optional, defaults)
 *   deviceId        — stable UUID for this desktop install
 *   deviceName      — hostname/"My Laptop"
 *   devicePlatform  — darwin / win32 / linux
 *   appVersion      — desktop app version string
 *   workspaceId     — optional pre-selected workspace id (used by the
 *                     desktop "Switch workspace" affordance)
 */

import { useEffect, useMemo, useRef, useState, useCallback } from 'react'
import { View, Text, ActivityIndicator, Platform, Pressable } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Button, cn } from '@shogo/shared-ui/primitives'
import { PlatformApi, type WorkspaceSummary } from '@shogo-ai/sdk'
import { useAuth } from '../../contexts/auth'
import { useDomainHttp } from '../../contexts/domain'

interface LocalLinkParams {
  state?: string
  callback?: string
  deviceId?: string
  deviceName?: string
  devicePlatform?: string
  appVersion?: string
  workspaceId?: string
}

type Status =
  | 'checking-auth'
  | 'redirect-signin'
  | 'loading-workspaces'
  | 'picking-workspace'
  | 'minting'
  | 'ready'
  | 'error'

export default function LocalLinkBridge() {
  const router = useRouter()
  const params = useLocalSearchParams<LocalLinkParams>()
  const { user, isLoading: isAuthLoading, isAuthenticated } = useAuth()
  const http = useDomainHttp()
  const platform = useMemo(() => new PlatformApi(http), [http])

  const [status, setStatus] = useState<Status>('checking-auth')
  const [error, setError] = useState<string | null>(null)
  const [callbackUrl, setCallbackUrl] = useState<string | null>(null)
  const [workspaces, setWorkspaces] = useState<WorkspaceSummary[]>([])
  const [selectedWorkspaceId, setSelectedWorkspaceId] = useState<string | null>(null)
  // Guard so strict-mode double-renders / re-runs don't mint two device keys.
  const mintedRef = useRef(false)
  // Guard so we only fetch the workspace list once per page load.
  const workspacesLoadedRef = useRef(false)

  // Re-use the exact callback scheme from the desktop app. We default to
  // shogo://auth-callback if no override was provided.
  const callback = typeof params.callback === 'string' && params.callback
    ? params.callback
    : 'shogo://auth-callback'
  const state = typeof params.state === 'string' ? params.state : ''
  const preselectedWorkspaceId = typeof params.workspaceId === 'string' ? params.workspaceId : ''

  /** Mint a device key for the chosen workspace and fire the deep link. */
  const completeMint = useCallback(async (workspaceId: string | undefined) => {
    if (mintedRef.current) return
    mintedRef.current = true
    setStatus('minting')
    try {
      const minted = await platform.createDeviceApiKey(
        {
          id: String(params.deviceId),
          name: typeof params.deviceName === 'string' ? params.deviceName : 'Shogo Desktop',
          platform: typeof params.devicePlatform === 'string' ? params.devicePlatform : 'unknown',
          appVersion: typeof params.appVersion === 'string' ? params.appVersion : 'unknown',
        },
        workspaceId ? { workspaceId } : undefined,
      )

      // Assemble the callback URL that carries everything the desktop app
      // needs to finalize sign-in. The state nonce is required; it's
      // validated server-side in /api/local/cloud-login/complete. The
      // cloud endpoint is sourced from the desktop's SHOGO_CLOUD_URL env
      // var, so we deliberately do NOT echo a cloudUrl back here.
      const callbackParams = new URLSearchParams({
        state,
        key: minted.key,
      })
      if (user?.email) callbackParams.set('email', user.email)
      if (minted.workspace?.name) callbackParams.set('workspace', minted.workspace.name)
      const url = `${callback}?${callbackParams.toString()}`

      setCallbackUrl(url)
      setStatus('ready')

      // Auto-trigger the deep link. Most OSes will prompt once before
      // opening; the fallback UI below gives the user a manual button.
      if (typeof window !== 'undefined') {
        window.location.replace(url)
      }
    } catch (err) {
      console.error('[LocalLink] Failed to mint device key:', err)
      mintedRef.current = false
      setStatus('error')
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to create a sign-in key. Please try again.',
      )
    }
  }, [platform, params.deviceId, params.deviceName, params.devicePlatform, params.appVersion, callback, state, user?.email])

  useEffect(() => {
    if (Platform.OS !== 'web') {
      setStatus('error')
      setError('This sign-in bridge is only available on web.')
      return
    }
    if (isAuthLoading) return

    if (!isAuthenticated) {
      setStatus('redirect-signin')
      // Bounce through sign-in and come back to this page once authenticated.
      // We encode the full current URL (including all device params) so
      // nothing is lost on the round-trip.
      const full = typeof window !== 'undefined'
        ? window.location.pathname + window.location.search
        : '/auth/local-link'
      router.replace({ pathname: '/(auth)/sign-in', params: { next: full } } as any)
      return
    }

    if (!state || !params.deviceId) {
      setStatus('error')
      setError('Missing state or device identifier. Please restart the sign-in from Shogo desktop.')
      return
    }

    if (workspacesLoadedRef.current) return
    workspacesLoadedRef.current = true

    setStatus('loading-workspaces')
    ;(async () => {
      try {
        const list = await platform.listMyWorkspaces()
        setWorkspaces(list)

        if (list.length === 0) {
          setStatus('error')
          setError('Your account has no workspaces. Create one in Shogo Cloud first.')
          return
        }

        // Auto-skip the picker when there's only one workspace, or when
        // the desktop app pre-selected a valid workspaceId.
        const preselected = preselectedWorkspaceId
          ? list.find((w) => w.id === preselectedWorkspaceId)
          : null
        if (preselected) {
          await completeMint(preselected.id)
          return
        }
        if (list.length === 1) {
          await completeMint(list[0].id)
          return
        }

        // Multiple workspaces, no valid pre-selection: render the picker.
        // Default-select the first one so the Continue button is enabled.
        setSelectedWorkspaceId(list[0].id)
        setStatus('picking-workspace')
      } catch (err) {
        console.error('[LocalLink] Failed to load workspaces:', err)
        workspacesLoadedRef.current = false
        setStatus('error')
        setError(
          err instanceof Error
            ? err.message
            : 'Failed to load your workspaces. Please try again.',
        )
      }
    })()
  }, [isAuthLoading, isAuthenticated, state, params.deviceId, preselectedWorkspaceId, platform, router, completeMint])

  return (
    <View className="flex-1 bg-background items-center justify-center px-6">
      <View className="max-w-md w-full gap-4 items-center">
        <Text className="text-2xl font-bold text-foreground">Sign in to Shogo Desktop</Text>

        {status === 'checking-auth' && (
          <>
            <ActivityIndicator />
            <Text className="text-sm text-muted-foreground text-center">Checking your session...</Text>
          </>
        )}

        {status === 'redirect-signin' && (
          <Text className="text-sm text-muted-foreground text-center">Redirecting you to sign in...</Text>
        )}

        {status === 'loading-workspaces' && (
          <>
            <ActivityIndicator />
            <Text className="text-sm text-muted-foreground text-center">Loading your workspaces...</Text>
          </>
        )}

        {status === 'picking-workspace' && (
          <View className="gap-3 w-full">
            <Text className="text-sm text-muted-foreground text-center">
              Choose which workspace to link to this device. You can switch later from
              the desktop app's General settings.
            </Text>
            <View className="gap-2 w-full">
              {workspaces.map((ws) => {
                const isSelected = selectedWorkspaceId === ws.id
                return (
                  <Pressable
                    key={ws.id}
                    onPress={() => setSelectedWorkspaceId(ws.id)}
                    className={cn(
                      'flex-row items-center gap-3 px-4 py-3 rounded-lg border',
                      isSelected ? 'border-primary bg-primary/5' : 'border-border',
                    )}
                  >
                    <View
                      className={cn(
                        'w-4 h-4 rounded-full border-2',
                        isSelected ? 'border-primary bg-primary' : 'border-muted-foreground',
                      )}
                    />
                    <View className="flex-1">
                      <Text className="font-medium text-foreground">{ws.name}</Text>
                      <Text className="text-xs text-muted-foreground">{ws.slug}</Text>
                    </View>
                  </Pressable>
                )
              })}
            </View>
            <Button
              onPress={() => {
                if (selectedWorkspaceId) {
                  void completeMint(selectedWorkspaceId)
                }
              }}
              disabled={!selectedWorkspaceId}
              className="w-full"
            >
              Continue
            </Button>
          </View>
        )}

        {status === 'minting' && (
          <>
            <ActivityIndicator />
            <Text className="text-sm text-muted-foreground text-center">
              Linking this browser session to your Shogo Desktop app...
            </Text>
          </>
        )}

        {status === 'ready' && (
          <View className="gap-3 items-center w-full">
            <Text className="text-sm text-foreground text-center">
              Your desktop app should open automatically. If it doesn't, click the button below.
            </Text>
            {callbackUrl && (
              <Button
                onPress={() => {
                  if (typeof window !== 'undefined' && callbackUrl) {
                    window.location.href = callbackUrl
                  }
                }}
                className="w-full"
              >
                Return to Shogo Desktop
              </Button>
            )}
            <Text className="text-xs text-muted-foreground text-center">
              You can close this tab once your desktop app shows you as signed in.
            </Text>
          </View>
        )}

        {status === 'error' && (
          <View className="gap-3 items-center w-full">
            <Text className="text-sm text-destructive text-center">
              {error || 'Something went wrong.'}
            </Text>
            <Button
              variant="outline"
              onPress={() => {
                mintedRef.current = false
                workspacesLoadedRef.current = false
                setStatus('checking-auth')
                setError(null)
              }}
              className="w-full"
            >
              Try Again
            </Button>
          </View>
        )}
      </View>
    </View>
  )
}
