// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Chat Message Edit Routes
 *
 * Extends the auto-generated `/api/chat-messages` CRUD with operations
 * that are awkward to express as per-row PATCH/DELETE because they
 * need to be atomic across many rows.
 *
 * The base CRUD lives in `apps/api/src/generated/chat-message.routes.ts`
 * and is mounted at `/api/chat-messages` via `createGeneratedRoutes` in
 * `server.ts`. We mount THIS router at the same prefix BEFORE the
 * generated one so Hono matches the more specific paths (`/:id/...`)
 * here first.
 *
 * Why a separate file:
 *   - The generated routes file is regenerated by the SDK codegen and
 *     carries a "DO NOT EDIT" banner.
 *   - Authorization is intentionally re-checked here (mirrors the
 *     `chat-message.hooks.ts` pattern) rather than relying on the
 *     generated hooks, since this endpoint isn't part of the CRUD
 *     contract.
 *
 * Endpoints:
 *   - POST /:id/truncate-from
 *       Delete the message itself AND every message in the same
 *       session with a strictly greater `createdAt`. Used by the
 *       in-place message-edit UX (re-send after edit) and the
 *       "Retry from here" action. Atomic via Prisma transaction.
 *
 *   - GET /:id/preceding-checkpoint
 *       Return the latest ProjectCheckpoint whose `createdAt` is
 *       strictly less than the message's `createdAt`, for the
 *       project that owns the message's chat session. Powers the
 *       optional "Also revert project files" affordance in the
 *       edit/retry confirmation dialog. Returns `{ checkpoint: null,
 *       reason }` for the perfectly expected zero-match cases
 *       (no project context, external mode, no prior checkpoint)
 *       so the UI can degrade gracefully instead of treating a 404
 *       as an error.
 *
 * Why "truncate-from" (inclusive of `:id`) and not "truncate-after"
 * (exclusive): the client edit/retry flow always wants to re-send
 * the user message from scratch (so the new content + a fresh row
 * shows up at the bottom), so it would PATCH-then-DELETE-self in a
 * follow-up regardless. Keeping it inclusive collapses that to one
 * round trip and removes a class of partial-failure states where
 * the row is updated but the subsequent rows didn't get deleted.
 */

import { Hono } from 'hono'
import { prisma } from '../lib/prisma'

export function createChatMessageEditRoutes(): Hono {
  const router = new Hono()

  router.post('/:id/truncate-from', async (c) => {
    const auth = c.get('auth') as
      | { userId?: string; tunnelAuthenticated?: boolean; isAuthenticated?: boolean }
      | undefined
    if (!auth?.isAuthenticated || !auth.userId) {
      return c.json(
        { error: { code: 'unauthorized', message: 'Authentication required' } },
        401,
      )
    }

    const id = c.req.param('id')
    if (!id) {
      return c.json(
        { error: { code: 'bad_request', message: 'Message id is required' } },
        400,
      )
    }

    const message = await prisma.chatMessage.findUnique({
      where: { id },
      include: {
        session: {
          include: {
            project: {
              include: {
                workspace: {
                  include: { members: true },
                },
              },
            },
          },
        },
      },
    })

    if (!message) {
      return c.json(
        { error: { code: 'not_found', message: 'Message not found' } },
        404,
      )
    }

    // Same membership check the auto-generated chat-message hooks use.
    // Tunnel-authenticated callers (desktop bridge) skip the check
    // because the tunnel already authoritatively identifies the user
    // outside this router's purview.
    if (!auth.tunnelAuthenticated) {
      const hasAccess = message.session?.project?.workspace?.members?.some(
        (m) => m.userId === auth.userId,
      )
      if (!hasAccess) {
        return c.json(
          {
            error: {
              code: 'forbidden',
              message: 'Access denied to this chat session',
            },
          },
          403,
        )
      }
    }

    const sessionId = message.sessionId
    const cutoff = message.createdAt

    // Atomic: bump everything after the cutoff AND the row itself in
    // one transaction so a partial failure can't leave the session
    // with a half-truncated tail. We delete by `createdAt >= cutoff
    // AND id != prior-rows-in-same-second` via a single `gte` plus
    // the row itself — `createdAt` has millisecond resolution from
    // Prisma's `@default(now())`, and the same-millisecond collision
    // case is handled by the `gte` covering the row's own timestamp
    // (the row itself is included in the `gte` set).
    //
    // Edge case: two messages created in the exact same millisecond
    // (rare; can happen in tests with mocked clocks). The `gte`
    // bucket would catch both rows. To be safe we ALSO scope by
    // sessionId, which is what truly defines "the tail" — there is
    // no realistic case where the user wants to delete same-session
    // rows that happen to share a millisecond but logically precede
    // the target.
    const result = await prisma.$transaction(async (tx) => {
      const deleted = await tx.chatMessage.deleteMany({
        where: {
          sessionId,
          createdAt: { gte: cutoff },
        },
      })

      // Mirror the `afterCreate` chatMessageHooks side effect of
      // bumping the session's updatedAt — without this, the chat
      // session list ordering would drift after a destructive edit.
      await tx.chatSession.update({
        where: { id: sessionId },
        data: { updatedAt: new Date() },
      })

      return { deletedCount: deleted.count }
    })

    return c.json({
      ok: true,
      sessionId,
      deletedCount: result.deletedCount,
    })
  })

  router.get('/:id/preceding-checkpoint', async (c) => {
    const auth = c.get('auth') as
      | { userId?: string; tunnelAuthenticated?: boolean; isAuthenticated?: boolean }
      | undefined
    if (!auth?.isAuthenticated || !auth.userId) {
      return c.json(
        { error: { code: 'unauthorized', message: 'Authentication required' } },
        401,
      )
    }

    const id = c.req.param('id')
    if (!id) {
      return c.json(
        { error: { code: 'bad_request', message: 'Message id is required' } },
        400,
      )
    }

    // Pull the message + ALL the chain we need to resolve project +
    // workspace membership + workingMode in one round trip. Mirrors
    // the membership-resolution shape used by `chat-message.hooks.ts`
    // (beforeGet) so the security contract is identical.
    const message = await prisma.chatMessage.findUnique({
      where: { id },
      include: {
        session: {
          include: {
            project: {
              include: {
                workspace: { include: { members: true } },
              },
            },
          },
        },
      },
    })

    if (!message) {
      return c.json(
        { error: { code: 'not_found', message: 'Message not found' } },
        404,
      )
    }

    // A `ChatSession` may belong to a Feature instead of a Project
    // (see ContextType enum in schema.prisma). Checkpoints only exist
    // for projects, so non-project sessions cleanly degrade to
    // "no checkpoint available" rather than 400/500.
    //
    // We check this BEFORE the membership check on purpose:
    //   - The membership check dereferences
    //     `session.project.workspace.members`, which is null on a
    //     feature-scoped session and would 403 every legitimate
    //     caller.
    //   - The early return leaks no privileged data — `reason:
    //     'no_project_context'` is the same answer any caller
    //     (member or not) would get; the message body itself is
    //     never echoed back.
    const session = message.session
    const project = session?.project
    if (!session || session.contextType !== 'project' || !project) {
      return c.json({
        ok: true,
        checkpoint: null,
        reason: 'no_project_context',
      })
    }

    // Same membership check as truncate-from. Tunnel-authenticated
    // callers (desktop bridge) skip it because the tunnel already
    // authoritatively identifies the user.
    if (!auth.tunnelAuthenticated) {
      const hasAccess = project.workspace?.members?.some(
        (m) => m.userId === auth.userId,
      )
      if (!hasAccess) {
        return c.json(
          {
            error: {
              code: 'forbidden',
              message: 'Access denied to this chat session',
            },
          },
          403,
        )
      }
    }

    // External (folder-linked) projects don't have managed
    // checkpoints — Shogo intentionally doesn't own their git. Same
    // semantics as `checkpoints.ts` externalModeResponse, but we
    // surface it as `reason: 'external_mode'` on a 200 so the dialog
    // can render the "file revert isn't available" hint inline
    // instead of treating a 409 as a hard failure.
    if ((project as { workingMode?: string }).workingMode === 'external') {
      return c.json({
        ok: true,
        checkpoint: null,
        reason: 'external_mode',
      })
    }

    const checkpoint = await prisma.projectCheckpoint.findFirst({
      where: {
        projectId: project.id,
        createdAt: { lt: message.createdAt },
      },
      orderBy: { createdAt: 'desc' },
      // Trim the row to what the dialog actually displays — the
      // commit message + stats — plus the id needed to invoke
      // rollback later. We deliberately do NOT include commitSha
      // here: the rollback endpoint resolves the SHA server-side
      // from the row, and sending it to the client would just
      // tempt callers to bypass the rollback service.
      select: {
        id: true,
        name: true,
        commitMessage: true,
        filesChanged: true,
        additions: true,
        deletions: true,
        isAutomatic: true,
        includesDb: true,
        createdAt: true,
      },
    })

    if (!checkpoint) {
      return c.json({
        ok: true,
        checkpoint: null,
        reason: 'no_checkpoint',
      })
    }

    return c.json({
      ok: true,
      checkpoint,
      projectId: project.id,
    })
  })

  return router
}
