/**
 * App Scaffolding: Create complete app from Enhanced JSON Schema
 *
 * Copies base template, generates domain and routes, customizes for schema.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs"
import { execSync } from "child_process"
import { join, resolve, dirname } from "path"
import nunjucks from "nunjucks"
import type { EnhancedJsonSchema } from "../schematic/types"
import { createRoutes } from "./routes"

/**
 * App features configuration
 */
export interface AppFeatures {
  /** Include API routes (default: true) */
  api?: boolean
  /** Include basic styling (default: true) */
  styling?: boolean
}

/**
 * Configuration for app scaffolding
 */
export interface ScaffoldAppConfig {
  /** Project name (used for directory and package.json) */
  name: string
  /** Enhanced JSON Schema or path to schema file */
  schema: EnhancedJsonSchema | string
  /** Output directory (default: workspaces/{name}) */
  output?: string
  /** App features to include */
  features?: AppFeatures
  /** Skip dependency installation (default: false) */
  skipInstall?: boolean
  /** Dry run - return files without writing (default: false) */
  dryRun?: boolean
}

/**
 * Result of app scaffolding
 */
export interface ScaffoldAppResult {
  /** Absolute path to project directory */
  projectDir: string
  /** List of created/modified files (relative to projectDir) */
  files: string[]
  /** File contents if dryRun is true */
  fileContents?: Record<string, string>
}

// Template for domain.ts
const DOMAIN_TEMPLATE = `/**
 * {{ name }} Domain
 *
 * Generated by @shogo/state-api scaffoldApp()
 */

import { scope } from "arktype"
import { domain } from "@shogo/state-api"

/**
 * {{ name }} ArkType scope
 */
export const {{ scopeName }}Domain = scope({
{%- for entity in entities %}
  {{ entity.name }}: {
{%- for prop in entity.properties %}
    {{ prop.arkTypeDef }},
{%- endfor %}
  },
{%- endfor %}
})

/**
 * {{ name }} domain with enhancements
 */
export const {{ domainName }}Domain = domain({
  name: "{{ schemaName }}",
  from: {{ scopeName }}Domain,
  enhancements: {
    models: (models) => ({
      ...models,
      // Add computed views here
    }),
    collections: (collections) => ({
      ...collections,
      // Add query methods here
    }),
    rootStore: (Root) =>
      Root.views((self) => ({
        // Add domain-wide views here
      })),
  },
})

/**
 * Create store instance
 */
export const create{{ scopeName }}Store = {{ domainName }}Domain.createStore
`

// Template for App.tsx with domain integration
const APP_TEMPLATE = `/**
 * {{ name }} App
 *
 * Generated by @shogo/state-api scaffoldApp()
 */

import { useState, useEffect, createContext, useContext, useMemo } from 'react'
import { observer } from 'mobx-react-lite'
import { {{ domainName }}Domain } from './domain'

// Create domain store
const store = {{ domainName }}Domain.createStore()

// Context for store access
const StoreContext = createContext(store)
export const useStore = () => useContext(StoreContext)

// Main App component
const App = observer(function App() {
  const store = useStore()
{%- if primaryEntity %}
  const items = store.{{ primaryEntity.collectionName }}.items

  const [input, setInput] = useState('')

  const handleAdd = async () => {
    if (!input.trim()) return
    await store.{{ primaryEntity.collectionName }}.insertOne({
      id: crypto.randomUUID(),
      {{ primaryEntity.mainField }}: input.trim(),
{%- for prop in primaryEntity.defaultProps %}
      {{ prop.name }}: {{ prop.default }},
{%- endfor %}
    })
    setInput('')
  }

  const handleDelete = async (id: string) => {
    await store.{{ primaryEntity.collectionName }}.deleteOne(id)
  }
{%- endif %}

  return (
    <div className="app">
      <header className="header">
        <h1>{{ name }}</h1>
{%- if primaryEntity %}
        <p className="subtitle">{items.length} {{ primaryEntity.pluralName | lower }}</p>
{%- endif %}
      </header>

      <main className="main">
{%- if primaryEntity %}
        <div className="input-group">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleAdd()}
            placeholder="Add new {{ primaryEntity.name | lower }}..."
            className="todo-input"
          />
          <button onClick={handleAdd} className="add-btn">Add</button>
        </div>

        <ul className="todo-list">
          {items.map((item: any) => (
            <li key={item.id} className="todo-item">
              <span className="todo-text">{item.{{ primaryEntity.mainField }}}</span>
              <button
                onClick={() => handleDelete(item.id)}
                className="delete-btn"
                aria-label="Delete"
              >
                ×
              </button>
            </li>
          ))}
        </ul>

        {items.length === 0 && (
          <p className="empty-state">No {{ primaryEntity.pluralName | lower }} yet. Add one above!</p>
        )}
{%- else %}
        <p>Welcome to {{ name }}!</p>
{%- endif %}
      </main>

      <footer className="footer">
        <p>Powered by Shogo AI</p>
      </footer>
    </div>
  )
})

export default function AppWrapper() {
  return (
    <StoreContext.Provider value={store}>
      <App />
    </StoreContext.Provider>
  )
}
`

/**
 * Pluralize entity name
 */
function pluralize(name: string): string {
  if (name.endsWith("y")) return name.slice(0, -1) + "ies"
  if (name.endsWith("s") || name.endsWith("x") || name.endsWith("ch") || name.endsWith("sh")) {
    return name + "es"
  }
  return name + "s"
}

/**
 * Convert to camelCase (handles hyphens and underscores)
 */
function toCamelCase(str: string): string {
  return str
    .split(/[-_\s]/)
    .map((word, index) =>
      index === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    )
    .join("")
}

/**
 * Convert to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("")
}

/**
 * Convert JSON Schema type to ArkType definition
 */
function toArkTypeDef(propName: string, propDef: any, required: boolean): string {
  const optional = required ? "" : "?"

  // Reference type
  if (propDef["x-mst-type"] === "reference") {
    const target = propDef["x-reference-target"] || "string"
    return `"${propName}${optional}": "${target}"`
  }

  // Identifier
  if (propDef["x-mst-type"] === "identifier") {
    return `${propName}: "string.uuid"`
  }

  // Basic types
  const type = propDef.type || "string"
  switch (type) {
    case "string":
      if (propDef.format === "email") return `"${propName}${optional}": "string.email"`
      if (propDef.format === "uuid") return `${propName}: "string.uuid"`
      if (propDef.format === "date-time") return `"${propName}${optional}": "string"`
      if (propDef.enum) return `"${propName}${optional}": "'${propDef.enum.join("' | '")}'"`
      return `"${propName}${optional}": "string"`
    case "number":
    case "integer":
      return `"${propName}${optional}": "number"`
    case "boolean":
      return `"${propName}${optional}": "boolean"`
    case "array":
      return `"${propName}${optional}": "string[]"` // Simplified
    default:
      return `"${propName}${optional}": "string"`
  }
}

/**
 * Extract entity info for templates
 */
function extractEntityInfo(schema: EnhancedJsonSchema) {
  const defs = schema.$defs || schema.definitions || {}
  const entities: any[] = []

  for (const [name, def] of Object.entries(defs)) {
    if (typeof def !== "object" || (def as any).type !== "object") continue

    const typedDef = def as any
    const required = new Set(typedDef.required || [])
    const properties: any[] = []

    // Find main text field (first string that's not id)
    let mainField = "name"
    for (const [propName, propDef] of Object.entries(typedDef.properties || {})) {
      if (typeof propDef !== "object") continue
      const p = propDef as any

      if (propName !== "id" && p.type === "string" && !p["x-mst-type"]) {
        mainField = propName
        break
      }
    }

    // Build properties
    for (const [propName, propDef] of Object.entries(typedDef.properties || {})) {
      if (typeof propDef !== "object") continue
      const p = propDef as any

      properties.push({
        name: propName,
        type: p.type || "string",
        required: required.has(propName),
        arkTypeDef: toArkTypeDef(propName, p, required.has(propName)),
        default: p.default !== undefined ? JSON.stringify(p.default) : undefined,
      })
    }

    // Build default props for creation (non-id, non-main fields with defaults)
    const defaultProps = properties
      .filter((p) => p.name !== "id" && p.name !== mainField && p.default !== undefined)
      .map((p) => ({ name: p.name, default: p.default }))

    entities.push({
      name,
      pluralName: pluralize(name),
      collectionName: toCamelCase(name) + "Collection",
      properties,
      mainField,
      defaultProps,
    })
  }

  return entities
}

/**
 * Load schema from path or use directly
 */
function loadSchema(schema: EnhancedJsonSchema | string): EnhancedJsonSchema {
  if (typeof schema === "string") {
    const content = readFileSync(schema, "utf-8")
    return JSON.parse(content)
  }
  return schema
}

/**
 * Get default workspaces directory
 */
function getWorkspacesDir(): string {
  // Try to find monorepo root by looking for package.json with workspaces
  let dir = process.cwd()
  for (let i = 0; i < 5; i++) {
    const pkgPath = join(dir, "package.json")
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
      if (pkg.workspaces) {
        return join(dir, "workspaces")
      }
    }
    dir = dirname(dir)
  }
  return join(process.cwd(), "workspaces")
}

/**
 * Scaffold a complete app from Enhanced JSON Schema
 *
 * @param config - Scaffolding configuration
 * @returns Result with project directory and created files
 *
 * @example
 * ```typescript
 * const result = await scaffoldApp({
 *   name: 'my-app',
 *   schema: myEnhancedSchema,
 * })
 * console.log(result.projectDir) // /path/to/workspaces/my-app
 * ```
 */
export async function scaffoldApp(config: ScaffoldAppConfig): Promise<ScaffoldAppResult> {
  const {
    name,
    schema: schemaInput,
    output,
    features = {},
    skipInstall = false,
    dryRun = false,
  } = config

  const { api = true } = features

  // Load schema
  const schema = loadSchema(schemaInput)
  const schemaName = schema.title || name

  // Determine directories
  const workspacesDir = getWorkspacesDir()
  const templateDir = join(workspacesDir, "_template")
  const projectDir = output ? resolve(output) : join(workspacesDir, name)

  // Extract entity info
  const entities = extractEntityInfo(schema)
  const primaryEntity = entities[0] || null

  // Template context
  const scopeName = toPascalCase(name)
  const domainName = toCamelCase(name)

  // Configure Nunjucks
  const env = new nunjucks.Environment(null, { autoescape: false })
  env.addFilter("lower", (str: string) => str.toLowerCase())
  env.addFilter("title", (str: string) => toPascalCase(str))

  // Generate files
  const files: string[] = []
  const fileContents: Record<string, string> = {}

  // Generate domain.ts
  const domainCode = env.renderString(DOMAIN_TEMPLATE, {
    name,
    schemaName,
    scopeName,
    domainName,
    entities,
  })
  files.push("src/domain.ts")
  fileContents["src/domain.ts"] = domainCode

  // Generate routes.ts if API enabled
  if (api) {
    const routesResult = createRoutes({ schema, basePath: "/api" })
    files.push("src/routes.ts")
    fileContents["src/routes.ts"] = routesResult.code
  }

  // Generate App.tsx
  const appCode = env.renderString(APP_TEMPLATE, {
    name,
    domainName,
    primaryEntity,
  })
  files.push("src/App.tsx")
  fileContents["src/App.tsx"] = appCode

  // If dry run, return without writing
  if (dryRun) {
    return {
      projectDir,
      files,
      fileContents,
    }
  }

  // Copy template (excluding node_modules)
  if (!existsSync(projectDir)) {
    if (existsSync(templateDir)) {
      cpSync(templateDir, projectDir, {
        recursive: true,
        filter: (src) => !src.includes("node_modules"),
      })
    } else {
      mkdirSync(projectDir, { recursive: true })
      mkdirSync(join(projectDir, "src"), { recursive: true })
    }
  }

  // Write generated files
  for (const [filePath, content] of Object.entries(fileContents)) {
    const fullPath = join(projectDir, filePath)
    const dir = dirname(fullPath)
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }
    writeFileSync(fullPath, content, "utf-8")
  }

  // Update package.json name
  const pkgPath = join(projectDir, "package.json")
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
    pkg.name = name
    // Add dependencies
    pkg.dependencies = pkg.dependencies || {}
    pkg.dependencies["@shogo/state-api"] = "workspace:*"
    pkg.dependencies["mobx"] = "^6.12.0"
    pkg.dependencies["mobx-react-lite"] = "^4.0.5"
    pkg.dependencies["mobx-state-tree"] = "^6.0.0"
    if (api) {
      pkg.dependencies["hono"] = "^4.0.0"
    }
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf-8")
    files.push("package.json")
  }

  // Install dependencies
  if (!skipInstall && existsSync(join(projectDir, "package.json"))) {
    try {
      execSync("bun install", {
        cwd: projectDir,
        stdio: "pipe",
        timeout: 120000,
      })
    } catch (error) {
      console.warn("[scaffoldApp] Warning: bun install failed, you may need to run it manually")
    }
  }

  return {
    projectDir,
    files,
  }
}
