// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.

import { resolve } from "node:path"

const mobileRoot = resolve(import.meta.dir, "..")
const entrypoint = resolve(mobileRoot, "components/island/buddy/webview-entry.ts")
const generatedPath = resolve(mobileRoot, "components/island/buddy/buddy-webview.generated.ts")

export async function buildBuddyWebviewHtml(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    target: "browser",
    format: "iife",
    minify: true,
    sourcemap: "none",
  })
  if (!result.success) {
    throw new Error(result.logs.map((log) => log.message).join("\n"))
  }
  const output = result.outputs[0]
  if (!output) throw new Error("Buddy WebView bundle produced no output")
  const script = await output.text()
  return [
    "<!doctype html>",
    '<html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">',
    "<style>html,body{margin:0;padding:0;overflow:hidden;background:transparent}canvas{display:block}</style>",
    "</head><body><canvas id=\"buddy\" aria-label=\"Shogo\"></canvas>",
    `<script>${script}</script>`,
    "</body></html>",
  ].join("")
}

export function formatBuddyWebviewModule(html: string): string {
  return `// This file is generated by scripts/build-buddy-webview.ts. Do not edit by hand.\n\nexport const BUDDY_WEBVIEW_HTML = ${JSON.stringify(html)} as const\n`
}

async function main() {
  const html = await buildBuddyWebviewHtml()
  await Bun.write(generatedPath, formatBuddyWebviewModule(html))
  console.log(`wrote ${generatedPath} (${html.length.toLocaleString()} bytes)`)
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
