-- Migration: affiliate_content_program_application
-- Source:    prisma/schema.local.prisma
--
-- Adds the video-creator (content CPM) application/approval gate to the
-- `affiliates` table: `contentProgramStatus` plus application audit columns.
-- Earning AND payout of content commissions require `approved`.
--
-- Generated by `bun run db:migrate:desktop --name affiliate_content_program_application`
-- and trimmed to the single affected table (the generator also re-emitted
-- pre-existing accepted drift for unrelated tables, which is intentionally
-- excluded here — see scripts/check-desktop-schema-drift accepted-drift list).

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_affiliates" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "parentAffiliateId" TEXT,
    "depth" INTEGER NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'active',
    "stripeCustomAccountId" TEXT,
    "payoutStatus" TEXT NOT NULL DEFAULT 'not_setup',
    "payoutDetailsSubmittedAt" DATETIME,
    "totalEarningsCents" INTEGER NOT NULL DEFAULT 0,
    "pendingPayoutCents" INTEGER NOT NULL DEFAULT 0,
    "totalPaidOutCents" INTEGER NOT NULL DEFAULT 0,
    "commissionRateBps" INTEGER,
    "contentCpmCents" INTEGER,
    "termsAcceptedAt" DATETIME,
    "contentProgramStatus" TEXT NOT NULL DEFAULT 'none',
    "contentAppliedAt" DATETIME,
    "contentReviewedAt" DATETIME,
    "contentReviewedBy" TEXT,
    "contentRejectionReason" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "affiliates_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "affiliates_parentAffiliateId_fkey" FOREIGN KEY ("parentAffiliateId") REFERENCES "affiliates" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_affiliates" ("code", "commissionRateBps", "contentCpmCents", "createdAt", "depth", "id", "parentAffiliateId", "payoutDetailsSubmittedAt", "payoutStatus", "pendingPayoutCents", "status", "stripeCustomAccountId", "termsAcceptedAt", "totalEarningsCents", "totalPaidOutCents", "updatedAt", "userId") SELECT "code", "commissionRateBps", "contentCpmCents", "createdAt", "depth", "id", "parentAffiliateId", "payoutDetailsSubmittedAt", "payoutStatus", "pendingPayoutCents", "status", "stripeCustomAccountId", "termsAcceptedAt", "totalEarningsCents", "totalPaidOutCents", "updatedAt", "userId" FROM "affiliates";
DROP TABLE "affiliates";
ALTER TABLE "new_affiliates" RENAME TO "affiliates";
CREATE UNIQUE INDEX "affiliates_userId_key" ON "affiliates"("userId");
CREATE UNIQUE INDEX "affiliates_code_key" ON "affiliates"("code");
CREATE INDEX "affiliates_parentAffiliateId_idx" ON "affiliates"("parentAffiliateId");
CREATE INDEX "affiliates_status_idx" ON "affiliates"("status");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- Backfill: affiliates that already have a verified social handle (or any
-- content commissions) were earning under the pre-gate behaviour; approve
-- them so the new gate doesn't strand existing earners.
UPDATE "affiliates" SET "contentProgramStatus" = 'approved', "contentReviewedAt" = CURRENT_TIMESTAMP
WHERE "id" IN (SELECT DISTINCT "affiliateId" FROM "affiliate_social_accounts" WHERE "verificationStatus" = 'verified')
   OR "id" IN (SELECT DISTINCT "affiliateId" FROM "affiliate_commissions" WHERE "source" = 'content');
