// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated BillingAccount Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface BillingAccountType {
  id: string
  workspaceId: string
  stripeCustomerId?: string
  taxId?: string
  createdAt: Date
  updatedAt: Date
}

export interface BillingAccountCreateInput {
  workspaceId: string
  stripeCustomerId?: string
  taxId?: string
}

export interface BillingAccountUpdateInput {
  workspaceId?: string
  stripeCustomerId?: string
  taxId?: string
}
