// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatSession Store
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { OptimisticStore } from "@shogo-ai/sdk"
import type { HttpClient } from "@shogo-ai/sdk"
import type { ChatSessionType } from "./chat-session.types"

// Store instance (singleton)
let _store: OptimisticStore<ChatSessionType> | null = null

/**
 * Get or create the ChatSession store
 *
 * @param http - HttpClient instance (required on first call)
 */
export function getChatSessionStore(http?: HttpClient): OptimisticStore<ChatSessionType> {
  if (!_store) {
    if (!http) {
      throw new Error("HttpClient required to initialize ChatSessionStore")
    }
    _store = new OptimisticStore<ChatSessionType>({
      http,
      endpoint: "/api/chat-sessions",
    })
  }
  return _store
}

/**
 * Reset the ChatSession store (for testing)
 */
export function resetChatSessionStore(): void {
  _store = null
}

// Convenience export for direct import
export type { ChatSessionType }
