// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatSession Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ContextType = 'feature' | 'project' | 'general'

export interface ChatSessionType {
  id: string
  name?: string
  inferredName: string
  contextType: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  cachedMessageCount: number
  contextUsageTokens: number
  contextWindowTokens: number
  isPinned: boolean
  isArchived: boolean
  createdAt: Date
  updatedAt: Date
  lastActiveAt: Date
}

export interface ChatSessionCreateInput {
  name?: string
  inferredName: string
  contextType: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  cachedMessageCount?: number
  contextUsageTokens?: number
  contextWindowTokens?: number
  isPinned?: boolean
  isArchived?: boolean
  lastActiveAt?: Date
}

export interface ChatSessionUpdateInput {
  name?: string
  inferredName?: string
  contextType?: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  cachedMessageCount?: number
  contextUsageTokens?: number
  contextWindowTokens?: number
  isPinned?: boolean
  isArchived?: boolean
  lastActiveAt?: Date
}
