// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatSessionProject Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface ChatSessionProjectType {
  id: string
  sessionId: string
  projectId: string
  attachMode: string
  createdAt: Date
}

export interface ChatSessionProjectCreateInput {
  sessionId: string
  projectId: string
  attachMode?: string
}

export interface ChatSessionProjectUpdateInput {
  sessionId?: string
  projectId?: string
  attachMode?: string
}
