/**
 * Auto-generated ChatMessage Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ChatRole = 'user' | 'assistant'

export interface ChatMessageType {
  id: string
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
  createdAt: Date
}

export interface ChatMessageCreateInput {
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
}

export interface ChatMessageUpdateInput {
  sessionId?: string
  role?: ChatRole
  content?: string
  imageData?: string
  parts?: string
}
