// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatMessage Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ChatRole = 'user' | 'assistant'

export interface MentionRef {
  path: string
  displayName: string
}

export interface ChatMessageType {
  id: string
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
  mentions?: MentionRef[]
  createdAt: Date
  agent: string
}

export interface ChatMessageCreateInput {
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
  mentions?: MentionRef[]
  agent?: string
}

export interface ChatMessageUpdateInput {
  sessionId?: string
  role?: ChatRole
  content?: string
  imageData?: string
  parts?: string
  mentions?: MentionRef[]
  agent?: string
}

export function parseMentions(value: unknown): MentionRef[] {
  const raw = typeof value === 'string' ? safeJsonParse(value) : value
  if (!Array.isArray(raw)) return []

  return raw
    .filter((item): item is MentionRef => (
      !!item &&
      typeof item === 'object' &&
      typeof (item as MentionRef).path === 'string' &&
      typeof (item as MentionRef).displayName === 'string'
    ))
    .map((item) => ({ path: item.path, displayName: item.displayName }))
}

export function serializeMentions(value: MentionRef[] | undefined): MentionRef[] | undefined {
  if (!value || value.length === 0) return undefined
  return parseMentions(value)
}

function safeJsonParse(value: string): unknown {
  try {
    return JSON.parse(value)
  } catch {
    return []
  }
}
