/**
 * Auto-generated ChatMessage Store
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { OptimisticStore } from "@shogo-ai/sdk"
import type { HttpClient } from "@shogo-ai/sdk"
import type { ChatMessageType } from "./chat-message.types"

// Store instance (singleton)
let _store: OptimisticStore<ChatMessageType> | null = null

/**
 * Get or create the ChatMessage store
 *
 * @param http - HttpClient instance (required on first call)
 */
export function getChatMessageStore(http?: HttpClient): OptimisticStore<ChatMessageType> {
  if (!_store) {
    if (!http) {
      throw new Error("HttpClient required to initialize ChatMessageStore")
    }
    _store = new OptimisticStore<ChatMessageType>({
      http,
      endpoint: "/api/chat-messages",
    })
  }
  return _store
}

/**
 * Reset the ChatMessage store (for testing)
 */
export function resetChatMessageStore(): void {
  _store = null
}

// Convenience export for direct import
export type { ChatMessageType }
