// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatMessage Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ChatRole = 'user' | 'assistant'

export interface ChatMessageType {
  id: string
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
  createdAt: Date
  agent: string
}

export interface ChatMessageCreateInput {
  sessionId: string
  role: ChatRole
  content: string
  imageData?: string
  parts?: string
  agent?: string
}

export interface ChatMessageUpdateInput {
  sessionId?: string
  role?: ChatRole
  content?: string
  imageData?: string
  parts?: string
  agent?: string
}
