// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatSessionProject MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { ChatSessionModel } from "./chat-session.model"
import { ProjectModel } from "./project.model"

// ============================================================================
// ChatSessionProject Model
// ============================================================================

export const ChatSessionProjectModel = types
  .model("ChatSessionProject", {
    id: types.identifier,
    sessionId: types.string,
    projectId: types.string,
    attachMode: types.optional(types.string, "readwrite"),
    createdAt: types.optional(types.number, 0),
    session: types.safeReference(types.late(() => ChatSessionModel)),
    project: types.safeReference(types.late(() => ProjectModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IChatSessionProject extends Instance<typeof ChatSessionProjectModel> {}
export interface IChatSessionProjectSnapshotIn extends SnapshotIn<typeof ChatSessionProjectModel> {}
export interface IChatSessionProjectSnapshotOut extends SnapshotOut<typeof ChatSessionProjectModel> {}
