// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ChatSession Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ContextType = 'feature' | 'project' | 'general'

export interface ChatSessionType {
  id: string
  name?: string
  inferredName: string
  contextType: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  createdAt: Date
  updatedAt: Date
  lastActiveAt: Date
}

export interface ChatSessionCreateInput {
  name?: string
  inferredName: string
  contextType: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  lastActiveAt?: Date
}

export interface ChatSessionUpdateInput {
  name?: string
  inferredName?: string
  contextType?: ContextType
  contextId?: string
  phase?: string
  claudeCodeSessionId?: string
  lastActiveAt?: Date
}
