// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
// @ts-nocheck
/**
 * Auto-generated CreditLedger MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { WorkspaceModel } from "./workspace.model"

// ============================================================================
// CreditLedger Model
// ============================================================================

export const CreditLedgerModel = types
  .model("CreditLedger", {
    id: types.identifier,
    workspaceId: types.string,
    monthlyCredits: types.optional(types.number, 0),
    dailyCredits: types.optional(types.number, 0),
    monthlyAllocation: types.optional(types.number, 0),
    anniversaryDay: types.number,
    lastDailyReset: types.optional(types.number, 0),
    lastMonthlyReset: types.optional(types.number, 0),
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    workspace: types.safeReference(types.late(() => WorkspaceModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface ICreditLedger extends Instance<typeof CreditLedgerModel> {}
export interface ICreditLedgerSnapshotIn extends SnapshotIn<typeof CreditLedgerModel> {}
export interface ICreditLedgerSnapshotOut extends SnapshotOut<typeof CreditLedgerModel> {}
