/**
 * Auto-generated CreditLedger Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface CreditLedgerType {
  id: string
  workspaceId: string
  monthlyCredits: number
  dailyCredits: number
  rolloverCredits: number
  anniversaryDay: number
  lastDailyReset: Date
  lastMonthlyReset: Date
  createdAt: Date
  updatedAt: Date
}

export interface CreditLedgerCreateInput {
  workspaceId: string
  monthlyCredits?: number
  dailyCredits?: number
  rolloverCredits?: number
  anniversaryDay: number
  lastDailyReset: Date
  lastMonthlyReset: Date
}

export interface CreditLedgerUpdateInput {
  workspaceId?: string
  monthlyCredits?: number
  dailyCredits?: number
  rolloverCredits?: number
  anniversaryDay?: number
  lastDailyReset?: Date
  lastMonthlyReset?: Date
}
