// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Domain Store
 *
 * Root MST store combining all collections.
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"
import type { HttpClient } from "@shogo-ai/sdk"

// Collection imports
import { UserCollection, type IUserCollection } from "./user.collection"
import { WorkspaceCollection, type IWorkspaceCollection } from "./workspace.collection"
import { ProjectCollection, type IProjectCollection } from "./project.collection"
import { StarredProjectCollection, type IStarredProjectCollection } from "./starred-project.collection"
import { MemberCollection, type IMemberCollection } from "./member.collection"
import { BillingAccountCollection, type IBillingAccountCollection } from "./billing-account.collection"
import { InvitationCollection, type IInvitationCollection } from "./invitation.collection"
import { FolderCollection, type IFolderCollection } from "./folder.collection"
import { NotificationCollection, type INotificationCollection } from "./notification.collection"
import { SubscriptionCollection, type ISubscriptionCollection } from "./subscription.collection"
import { UsageWalletCollection, type IUsageWalletCollection } from "./usage-wallet.collection"
import { UsageEventCollection, type IUsageEventCollection } from "./usage-event.collection"
import { ChatSessionCollection, type IChatSessionCollection } from "./chat-session.collection"
import { ChatMessageCollection, type IChatMessageCollection } from "./chat-message.collection"
import { ToolCallLogCollection, type IToolCallLogCollection } from "./tool-call-log.collection"
import { FeatureSessionCollection, type IFeatureSessionCollection } from "./feature-session.collection"

// Model imports (for type re-exports)
export { UserModel, type IUser, type IUserSnapshotIn, type IUserSnapshotOut } from "./user.model"
export { WorkspaceModel, type IWorkspace, type IWorkspaceSnapshotIn, type IWorkspaceSnapshotOut } from "./workspace.model"
export { ProjectModel, type IProject, type IProjectSnapshotIn, type IProjectSnapshotOut } from "./project.model"
export { StarredProjectModel, type IStarredProject, type IStarredProjectSnapshotIn, type IStarredProjectSnapshotOut } from "./starred-project.model"
export { MemberModel, type IMember, type IMemberSnapshotIn, type IMemberSnapshotOut } from "./member.model"
export { BillingAccountModel, type IBillingAccount, type IBillingAccountSnapshotIn, type IBillingAccountSnapshotOut } from "./billing-account.model"
export { InvitationModel, type IInvitation, type IInvitationSnapshotIn, type IInvitationSnapshotOut } from "./invitation.model"
export { FolderModel, type IFolder, type IFolderSnapshotIn, type IFolderSnapshotOut } from "./folder.model"
export { NotificationModel, type INotification, type INotificationSnapshotIn, type INotificationSnapshotOut } from "./notification.model"
export { SubscriptionModel, type ISubscription, type ISubscriptionSnapshotIn, type ISubscriptionSnapshotOut } from "./subscription.model"
export { UsageWalletModel, type IUsageWallet, type IUsageWalletSnapshotIn, type IUsageWalletSnapshotOut } from "./usage-wallet.model"
export { UsageEventModel, type IUsageEvent, type IUsageEventSnapshotIn, type IUsageEventSnapshotOut } from "./usage-event.model"
export { ChatSessionModel, type IChatSession, type IChatSessionSnapshotIn, type IChatSessionSnapshotOut } from "./chat-session.model"
export { ChatMessageModel, type IChatMessage, type IChatMessageSnapshotIn, type IChatMessageSnapshotOut } from "./chat-message.model"
export { ToolCallLogModel, type IToolCallLog, type IToolCallLogSnapshotIn, type IToolCallLogSnapshotOut } from "./tool-call-log.model"
export { FeatureSessionModel, type IFeatureSession, type IFeatureSessionSnapshotIn, type IFeatureSessionSnapshotOut } from "./feature-session.model"

// Collection type re-exports
export { UserCollection, type IUserCollection }
export { WorkspaceCollection, type IWorkspaceCollection }
export { ProjectCollection, type IProjectCollection }
export { StarredProjectCollection, type IStarredProjectCollection }
export { MemberCollection, type IMemberCollection }
export { BillingAccountCollection, type IBillingAccountCollection }
export { InvitationCollection, type IInvitationCollection }
export { FolderCollection, type IFolderCollection }
export { NotificationCollection, type INotificationCollection }
export { SubscriptionCollection, type ISubscriptionCollection }
export { UsageWalletCollection, type IUsageWalletCollection }
export { UsageEventCollection, type IUsageEventCollection }
export { ChatSessionCollection, type IChatSessionCollection }
export { ChatMessageCollection, type IChatMessageCollection }
export { ToolCallLogCollection, type IToolCallLogCollection }
export { FeatureSessionCollection, type IFeatureSessionCollection }

// ============================================================================
// SDK Environment Type
// ============================================================================

/**
 * Environment interface for SDK MST stores.
 * Inject this when creating the store.
 */
export interface ISDKEnvironment {
  /** HTTP client for API calls */
  http: HttpClient
  /** Optional context for authorization */
  context?: {
    userId?: string
    workspaceId?: string
  }
}

// ============================================================================
// Root Store
// ============================================================================

/**
 * Root domain store combining all collections.
 */
export const DomainStore = types
  .model("DomainStore", {
    userCollection: types.optional(UserCollection, { items: {} }),
    workspaceCollection: types.optional(WorkspaceCollection, { items: {} }),
    projectCollection: types.optional(ProjectCollection, { items: {} }),
    starredProjectCollection: types.optional(StarredProjectCollection, { items: {} }),
    memberCollection: types.optional(MemberCollection, { items: {} }),
    billingAccountCollection: types.optional(BillingAccountCollection, { items: {} }),
    invitationCollection: types.optional(InvitationCollection, { items: {} }),
    folderCollection: types.optional(FolderCollection, { items: {} }),
    notificationCollection: types.optional(NotificationCollection, { items: {} }),
    subscriptionCollection: types.optional(SubscriptionCollection, { items: {} }),
    usageWalletCollection: types.optional(UsageWalletCollection, { items: {} }),
    usageEventCollection: types.optional(UsageEventCollection, { items: {} }),
    chatSessionCollection: types.optional(ChatSessionCollection, { items: {} }),
    chatMessageCollection: types.optional(ChatMessageCollection, { items: {} }),
    toolCallLogCollection: types.optional(ToolCallLogCollection, { items: {} }),
    featureSessionCollection: types.optional(FeatureSessionCollection, { items: {} }),
  })

  .views(self => ({
    /** Get all collection names */
    get collectionNames(): string[] {
      return [
        "userCollection",
        "workspaceCollection",
        "projectCollection",
        "starredProjectCollection",
        "memberCollection",
        "billingAccountCollection",
        "invitationCollection",
        "folderCollection",
        "notificationCollection",
        "subscriptionCollection",
        "usageWalletCollection",
        "usageEventCollection",
        "chatSessionCollection",
        "chatMessageCollection",
        "toolCallLogCollection",
        "featureSessionCollection",
      ]
    },
  }))

  .actions(self => ({
    /** Clear all collections */
    clearAll() {
      self.userCollection.clear()
      self.workspaceCollection.clear()
      self.projectCollection.clear()
      self.starredProjectCollection.clear()
      self.memberCollection.clear()
      self.billingAccountCollection.clear()
      self.invitationCollection.clear()
      self.folderCollection.clear()
      self.notificationCollection.clear()
      self.subscriptionCollection.clear()
      self.usageWalletCollection.clear()
      self.usageEventCollection.clear()
      self.chatSessionCollection.clear()
      self.chatMessageCollection.clear()
      self.toolCallLogCollection.clear()
      self.featureSessionCollection.clear()
    },

    /** Clear all errors */
    clearAllErrors() {
      self.userCollection.clearError()
      self.workspaceCollection.clearError()
      self.projectCollection.clearError()
      self.starredProjectCollection.clearError()
      self.memberCollection.clearError()
      self.billingAccountCollection.clearError()
      self.invitationCollection.clearError()
      self.folderCollection.clearError()
      self.notificationCollection.clearError()
      self.subscriptionCollection.clearError()
      self.usageWalletCollection.clearError()
      self.usageEventCollection.clearError()
      self.chatSessionCollection.clearError()
      self.chatMessageCollection.clearError()
      self.toolCallLogCollection.clearError()
      self.featureSessionCollection.clearError()
    },
  }))

// Type exports
export type IDomainStore = Instance<typeof DomainStore>
export type IDomainStoreSnapshotIn = SnapshotIn<typeof DomainStore>
export type IDomainStoreSnapshotOut = SnapshotOut<typeof DomainStore>

// ============================================================================
// Factory Functions
// ============================================================================

/** Singleton store instance */
let _store: IDomainStore | null = null

/**
 * Create a new domain store instance.
 *
 * @param env - SDK environment with HttpClient
 * @returns New domain store instance
 *
 * @example
 * ```typescript
 * import { createDomainStore, type ISDKEnvironment } from "./generated/domain"
 * import { HttpClient } from "@shogo-ai/sdk"
 *
 * const http = new HttpClient({ baseUrl: "http://localhost:3000" })
 * const store = createDomainStore({ http })
 *
 * // Load data
 * await store.workspaceCollection.loadAll()
 * console.log(store.workspaceCollection.all)
 * ```
 */
export function createDomainStore(env: ISDKEnvironment): IDomainStore {
  return DomainStore.create({}, env)
}

/**
 * Get or create singleton domain store.
 *
 * @param env - SDK environment (required on first call)
 * @returns Singleton domain store instance
 */
export function getDomainStore(env?: ISDKEnvironment): IDomainStore {
  if (!_store) {
    if (!env) {
      throw new Error("SDK environment required to initialize domain store")
    }
    _store = createDomainStore(env)
  }
  return _store
}

/**
 * Reset singleton store (for testing or auth changes)
 */
export function resetDomainStore(): void {
  _store = null
}
