// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated FeatureSession MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { ProjectModel } from "./project.model"

// ============================================================================
// FeatureSession Model
// ============================================================================

export const FeatureSessionModel = types
  .model("FeatureSession", {
    id: types.identifier,
    name: types.string,
    intent: types.string,
    status: types.enumeration("FeatureStatus", ["discovery", "analysis", "classification", "design", "spec", "implementation", "testing", "complete"]),
    affectedPackages: types.optional(types.array(types.string), []),
    schemaName: types.optional(types.string, ""),
    initialAssessment: types.optional(types.frozen(), {}),
    featureArchetype: types.maybeNull(types.enumeration("FeatureArchetype", ["service", "domain", "infrastructure", "hybrid"])),
    applicablePatterns: types.optional(types.array(types.string), []),
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    projectId: types.optional(types.string, ""),
    project: types.safeReference(types.late(() => ProjectModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IFeatureSession extends Instance<typeof FeatureSessionModel> {}
export interface IFeatureSessionSnapshotIn extends SnapshotIn<typeof FeatureSessionModel> {}
export interface IFeatureSessionSnapshotOut extends SnapshotOut<typeof FeatureSessionModel> {}
