/**
 * Auto-generated Folder Store
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { OptimisticStore } from "@shogo-ai/sdk"
import type { HttpClient } from "@shogo-ai/sdk"
import type { FolderType } from "./folder.types"

// Store instance (singleton)
let _store: OptimisticStore<FolderType> | null = null

/**
 * Get or create the Folder store
 *
 * @param http - HttpClient instance (required on first call)
 */
export function getFolderStore(http?: HttpClient): OptimisticStore<FolderType> {
  if (!_store) {
    if (!http) {
      throw new Error("HttpClient required to initialize FolderStore")
    }
    _store = new OptimisticStore<FolderType>({
      http,
      endpoint: "/api/folders",
    })
  }
  return _store
}

/**
 * Reset the Folder store (for testing)
 */
export function resetFolderStore(): void {
  _store = null
}

// Convenience export for direct import
export type { FolderType }
