// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Folder Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface FolderType {
  id: string
  name: string
  workspaceId: string
  parentId?: string
  createdBy?: string
  createdAt: Date
  updatedAt: Date
}

export interface FolderCreateInput {
  name: string
  workspaceId: string
  parentId?: string
  createdBy?: string
}

export interface FolderUpdateInput {
  name?: string
  workspaceId?: string
  parentId?: string
  createdBy?: string
}
