// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Invitation Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import type { MemberRole } from "./member.types"

export type InvitationStatus = 'pending' | 'accepted' | 'declined' | 'expired' | 'cancelled'

export type EmailStatus = 'not_sent' | 'sent' | 'failed'

export interface InvitationType {
  id: string
  email: string
  role: MemberRole
  workspaceId?: string
  projectId?: string
  status: InvitationStatus
  emailStatus: EmailStatus
  emailSentAt?: Date
  emailError?: string
  invitedBy?: string
  expiresAt: Date
  createdAt: Date
  updatedAt: Date
}

export interface InvitationCreateInput {
  email: string
  role?: MemberRole
  workspaceId?: string
  projectId?: string
  status?: InvitationStatus
  emailStatus?: EmailStatus
  emailSentAt?: Date
  emailError?: string
  invitedBy?: string
  expiresAt: Date
}

export interface InvitationUpdateInput {
  email?: string
  role?: MemberRole
  workspaceId?: string
  projectId?: string
  status?: InvitationStatus
  emailStatus?: EmailStatus
  emailSentAt?: Date
  emailError?: string
  invitedBy?: string
  expiresAt?: Date
}
