// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
// @ts-nocheck
/**
 * Auto-generated Member MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Cyclic model references are resolved lazily to avoid "Require cycle" warnings.
// types.late() defers resolution until the MST tree is first instantiated, by
// which point all modules are fully evaluated.

// ============================================================================
// Member Model
// ============================================================================

export const MemberModel = types
  .model("Member", {
    id: types.identifier,
    userId: types.string,
    role: types.enumeration("MemberRole", ["owner", "admin", "member", "viewer"]),
    workspaceId: types.optional(types.string, ""),
    projectId: types.optional(types.string, ""),
    isBillingAdmin: types.boolean,
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    user: types.safeReference(types.late(() => require("./user.model").UserModel)),
    workspace: types.safeReference(types.late(() => require("./workspace.model").WorkspaceModel)),
    project: types.safeReference(types.late(() => require("./project.model").ProjectModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IMember extends Instance<typeof MemberModel> {}
export interface IMemberSnapshotIn extends SnapshotIn<typeof MemberModel> {}
export interface IMemberSnapshotOut extends SnapshotOut<typeof MemberModel> {}
