// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Notification Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type NotificationType = 'invitation_pending' | 'invitation_accepted' | 'member_joined' | 'member_left' | 'workspace_updated'

export interface Notification {
  id: string
  userId: string
  type: NotificationType
  title: string
  message: string
  metadata?: Record<string, unknown>
  actionUrl?: string
  readAt?: Date
  createdAt: Date
}

export interface NotificationCreateInput {
  userId: string
  type: NotificationType
  title: string
  message: string
  metadata?: Record<string, unknown>
  actionUrl?: string
  readAt?: Date
}

export interface NotificationUpdateInput {
  userId?: string
  type?: NotificationType
  title?: string
  message?: string
  metadata?: Record<string, unknown>
  actionUrl?: string
  readAt?: Date
}
