// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
// @ts-nocheck
/**
 * Auto-generated Project MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
// WorkspaceModel uses require() inside types.late() to break the
// workspace ↔ project circular module reference.
import { FolderModel } from "./folder.model"
import { MemberModel } from "./member.model"
import { FeatureSessionModel } from "./feature-session.model"
import { ChatSessionModel } from "./chat-session.model"
import { UsageEventModel } from "./usage-event.model"
import { StarredProjectModel } from "./starred-project.model"

// ============================================================================
// Project Model
// ============================================================================

export const ProjectModel = types
  .model("Project", {
    id: types.identifier,
    name: types.string,
    description: types.optional(types.string, ""),
    workspaceId: types.string,
    tier: types.enumeration("ProjectTier", ["starter", "pro", "enterprise", "internal"]),
    status: types.enumeration("ProjectStatus", ["draft", "active", "archived"]),
    schemas: types.optional(types.array(types.string), []),
    createdBy: types.optional(types.string, ""),
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    folderId: types.optional(types.string, ""),
    publishedSubdomain: types.optional(types.string, ""),
    publishedAt: types.optional(types.number, 0),
    accessLevel: types.enumeration("AccessLevel", ["anyone", "authenticated", "private"]),
    category: types.optional(types.string, ""),
    siteTitle: types.optional(types.string, ""),
    siteDescription: types.optional(types.string, ""),
    thumbnailUrl: types.optional(types.string, ""),
    settings: types.frozen<Record<string, unknown> | null>(null),
    workspace: types.safeReference(types.late(() => require("./workspace.model").WorkspaceModel)),
    folder: types.safeReference(types.late(() => FolderModel)),
    members: types.optional(types.array(types.safeReference(types.late(() => MemberModel))), []),
    featureSessions: types.optional(types.array(types.safeReference(types.late(() => FeatureSessionModel))), []),
    chatSessions: types.optional(types.array(types.safeReference(types.late(() => ChatSessionModel))), []),
    usageEvents: types.optional(types.array(types.safeReference(types.late(() => UsageEventModel))), []),
    starredBy: types.optional(types.array(types.safeReference(types.late(() => StarredProjectModel))), []),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IProject extends Instance<typeof ProjectModel> {}
export interface IProjectSnapshotIn extends SnapshotIn<typeof ProjectModel> {}
export interface IProjectSnapshotOut extends SnapshotOut<typeof ProjectModel> {}
