// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ProjectFolder Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface ProjectFolderType {
  id: string
  projectId: string
  path: string
  isPrimary: boolean
  addedAt: Date
  lastOpenedAt?: Date
}

export interface ProjectFolderCreateInput {
  projectId: string
  path: string
  isPrimary?: boolean
  addedAt?: Date
  lastOpenedAt?: Date
}

export interface ProjectFolderUpdateInput {
  projectId?: string
  path?: string
  isPrimary?: boolean
  addedAt?: Date
  lastOpenedAt?: Date
}
