// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated StarredProject Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface StarredProjectType {
  id: string
  userId: string
  projectId: string
  workspaceId: string
  createdAt: Date
}

export interface StarredProjectCreateInput {
  userId: string
  projectId: string
  workspaceId: string
}

export interface StarredProjectUpdateInput {
  userId?: string
  projectId?: string
  workspaceId?: string
}
