// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
// @ts-nocheck
/**
 * Auto-generated StarredProject MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { UserModel } from "./user.model"
import { WorkspaceModel } from "./workspace.model"
import { ProjectModel } from "./project.model"

// ============================================================================
// StarredProject Model
// ============================================================================

export const StarredProjectModel = types
  .model("StarredProject", {
    id: types.identifier,
    userId: types.string,
    projectId: types.string,
    workspaceId: types.string,
    createdAt: types.optional(types.number, 0),
    user: types.safeReference(types.late(() => UserModel)),
    workspace: types.safeReference(types.late(() => WorkspaceModel)),
    project: types.safeReference(types.late(() => ProjectModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IStarredProject extends Instance<typeof StarredProjectModel> {}
export interface IStarredProjectSnapshotIn extends SnapshotIn<typeof StarredProjectModel> {}
export interface IStarredProjectSnapshotOut extends SnapshotOut<typeof StarredProjectModel> {}
