// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Subscription Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type SubscriptionStatus = 'active' | 'past_due' | 'canceled' | 'trialing' | 'paused'

export type BillingInterval = 'monthly' | 'annual'

export interface SubscriptionType {
  id: string
  workspaceId: string
  stripeSubscriptionId: string
  stripeCustomerId: string
  planId: string
  seats: number
  status: SubscriptionStatus
  billingInterval: BillingInterval
  currentPeriodStart: Date
  currentPeriodEnd: Date
  cancelAtPeriodEnd: boolean
  createdAt: Date
  updatedAt: Date
}

export interface SubscriptionCreateInput {
  workspaceId: string
  stripeSubscriptionId: string
  stripeCustomerId: string
  planId: string
  seats?: number
  status: SubscriptionStatus
  billingInterval: BillingInterval
  currentPeriodStart: Date
  currentPeriodEnd: Date
  cancelAtPeriodEnd?: boolean
}

export interface SubscriptionUpdateInput {
  workspaceId?: string
  stripeSubscriptionId?: string
  stripeCustomerId?: string
  planId?: string
  seats?: number
  status?: SubscriptionStatus
  billingInterval?: BillingInterval
  currentPeriodStart?: Date
  currentPeriodEnd?: Date
  cancelAtPeriodEnd?: boolean
}
