// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Subscription MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { WorkspaceModel } from "./workspace.model"

// ============================================================================
// Subscription Model
// ============================================================================

export const SubscriptionModel = types
  .model("Subscription", {
    id: types.identifier,
    workspaceId: types.string,
    stripeSubscriptionId: types.string,
    stripeCustomerId: types.string,
    planId: types.string,
    /**
     * Paying seat count. Basic is always 1; Pro/Business are per-seat. The
     * server (`Subscription.seats`) is the source of truth — the client
     * model exposes it for UI math (price/included display).
     */
    seats: types.optional(types.number, 1),
    status: types.enumeration("SubscriptionStatus", ["active", "past_due", "canceled", "trialing", "paused"]),
    billingInterval: types.enumeration("BillingInterval", ["monthly", "annual"]),
    currentPeriodStart: types.number,
    currentPeriodEnd: types.number,
    cancelAtPeriodEnd: types.optional(types.boolean, false),
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    workspace: types.safeReference(types.late(() => WorkspaceModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface ISubscription extends Instance<typeof SubscriptionModel> {}
export interface ISubscriptionSnapshotIn extends SnapshotIn<typeof SubscriptionModel> {}
export interface ISubscriptionSnapshotOut extends SnapshotOut<typeof SubscriptionModel> {}
