// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ToolCallLog Store
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { OptimisticStore } from "@shogo-ai/sdk"
import type { HttpClient } from "@shogo-ai/sdk"
import type { ToolCallLogType } from "./tool-call-log.types"

// Store instance (singleton)
let _store: OptimisticStore<ToolCallLogType> | null = null

/**
 * Get or create the ToolCallLog store
 *
 * @param http - HttpClient instance (required on first call)
 */
export function getToolCallLogStore(http?: HttpClient): OptimisticStore<ToolCallLogType> {
  if (!_store) {
    if (!http) {
      throw new Error("HttpClient required to initialize ToolCallLogStore")
    }
    _store = new OptimisticStore<ToolCallLogType>({
      http,
      endpoint: "/api/tool-call-logs",
    })
  }
  return _store
}

/**
 * Reset the ToolCallLog store (for testing)
 */
export function resetToolCallLogStore(): void {
  _store = null
}

// Convenience export for direct import
export type { ToolCallLogType }
