// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated ToolCallLog Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type ToolCallStatus = 'streaming' | 'executing' | 'complete' | 'error'

export interface ToolCallLogType {
  id: string
  chatSessionId: string
  messageId: string
  toolName: string
  status: ToolCallStatus
  args?: Record<string, unknown>
  result?: Record<string, unknown>
  duration?: number
  createdAt: Date
}

export interface ToolCallLogCreateInput {
  chatSessionId: string
  messageId: string
  toolName: string
  status: ToolCallStatus
  args?: Record<string, unknown>
  result?: Record<string, unknown>
  duration?: number
}

export interface ToolCallLogUpdateInput {
  chatSessionId?: string
  messageId?: string
  toolName?: string
  status?: ToolCallStatus
  args?: Record<string, unknown>
  result?: Record<string, unknown>
  duration?: number
}
