// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated UsageEvent Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type UsageSource = 'daily' | 'monthly' | 'overage' | 'window'

export interface UsageEventType {
  id: string
  workspaceId: string
  projectId?: string
  memberId: string
  actionType: string
  actionMetadata?: Record<string, unknown>
  rawUsd?: number
  billedUsd: number
  source: UsageSource
  balanceBefore: number
  balanceAfter: number
  createdAt: Date
}

export interface UsageEventCreateInput {
  workspaceId: string
  projectId?: string
  memberId: string
  actionType: string
  actionMetadata?: Record<string, unknown>
  rawUsd?: number
  billedUsd: number
  source: UsageSource
  balanceBefore: number
  balanceAfter: number
}

export interface UsageEventUpdateInput {
  workspaceId?: string
  projectId?: string
  memberId?: string
  actionType?: string
  actionMetadata?: Record<string, unknown>
  rawUsd?: number
  billedUsd?: number
  source?: UsageSource
  balanceBefore?: number
  balanceAfter?: number
}
