/**
 * Auto-generated UsageEvent Store
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { OptimisticStore } from "@shogo-ai/sdk"
import type { HttpClient } from "@shogo-ai/sdk"
import type { UsageEventType } from "./usage-event.types"

// Store instance (singleton)
let _store: OptimisticStore<UsageEventType> | null = null

/**
 * Get or create the UsageEvent store
 *
 * @param http - HttpClient instance (required on first call)
 */
export function getUsageEventStore(http?: HttpClient): OptimisticStore<UsageEventType> {
  if (!_store) {
    if (!http) {
      throw new Error("HttpClient required to initialize UsageEventStore")
    }
    _store = new OptimisticStore<UsageEventType>({
      http,
      endpoint: "/api/usage-events",
    })
  }
  return _store
}

/**
 * Reset the UsageEvent store (for testing)
 */
export function resetUsageEventStore(): void {
  _store = null
}

// Convenience export for direct import
export type { UsageEventType }
