// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated UsageWallet Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface UsageWalletType {
  id: string
  workspaceId: string
  monthlyIncludedUsd: number
  dailyIncludedUsd: number
  monthlyIncludedAllocationUsd: number
  dailyUsedThisMonthUsd: number
  overageEnabled: boolean
  overageHardLimitUsd?: number
  overageAccumulatedUsd: number
  overageBilledUsd: number
  stripeMeteredItemId?: string
  anniversaryDay: number
  lastDailyReset: Date
  lastMonthlyReset: Date
  createdAt: Date
  updatedAt: Date
}

export interface UsageWalletCreateInput {
  workspaceId: string
  monthlyIncludedUsd?: number
  dailyIncludedUsd?: number
  monthlyIncludedAllocationUsd?: number
  dailyUsedThisMonthUsd?: number
  overageEnabled?: boolean
  overageHardLimitUsd?: number
  overageAccumulatedUsd?: number
  overageBilledUsd?: number
  stripeMeteredItemId?: string
  anniversaryDay: number
  lastDailyReset: Date
  lastMonthlyReset: Date
}

export interface UsageWalletUpdateInput {
  workspaceId?: string
  monthlyIncludedUsd?: number
  dailyIncludedUsd?: number
  monthlyIncludedAllocationUsd?: number
  dailyUsedThisMonthUsd?: number
  overageEnabled?: boolean
  overageHardLimitUsd?: number
  overageAccumulatedUsd?: number
  overageBilledUsd?: number
  stripeMeteredItemId?: string
  anniversaryDay?: number
  lastDailyReset?: Date
  lastMonthlyReset?: Date
}
