// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated User Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type UserRole = 'user' | 'super_admin'

export interface UserType {
  id: string
  name?: string
  email: string
  emailVerified: boolean
  image?: string
  role: UserRole
  onboardingCompleted: boolean
  createdAt: Date
  updatedAt: Date
}

export interface UserCreateInput {
  name?: string
  email: string
  emailVerified?: boolean
  image?: string
  role?: UserRole
  onboardingCompleted?: boolean
}

export interface UserUpdateInput {
  name?: string
  email?: string
  emailVerified?: boolean
  image?: string
  role?: UserRole
  onboardingCompleted?: boolean
}
