// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated WorkspaceGrant MST Model
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"

// Referenced models (use types.late() to avoid circular imports)
import { WorkspaceModel } from "./workspace.model"

// ============================================================================
// WorkspaceGrant Model
// ============================================================================

export const WorkspaceGrantModel = types
  .model("WorkspaceGrant", {
    id: types.identifier,
    workspaceId: types.string,
    freeSeats: types.optional(types.number, 0),
    monthlyIncludedUsd: types.optional(types.number, 0),
    startsAt: types.optional(types.number, 0),
    expiresAt: types.optional(types.number, 0),
    note: types.optional(types.string, ""),
    createdByUserId: types.optional(types.string, ""),
    createdAt: types.optional(types.number, 0),
    updatedAt: types.number,
    workspace: types.safeReference(types.late(() => WorkspaceModel)),
  })
  .views(self => ({
    /** Check if this is a new/unsaved entity */
    get isNew(): boolean {
      return self.id.startsWith("temp-")
    },
  }))
  .actions(self => ({
    /** Update entity fields */
    update(changes: Partial<SnapshotIn<typeof self>>) {
      Object.assign(self, changes)
    },
  }))

// Type exports
export interface IWorkspaceGrant extends Instance<typeof WorkspaceGrantModel> {}
export interface IWorkspaceGrantSnapshotIn extends SnapshotIn<typeof WorkspaceGrantModel> {}
export interface IWorkspaceGrantSnapshotOut extends SnapshotOut<typeof WorkspaceGrantModel> {}
