// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Workspace Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export type InstanceSize = 'micro' | 'small' | 'medium' | 'large' | 'xlarge'

export interface WorkspaceType {
  id: string
  name: string
  slug: string
  description?: string
  ssoSettings?: Record<string, unknown>
  instanceSize: InstanceSize
  composioScope: string
  homeRegion?: string
  parentWorkspaceId?: string
  createdAt: Date
  updatedAt: Date
}

export interface WorkspaceCreateInput {
  name: string
  slug: string
  description?: string
  ssoSettings?: Record<string, unknown>
  instanceSize?: InstanceSize
  composioScope?: string
  homeRegion?: string
  parentWorkspaceId?: string
}

export interface WorkspaceUpdateInput {
  name?: string
  slug?: string
  description?: string
  ssoSettings?: Record<string, unknown>
  instanceSize?: InstanceSize
  composioScope?: string
  homeRegion?: string
  parentWorkspaceId?: string
}
