/**
 * Auto-generated Workspace Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface WorkspaceType {
  id: string
  name: string
  slug: string
  description?: string
  ssoSettings?: Record<string, unknown>
  createdAt: Date
  updatedAt: Date
}

export interface WorkspaceCreateInput {
  name: string
  slug: string
  description?: string
  ssoSettings?: Record<string, unknown>
}

export interface WorkspaceUpdateInput {
  name?: string
  slug?: string
  description?: string
  ssoSettings?: Record<string, unknown>
}
