// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated WorkspaceGrant Types
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

export interface WorkspaceGrantType {
  id: string
  workspaceId: string
  freeSeats: number
  monthlyIncludedUsd: number
  startsAt: Date
  expiresAt?: Date
  note?: string
  createdByUserId?: string
  createdAt: Date
  updatedAt: Date
}

export interface WorkspaceGrantCreateInput {
  workspaceId: string
  freeSeats?: number
  monthlyIncludedUsd?: number
  startsAt?: Date
  expiresAt?: Date
  note?: string
  createdByUserId?: string
}

export interface WorkspaceGrantUpdateInput {
  workspaceId?: string
  freeSeats?: number
  monthlyIncludedUsd?: number
  startsAt?: Date
  expiresAt?: Date
  note?: string
  createdByUserId?: string
}
