-- Migration: add_custom_domains
-- Generated: 2026-06-05T01:05:02.341Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_custom_domains`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- then trimmed to the new `custom_domains` table only: the generator also
-- re-emitted RedefineTable churn for 8 tables (agent_configs, agent_eval_sets,
-- budget_alerts, eval_runs, model_experiments, subagent_model_overrides,
-- usage_wallets, workspace_grants) plus a signup_attributions index, all of
-- which are PRE-EXISTING drift already on the ACCEPTED_DRIFT allow-list in
-- scripts/check-desktop-schema-drift.ts. Including that unrelated churn here
-- would rewrite those tables on every desktop upgrade for no reason, so it is
-- intentionally omitted.

-- CreateTable
CREATE TABLE "custom_domains" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "cfCustomHostnameId" TEXT,
    "sslStatus" TEXT,
    "lastError" TEXT,
    "verifiedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "custom_domains_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "custom_domains_hostname_key" ON "custom_domains"("hostname");

-- CreateIndex
CREATE INDEX "custom_domains_projectId_idx" ON "custom_domains"("projectId");
