#!/usr/bin/env python3
"""
Schema-Driven Type Generator

Generates Pydantic v2 models from schema.json, establishing tight coupling
between wavesmith schema and Python parser code. When schema evolves,
regenerating types will surface drift through type errors.

Usage:
    python scripts/build_types.py [--dry-run]

    --dry-run: Show what would be generated without writing files
"""

import json
import hashlib
import subprocess
import sys
from pathlib import Path
from datetime import datetime, timezone


# Paths (relative to script location)
SCRIPT_DIR = Path(__file__).parent
PACKAGE_ROOT = SCRIPT_DIR.parent
SCHEMA_PATH = PACKAGE_ROOT / "schema.json"
GENERATED_DIR = PACKAGE_ROOT / "generated"
OUTPUT_PATH = GENERATED_DIR / "models.py"

# Try to find datamodel-codegen in package root venv
VENV_BIN = PACKAGE_ROOT / ".venv" / "bin" / "datamodel-codegen"
DATAMODEL_CODEGEN = str(VENV_BIN) if VENV_BIN.exists() else "datamodel-codegen"


def compute_schema_hash(schema_path: Path) -> str:
    """Compute SHA256 hash of schema file for change detection."""
    with open(schema_path, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()[:12]


def load_schema_metadata(schema_path: Path) -> dict:
    """Extract metadata from schema for documentation."""
    with open(schema_path, 'r') as f:
        schema = json.load(f)

    # Count models
    model_count = len(schema.get('models', {}))

    # Extract schema name/version if available
    schema_name = schema.get('name', 'unknown')
    schema_id = schema.get('id', 'unknown')

    return {
        'name': schema_name,
        'id': schema_id,
        'model_count': model_count,
        'file_size': schema_path.stat().st_size
    }


def generate_models(schema_path: Path, output_path: Path, dry_run: bool = False) -> bool:
    """
    Generate Pydantic models using datamodel-code-generator.

    Returns:
        True if generation succeeded, False otherwise
    """
    if dry_run:
        print(f"[DRY RUN] Would generate models from {schema_path}")
        print(f"[DRY RUN] Would output to {output_path}")
        return True

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build datamodel-codegen command
    cmd = [
        DATAMODEL_CODEGEN,
        '--input', str(schema_path),
        '--output', str(output_path),
        '--input-file-type', 'jsonschema',
        '--output-model-type', 'pydantic_v2.BaseModel',
        '--field-constraints',              # Preserve min/max, enums
        '--use-annotated',                  # Pydantic v2.5+ style
        '--snake-case-field',               # Python naming convention
        '--use-standard-collections',       # list[T] not List[T]
        '--use-union-operator',             # T | None not Optional[T]
        '--target-python-version', '3.11',
        '--disable-timestamp',              # Deterministic output
        '--reuse-model',                    # Avoid duplicate models
        '--allow-population-by-field-name', # Accept both snake_case and camelCase
    ]

    print(f"Generating Pydantic models...")
    print(f"  Source: {schema_path}")
    print(f"  Output: {output_path}")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        if result.stdout:
            print("  Generator output:", result.stdout.strip())

        return True

    except subprocess.CalledProcessError as e:
        print(f"❌ Generation failed!")
        print(f"  Error: {e.stderr}")
        return False
    except FileNotFoundError:
        print(f"❌ datamodel-code-generator not found!")
        print(f"  Install with: pip install datamodel-code-generator")
        return False


def add_header_to_generated_file(output_path: Path, schema_hash: str, metadata: dict):
    """Add informative header comment to generated models file."""

    header = f'''"""
AUTO-GENERATED Pydantic Models from Wavesmith Schema

⚠️  DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN ⚠️

Source: schema.json (hash: {schema_hash})
Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}
Schema: {metadata['name']} (id: {metadata['id']})
Models: {metadata['model_count']} entities

To regenerate after schema changes:
    python scripts/build_types.py

When schema evolves:
    1. Edit schema.json
    2. Run: python scripts/build_types.py
    3. Fix type errors in parser code
    4. Commit both schema.json and generated/models.py
"""

'''

    # Read existing generated content
    with open(output_path, 'r') as f:
        generated_content = f.read()

    # Prepend header
    with open(output_path, 'w') as f:
        f.write(header)
        f.write(generated_content)


def create_init_file(generated_dir: Path):
    """Create __init__.py for generated package."""
    init_path = generated_dir / "__init__.py"

    init_content = '''"""
Generated Pydantic models from wavesmith schema.

Import models from this package:
    from generated.models import Template, Section, Rule, Option
"""

from .models import *

__all__ = ['Template', 'Section', 'Rule', 'Option', 'PwSectionContext']
'''

    with open(init_path, 'w') as f:
        f.write(init_content)


def main():
    """Main entry point for type generation."""
    dry_run = '--dry-run' in sys.argv

    print("=" * 60)
    print("Schema-Driven Type Generator")
    print("=" * 60)

    # Validate schema exists
    if not SCHEMA_PATH.exists():
        print(f"❌ Schema not found: {SCHEMA_PATH}")
        sys.exit(1)

    # Compute schema hash for tracking
    schema_hash = compute_schema_hash(SCHEMA_PATH)
    metadata = load_schema_metadata(SCHEMA_PATH)

    print(f"\n📄 Schema: {SCHEMA_PATH.name}")
    print(f"   Hash: {schema_hash}")
    print(f"   Name: {metadata['name']}")
    print(f"   Models: {metadata['model_count']}")
    print(f"   Size: {metadata['file_size']:,} bytes")

    # Generate models
    print(f"\n🔧 Generating Pydantic models...")
    success = generate_models(SCHEMA_PATH, OUTPUT_PATH, dry_run=dry_run)

    if not success:
        sys.exit(1)

    if not dry_run:
        # Add header with metadata
        add_header_to_generated_file(OUTPUT_PATH, schema_hash, metadata)

        # Create __init__.py
        create_init_file(GENERATED_DIR)

        print(f"\n✅ Models generated successfully!")
        print(f"   Output: {OUTPUT_PATH}")
        print(f"   Lines: {len(OUTPUT_PATH.read_text().splitlines())}")

    print("\n" + "=" * 60)
    print("Next steps:")
    print("  1. Review generated/models.py")
    print("  2. Import in parser: from generated.models import Template")
    print("  3. Run mypy to verify type safety")
    print("=" * 60)


if __name__ == '__main__':
    main()
