-- Migration: add_chat_session_active_turn
-- Generated: 2026-09-23T05:26:05.215Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_chat_session_active_turn`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "chat_sessions" ADD COLUMN "activeTurnId" TEXT;
ALTER TABLE "chat_sessions" ADD COLUMN "activeTurnStartedAt" DATETIME;
ALTER TABLE "chat_sessions" ADD COLUMN "activeTurnHeartbeatAt" DATETIME;

-- CreateIndex
CREATE INDEX "chat_sessions_activeTurnHeartbeatAt_idx" ON "chat_sessions"("activeTurnHeartbeatAt");

