apiVersion: v1
kind: Namespace
metadata:
  name: shogo-system
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: shogo-workspaces
  labels:
    environment: production
