-- Migration: add_event_identity
-- Generated: 2026-10-05T01:50:48.559Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_event_identity`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "workspace_events" ADD COLUMN "actor" TEXT;

-- CreateTable
CREATE TABLE "user_identity_links" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "email" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "user_identity_links_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_event_subscriptions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "eventType" TEXT NOT NULL,
    "eventVersion" INTEGER NOT NULL DEFAULT 1,
    "filter" TEXT,
    "ownerUserId" TEXT,
    "ownerKind" TEXT NOT NULL DEFAULT 'user',
    "installId" TEXT,
    "source" TEXT NOT NULL DEFAULT 'shogo',
    "composioTriggerSlug" TEXT,
    "composioTriggerId" TEXT,
    "composioConnectedAccountId" TEXT,
    "composioEntityId" TEXT,
    "triggerConfig" TEXT,
    "actsAs" TEXT NOT NULL DEFAULT 'subscriber',
    "actorIdPath" TEXT,
    "actorEmailPath" TEXT,
    "trustActorEmail" BOOLEAN NOT NULL DEFAULT false,
    "target" TEXT NOT NULL DEFAULT 'agent',
    "targetProjectId" TEXT,
    "targetMode" TEXT,
    "prompt" TEXT,
    "notifyConversationId" TEXT,
    "notifyThreadRootId" TEXT,
    "webhookUrl" TEXT,
    "webhookSecret" TEXT,
    "chatSessionId" TEXT,
    "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
    "lastDeliveredAt" DATETIME,
    "lastError" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "event_subscriptions_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_event_subscriptions" ("chatSessionId", "composioConnectedAccountId", "composioEntityId", "composioTriggerId", "composioTriggerSlug", "consecutiveFailures", "createdAt", "enabled", "eventType", "eventVersion", "filter", "id", "installId", "lastDeliveredAt", "lastError", "name", "notifyConversationId", "notifyThreadRootId", "ownerKind", "ownerUserId", "prompt", "source", "target", "targetMode", "targetProjectId", "triggerConfig", "updatedAt", "webhookSecret", "webhookUrl", "workspaceId") SELECT "chatSessionId", "composioConnectedAccountId", "composioEntityId", "composioTriggerId", "composioTriggerSlug", "consecutiveFailures", "createdAt", "enabled", "eventType", "eventVersion", "filter", "id", "installId", "lastDeliveredAt", "lastError", "name", "notifyConversationId", "notifyThreadRootId", "ownerKind", "ownerUserId", "prompt", "source", "target", "targetMode", "targetProjectId", "triggerConfig", "updatedAt", "webhookSecret", "webhookUrl", "workspaceId" FROM "event_subscriptions";
DROP TABLE "event_subscriptions";
ALTER TABLE "new_event_subscriptions" RENAME TO "event_subscriptions";
CREATE UNIQUE INDEX "event_subscriptions_composioTriggerId_key" ON "event_subscriptions"("composioTriggerId");
CREATE INDEX "event_subscriptions_workspaceId_enabled_eventType_idx" ON "event_subscriptions"("workspaceId", "enabled", "eventType");
CREATE INDEX "event_subscriptions_ownerUserId_idx" ON "event_subscriptions"("ownerUserId");
CREATE INDEX "event_subscriptions_installId_idx" ON "event_subscriptions"("installId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "user_identity_links_source_externalId_idx" ON "user_identity_links"("source", "externalId");

-- CreateIndex
CREATE UNIQUE INDEX "user_identity_links_userId_source_externalId_key" ON "user_identity_links"("userId", "source", "externalId");

