-- Migration: add_affiliate_per_video_cap
-- Generated by `bun run db:migrate:desktop --name add_affiliate_per_video_cap`.
-- Hand-trimmed to the two additive changes for this PR:
--   1. a per-creator per-video lifetime earnings cap on `affiliates`
--   2. a `paidCents` dollar high-water mark on `affiliate_posts`
-- The generator also emitted RedefineTables / RedefineIndex churn for
-- unrelated tables already in the desktop schema's ACCEPTED_DRIFT set
-- (agent_configs, eval_runs, signup_attributions, etc.) plus a full
-- table rebuild of `affiliate_posts` purely to reorder the new column;
-- those are intentionally replaced with plain additive ALTERs so this
-- migration replays cleanly. See the content-CPM migration for the same
-- trimming rationale.

-- AlterTable
ALTER TABLE "affiliates" ADD COLUMN "contentPerVideoCapCents" INTEGER;

-- AlterTable
ALTER TABLE "affiliate_posts" ADD COLUMN "paidCents" INTEGER NOT NULL DEFAULT 0;
