-- Migration: add_chat_installations
-- Generated: 2026-09-30T17:52:48.865Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_chat_installations`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- CreateTable
CREATE TABLE "chat_installations" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "externalTenantId" TEXT NOT NULL,
    "tenantName" TEXT,
    "botUserId" TEXT,
    "tokensEncrypted" TEXT,
    "config" TEXT,
    "installedByUserId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "chat_installations_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "chat_identity_links" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "provider" TEXT NOT NULL,
    "externalTenantId" TEXT NOT NULL,
    "externalUserId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "displayName" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "chat_identity_links_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_conversations" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'public',
    "name" TEXT,
    "slug" TEXT,
    "topic" TEXT,
    "dmKey" TEXT,
    "createdById" TEXT,
    "lastSeq" INTEGER NOT NULL DEFAULT 0,
    "lastMessageAt" DATETIME,
    "archivedAt" DATETIME,
    "provider" TEXT NOT NULL DEFAULT 'shogo',
    "externalId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "conversations_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_conversations" ("archivedAt", "createdAt", "createdById", "dmKey", "id", "kind", "lastMessageAt", "lastSeq", "name", "slug", "topic", "updatedAt", "workspaceId") SELECT "archivedAt", "createdAt", "createdById", "dmKey", "id", "kind", "lastMessageAt", "lastSeq", "name", "slug", "topic", "updatedAt", "workspaceId" FROM "conversations";
DROP TABLE "conversations";
ALTER TABLE "new_conversations" RENAME TO "conversations";
CREATE INDEX "conversations_workspaceId_kind_idx" ON "conversations"("workspaceId", "kind");
CREATE UNIQUE INDEX "conversations_workspaceId_slug_key" ON "conversations"("workspaceId", "slug");
CREATE UNIQUE INDEX "conversations_workspaceId_dmKey_key" ON "conversations"("workspaceId", "dmKey");
CREATE UNIQUE INDEX "conversations_workspaceId_provider_externalId_key" ON "conversations"("workspaceId", "provider", "externalId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "chat_installations_workspaceId_provider_key" ON "chat_installations"("workspaceId", "provider");

-- CreateIndex
CREATE UNIQUE INDEX "chat_installations_provider_externalTenantId_key" ON "chat_installations"("provider", "externalTenantId");

-- CreateIndex
CREATE INDEX "chat_identity_links_userId_idx" ON "chat_identity_links"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "chat_identity_links_provider_externalTenantId_externalUserId_key" ON "chat_identity_links"("provider", "externalTenantId", "externalUserId");

-- Backfill existing Slack installs and account links into the provider-generic tables.
-- The Slack bot token is already encrypted; it is carried over as-is and read
-- as a bare token by the installation loader.
INSERT OR IGNORE INTO "chat_installations" ("id", "workspaceId", "provider", "externalTenantId", "tenantName", "botUserId", "tokensEncrypted", "config", "createdAt", "updatedAt")
SELECT 'slack-' || s."id", s."workspaceId", 'slack', s."slackTeamId", s."slackTeamName", s."botUserId", s."botAccessTokenEncrypted",
       json_object('defaultProjectId', s."defaultProjectId"), s."createdAt", s."updatedAt"
FROM "slack_workspace_installations" s;

INSERT OR IGNORE INTO "chat_identity_links" ("id", "provider", "externalTenantId", "externalUserId", "userId", "createdAt", "updatedAt")
SELECT 'slack-' || l."id", 'slack', l."slackTeamId", l."slackUserId", l."shogoUserId", l."createdAt", l."updatedAt"
FROM "slack_user_links" l;

