-- Migration: proxy_capture_training_data
-- Generated: 2026-09-26T04:57:43.533Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name proxy_capture_training_data`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_workspaces" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'team',
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "ssoSettings" TEXT,
    "instanceSize" TEXT NOT NULL DEFAULT 'micro',
    "composioScope" TEXT NOT NULL DEFAULT 'workspace',
    "trainingDataMode" TEXT NOT NULL DEFAULT 'default',
    "parentWorkspaceId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "workspaces_parentWorkspaceId_fkey" FOREIGN KEY ("parentWorkspaceId") REFERENCES "workspaces" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_workspaces" ("composioScope", "createdAt", "description", "id", "instanceSize", "kind", "name", "parentWorkspaceId", "slug", "ssoSettings", "updatedAt") SELECT "composioScope", "createdAt", "description", "id", "instanceSize", "kind", "name", "parentWorkspaceId", "slug", "ssoSettings", "updatedAt" FROM "workspaces";
DROP TABLE "workspaces";
ALTER TABLE "new_workspaces" RENAME TO "workspaces";
CREATE UNIQUE INDEX "workspaces_slug_key" ON "workspaces"("slug");
CREATE INDEX "workspaces_parentWorkspaceId_idx" ON "workspaces"("parentWorkspaceId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

CREATE TABLE "proxy_turns" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "firstAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "projectId" TEXT,
    "userId" TEXT,
    "chatSessionId" TEXT,
    "turnKey" TEXT NOT NULL,
    "resolvedModel" TEXT,
    "llmCalls" INTEGER NOT NULL DEFAULT 0,
    "inputTokens" INTEGER NOT NULL DEFAULT 0,
    "outputTokens" INTEGER NOT NULL DEFAULT 0,
    "cachedInputTokens" INTEGER NOT NULL DEFAULT 0,
    "cacheWriteTokens" INTEGER NOT NULL DEFAULT 0,
    "reasoningTokens" INTEGER NOT NULL DEFAULT 0,
    "errorCount" INTEGER NOT NULL DEFAULT 0,
    "userText" TEXT,
    "assistantText" TEXT,
    "toolNames" TEXT NOT NULL DEFAULT '[]',
    "archivePrefix" TEXT,
    "feedback" TEXT,
    "revertedAt" DATETIME,
    "hadError" BOOLEAN NOT NULL DEFAULT false,
    "truncated" BOOLEAN NOT NULL DEFAULT false,
    "userFollowupKind" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "proxy_turns_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "proxy_turns_workspaceId_turnKey_key" ON "proxy_turns"("workspaceId", "turnKey");
CREATE INDEX "proxy_turns_workspaceId_lastAt_idx" ON "proxy_turns"("workspaceId", "lastAt");
CREATE INDEX "proxy_turns_chatSessionId_lastAt_idx" ON "proxy_turns"("chatSessionId", "lastAt");
CREATE INDEX "proxy_turns_source_idx" ON "proxy_turns"("source");
