-- Migration: add_message_external_thread_ref
-- Generated: 2026-09-30T18:07:59.668Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_message_external_thread_ref`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "conversation_messages" ADD COLUMN "externalThreadRef" TEXT;

-- CreateIndex
CREATE INDEX "conversation_messages_conversationId_externalThreadRef_idx" ON "conversation_messages"("conversationId", "externalThreadRef");
