-- Migration: add_agent_task_dispatch_indexes
-- Generated: 2026-09-18T23:47:42.440Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_agent_task_dispatch_indexes`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- CreateIndex
CREATE INDEX "agent_tasks_status_dueAt_idx" ON "agent_tasks"("status", "dueAt");

-- CreateIndex
CREATE INDEX "agent_tasks_status_updatedAt_idx" ON "agent_tasks"("status", "updatedAt");


