# =============================================================================
# install-shogo-ai — Cloudflare Workers backing install.shogo.ai +
# releases.shogo.ai
# =============================================================================
# Two Workers:
#
#   install.shogo.ai
#     - GET /            -> packages/shogo-worker/install.sh
#     - GET /install.sh  -> same
#     - GET /ps          -> packages/shogo-worker/install.ps1
#     - GET /install.ps1 -> same
#     Scripts are loaded via terraform's `file()` so the canonical text
#     lives at packages/shogo-worker/install.{sh,ps1}; a `terraform
#     apply` is the only ship step.
#
#   releases.shogo.ai
#     - GET /cli/<channel>/shogo-<target>.<ext>(.sha256)?
#         -> 302 to the latest matching v* GitHub Release asset
#     Worker source lives in scripts/releases-worker.js.tftpl.
#
# DNS: both subdomains are proxied A records pointing at a documentation
# IP (192.0.2.1 / RFC 5737). All traffic is intercepted by the matching
# worker_route, so the origin IP is never reached — same trick as the
# publish-hosting-oci wildcard record (see that module for the full
# rationale).
#
# Cloudflare API token scopes required for `terraform apply`:
#   - Workers Scripts:Edit
#   - Workers Routes:Edit
#   - Zone DNS:Edit  (on the shogo.ai zone)
# =============================================================================

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

locals {
  # `file()` reads at plan time, so updating install.sh / install.ps1
  # and re-applying ships the new script. jsonencode() is the safe way
  # to inline arbitrary text inside the Worker JS literal — handles
  # quotes, backticks, backslashes, newlines, and control chars without
  # us having to babysit escaping.
  install_sh  = file("${path.module}/../../../packages/shogo-worker/install.sh")
  install_ps1 = file("${path.module}/../../../packages/shogo-worker/install.ps1")

  install_worker_name  = "shogo-install-host-${var.environment}"
  releases_worker_name = "shogo-releases-resolver-${var.environment}"
}

# -----------------------------------------------------------------------------
# install.shogo.ai
# -----------------------------------------------------------------------------

resource "cloudflare_worker_script" "install_host" {
  account_id = var.cloudflare_account_id
  name       = local.install_worker_name
  module     = true

  content = <<-JS
    // Auto-generated by terraform/modules/install-shogo-ai/main.tf.
    // Source of truth for the script bodies:
    //   packages/shogo-worker/install.sh
    //   packages/shogo-worker/install.ps1
    const INSTALL_SH  = ${jsonencode(local.install_sh)};
    const INSTALL_PS1 = ${jsonencode(local.install_ps1)};

    const SH_HEADERS = {
      'content-type': 'text/x-shellscript; charset=utf-8',
      'cache-control': 'public, max-age=300, s-maxage=300',
    };
    const PS1_HEADERS = {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=300, s-maxage=300',
    };

    export default {
      async fetch(request) {
        if (request.method !== 'GET' && request.method !== 'HEAD') {
          return new Response('Method Not Allowed', {
            status: 405,
            headers: { Allow: 'GET, HEAD' },
          });
        }
        const { pathname } = new URL(request.url);
        if (pathname === '/' || pathname === '/install.sh') {
          return new Response(INSTALL_SH, { headers: SH_HEADERS });
        }
        if (pathname === '/ps' || pathname === '/install.ps1') {
          return new Response(INSTALL_PS1, { headers: PS1_HEADERS });
        }
        return new Response('Not Found', { status: 404 });
      },
    };
  JS
}

resource "cloudflare_record" "install" {
  zone_id = var.cloudflare_zone_id
  name    = "install"

  # See publish-hosting-oci/main.tf lines 189-199 for the rationale —
  # cloudflare rejects proxied records that target reserved CIDRs, and
  # the Worker route below intercepts every request before the proxy
  # ever fetches this origin, so 192.0.2.1 (RFC 5737 docs range) just
  # needs to be a syntactically valid A record CF will accept.
  content         = "192.0.2.1"
  type            = "A"
  proxied         = true
  allow_overwrite = true
}

resource "cloudflare_worker_route" "install" {
  zone_id     = var.cloudflare_zone_id
  pattern     = "install.${var.domain}/*"
  script_name = cloudflare_worker_script.install_host.name
}
