// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Admin Routes Generator
 *
 * Generates a single admin-routes file with unrestricted CRUD for ALL models.
 * Features per model:
 *   - LIST: pagination, text search across string fields, sorting, _count on relations
 *   - GET:  full record with relations included
 *   - PATCH: update any scalar field
 *   - DELETE: hard delete
 *
 * Middleware is injected via config at mount time, keeping the generated code
 * decoupled from any specific auth strategy.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { toCamelCase, getIdField, getScalarFields, getRelationFields } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface AdminRoutesGeneratorConfig {
  /** File extension: 'ts' | 'tsx' (default: 'ts') */
  fileExtension?: 'ts' | 'tsx'
}

export interface GeneratedAdminRoutesFile {
  fileName: string
  code: string
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to route path (kebab-case, plural)
 */
function toRoutePath(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  if (kebab.endsWith('y')) return kebab.slice(0, -1) + 'ies'
  if (kebab.endsWith('s') || kebab.endsWith('x') || kebab.endsWith('ch') || kebab.endsWith('sh')) {
    return kebab + 'es'
  }
  return kebab + 's'
}

/**
 * Get string fields that can be searched
 */
function getSearchableFields(model: PrismaModel): PrismaField[] {
  return getScalarFields(model).filter(f => f.type === 'String' && !f.isId)
}

/**
 * Get list-type relation fields (for _count)
 */
function getListRelations(model: PrismaModel): PrismaField[] {
  return getRelationFields(model).filter(f => f.isList)
}

/**
 * Get single relation fields (for include on GET)
 */
function getSingleRelations(model: PrismaModel): PrismaField[] {
  return getRelationFields(model).filter(f => !f.isList)
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate admin routes for all models
 */
export function generateAdminRoutes(
  models: PrismaModel[],
  config: AdminRoutesGeneratorConfig = {}
): GeneratedAdminRoutesFile {
  const ext = config.fileExtension || 'ts'
  const fileName = `admin-routes.${ext}`

  // Filter to models with @id
  const routeModels = models.filter(m => getIdField(m))

  const lines: string[] = [
    '/**',
    ' * Auto-generated Admin Routes',
    ' *',
    ' * Unrestricted CRUD for all models with pagination, search, and sorting.',
    ' * Protect these routes by passing middleware in the config.',
    ' *',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { Hono } from "hono"',
    '',
    'export interface AdminRoutesConfig {',
    '  /** Prisma client instance */',
    '  prisma: any',
    '  /** Middleware to apply to all admin routes (e.g. auth, role check) */',
    '  middleware?: Array<(c: any, next: () => Promise<void>) => Promise<any>>',
    '}',
    '',
    '/**',
    ' * Create admin CRUD routes for all models.',
    ' *',
    ' * Usage:',
    ' * ```ts',
    ' * app.route("/api/admin", createAdminRoutes({',
    ' *   prisma,',
    ' *   middleware: [authMiddleware, requireAuth, requireSuperAdmin],',
    ' * }))',
    ' * ```',
    ' */',
    'export function createAdminRoutes(config: AdminRoutesConfig): Hono {',
    '  const { prisma, middleware = [] } = config',
    '  const router = new Hono()',
    '',
    '  // Apply middleware stack',
    '  for (const mw of middleware) {',
    '    router.use("*", mw)',
    '  }',
    '',
  ]

  // Generate CRUD for each model
  for (const model of routeModels) {
    const modelName = model.name
    const modelLower = toCamelCase(modelName)
    const routePath = toRoutePath(modelName)
    const searchFields = getSearchableFields(model)
    const listRelations = getListRelations(model)
    const singleRelations = getSingleRelations(model)
    const scalarFields = getScalarFields(model)

    lines.push(`  // ========== ${modelName} ==========`)
    lines.push('')

    // LIST with pagination, search, _count
    lines.push(`  // LIST ${routePath}`)
    lines.push(`  router.get("/${routePath}", async (c) => {`)
    lines.push('    try {')
    lines.push('      const url = new URL(c.req.url)')
    lines.push('      const page = Math.max(1, parseInt(url.searchParams.get("page") || "1"))')
    lines.push('      const limit = Math.min(Math.max(1, parseInt(url.searchParams.get("limit") || "20")), 100)')
    lines.push('      const search = url.searchParams.get("search") || ""')
    lines.push('      const orderBy = url.searchParams.get("orderBy") || "createdAt"')
    lines.push('      const order = (url.searchParams.get("order") || "desc") as "asc" | "desc"')
    lines.push('')

    // Build search where clause
    if (searchFields.length > 0) {
      lines.push('      let where: any = {}')
      lines.push('      if (search) {')
      lines.push('        where = {')
      lines.push('          OR: [')
      for (const field of searchFields) {
        lines.push(`            { ${field.name}: { contains: search, mode: "insensitive" } },`)
      }
      lines.push('          ]')
      lines.push('        }')
      lines.push('      }')
    } else {
      lines.push('      const where: any = {}')
    }

    // Also support query-param filtering for non-reserved keys
    lines.push('')
    lines.push('      // Additional query param filters')
    lines.push('      const reserved = new Set(["page", "limit", "search", "orderBy", "order"])')
    lines.push('      for (const [key, value] of url.searchParams.entries()) {')
    lines.push('        if (!reserved.has(key) && value !== "") {')
    lines.push('          if (value === "true") where[key] = true')
    lines.push('          else if (value === "false") where[key] = false')
    lines.push('          else where[key] = value')
    lines.push('        }')
    lines.push('      }')
    lines.push('')

    // Build _count select for list relations
    const countSelect: string[] = listRelations.map(r => `${r.name}: true`)

    lines.push('      const [items, total] = await Promise.all([')
    lines.push(`        prisma.${modelLower}.findMany({`)
    lines.push('          where,')
    lines.push('          orderBy: { [orderBy]: order },')
    lines.push('          skip: (page - 1) * limit,')
    lines.push('          take: limit,')
    if (countSelect.length > 0) {
      lines.push('          include: {')
      lines.push(`            _count: { select: { ${countSelect.join(', ')} } },`)
      lines.push('          },')
    }
    lines.push('        }),')
    lines.push(`        prisma.${modelLower}.count({ where }),`)
    lines.push('      ])')
    lines.push('')
    // Use camelCase plural for the data key (routePath is kebab-case for URLs only)
    const dataKey = modelLower + 's'
    lines.push(`      return c.json({ ok: true, data: { ${dataKey}: items, total, page, limit } })`)
    lines.push('    } catch (error: any) {')
    lines.push(`      console.error("[Admin] List ${modelName} error:", error)`)
    lines.push('      return c.json({ error: { code: "list_failed", message: error.message } }, 500)')
    lines.push('    }')
    lines.push('  })')
    lines.push('')

    // GET by ID with relations
    lines.push(`  // GET ${routePath}/:id`)
    lines.push(`  router.get("/${routePath}/:id", async (c) => {`)
    lines.push('    try {')
    lines.push('      const id = c.req.param("id")')

    // Build include for single + list relations (limited)
    const hasRelations = singleRelations.length > 0 || listRelations.length > 0
    if (hasRelations) {
      lines.push(`      const item = await prisma.${modelLower}.findUnique({`)
      lines.push('        where: { id },')
      lines.push('        include: {')
      for (const rel of singleRelations) {
        lines.push(`          ${rel.name}: true,`)
      }
      for (const rel of listRelations) {
        lines.push(`          ${rel.name}: { take: 50 },`)
      }
      lines.push('        },')
      lines.push('      })')
    } else {
      lines.push(`      const item = await prisma.${modelLower}.findUnique({`)
      lines.push('        where: { id },')
      lines.push('      })')
    }

    lines.push('')
    lines.push('      if (!item) {')
    lines.push(`        return c.json({ error: { code: "not_found", message: "${modelName} not found" } }, 404)`)
    lines.push('      }')
    lines.push('')
    lines.push('      return c.json({ ok: true, data: item })')
    lines.push('    } catch (error: any) {')
    lines.push(`      console.error("[Admin] Get ${modelName} error:", error)`)
    lines.push('      return c.json({ error: { code: "get_failed", message: error.message } }, 500)')
    lines.push('    }')
    lines.push('  })')
    lines.push('')

    // PATCH
    lines.push(`  // PATCH ${routePath}/:id`)
    lines.push(`  router.patch("/${routePath}/:id", async (c) => {`)
    lines.push('    try {')
    lines.push('      const id = c.req.param("id")')
    lines.push('      const body = await c.req.json()')
    lines.push('')
    lines.push(`      const item = await prisma.${modelLower}.update({`)
    lines.push('        where: { id },')
    lines.push('        data: body,')
    lines.push('      })')
    lines.push('')
    lines.push('      return c.json({ ok: true, data: item })')
    lines.push('    } catch (error: any) {')
    lines.push(`      console.error("[Admin] Update ${modelName} error:", error)`)
    lines.push('      return c.json({ error: { code: "update_failed", message: error.message } }, 500)')
    lines.push('    }')
    lines.push('  })')
    lines.push('')

    // DELETE
    lines.push(`  // DELETE ${routePath}/:id`)
    lines.push(`  router.delete("/${routePath}/:id", async (c) => {`)
    lines.push('    try {')
    lines.push('      const id = c.req.param("id")')
    lines.push(`      await prisma.${modelLower}.delete({ where: { id } })`)
    lines.push('      return c.json({ ok: true })')
    lines.push('    } catch (error: any) {')
    lines.push(`      console.error("[Admin] Delete ${modelName} error:", error)`)
    lines.push('      return c.json({ error: { code: "delete_failed", message: error.message } }, 500)')
    lines.push('    }')
    lines.push('  })')
    lines.push('')
  }

  // Stats endpoint - aggregate counts for all models
  lines.push('  // ========== Stats ==========')
  lines.push('')
  lines.push('  // GET /stats - aggregate counts for all models')
  lines.push('  router.get("/stats", async (c) => {')
  lines.push('    try {')
  lines.push('      const [')
  for (let i = 0; i < routeModels.length; i++) {
    const modelLower = toCamelCase(routeModels[i].name)
    lines.push(`        ${modelLower}Count${i < routeModels.length - 1 ? ',' : ''}`)
  }
  lines.push('      ] = await Promise.all([')
  for (const model of routeModels) {
    const modelLower = toCamelCase(model.name)
    lines.push(`        prisma.${modelLower}.count(),`)
  }
  lines.push('      ])')
  lines.push('')
  lines.push('      return c.json({')
  lines.push('        ok: true,')
  lines.push('        data: {')
  for (const model of routeModels) {
    const modelLower = toCamelCase(model.name)
    lines.push(`          ${modelLower}: ${modelLower}Count,`)
  }
  lines.push('        }')
  lines.push('      })')
  lines.push('    } catch (error: any) {')
  lines.push('      console.error("[Admin] Stats error:", error)')
  lines.push('      return c.json({ error: { code: "stats_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  lines.push('  return router')
  lines.push('}')
  lines.push('')

  return {
    fileName,
    code: lines.join('\n'),
  }
}
