// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * HTTP API Client Generator
 *
 * Generates a typed fetch client for each Prisma model.
 * Used by Expo/React Native apps that need HTTP instead of server functions.
 */

import type { PrismaModel } from './prisma-generator'
import { toCamelCase, getIdField, getScalarFields } from './prisma-generator'
import { GENERATED_FILE_LICENSE_HEADER } from './generated-file-license-header'

/**
 * Convert model name to route path (kebab-case, plural)
 */
function toRoutePath(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  // Simple pluralization
  if (kebab.endsWith('y')) return kebab.slice(0, -1) + 'ies'
  if (kebab.endsWith('s') || kebab.endsWith('x') || kebab.endsWith('ch') || kebab.endsWith('sh')) {
    return kebab + 'es'
  }
  return kebab + 's'
}

/**
 * Generate API client code for all models
 */
export function generateApiClient(models: PrismaModel[]): string {
  const lines: string[] = [
    GENERATED_FILE_LICENSE_HEADER,
    '/**',
    ' * Auto-generated API Client',
    ' *',
    ' * Typed HTTP client for CRUD operations.',
    ' * Generated by `shogo generate` - DO NOT EDIT',
    ' */',
    '',
    'import type {',
  ]

  // Import types
  for (const model of models) {
    lines.push(`  ${model.name}Type,`)
    lines.push(`  ${model.name}CreateInput,`)
    lines.push(`  ${model.name}UpdateInput,`)
  }
  lines.push('} from \'./types\'')
  lines.push('')

  // API Response types
  lines.push('// ============================================================================')
  lines.push('// Response Types')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('export interface ApiResponse<T> {')
  lines.push('  ok: boolean')
  lines.push('  data?: T')
  lines.push('  error?: { code: string; message: string }')
  lines.push('}')
  lines.push('')
  lines.push('export interface ApiListResponse<T> {')
  lines.push('  ok: boolean')
  lines.push('  items?: T[]')
  lines.push('  error?: { code: string; message: string }')
  lines.push('}')
  lines.push('')

  // API Client Config
  lines.push('// ============================================================================')
  lines.push('// Client Configuration')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('export interface ApiClientConfig {')
  lines.push('  /** Base URL for API requests (e.g., "http://localhost:3000/api") */')
  lines.push('  baseUrl: string')
  lines.push('  /** Optional auth token to include in requests */')
  lines.push('  token?: string')
  lines.push('  /** Optional user ID to include in requests */')
  lines.push('  userId?: string')
  lines.push('}')
  lines.push('')
  lines.push('let config: ApiClientConfig = { baseUrl: \'/api\' }')
  lines.push('')
  lines.push('/**')
  lines.push(' * Configure the API client')
  lines.push(' */')
  lines.push('export function configureApiClient(newConfig: Partial<ApiClientConfig>) {')
  lines.push('  config = { ...config, ...newConfig }')
  lines.push('}')
  lines.push('')
  lines.push('/**')
  lines.push(' * Get current API client configuration')
  lines.push(' */')
  lines.push('export function getApiConfig(): ApiClientConfig {')
  lines.push('  return { ...config }')
  lines.push('}')
  lines.push('')

  // Helper functions
  lines.push('// ============================================================================')
  lines.push('// HTTP Helpers')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('async function request<T>(')
  lines.push('  method: string,')
  lines.push('  path: string,')
  lines.push('  body?: unknown')
  lines.push('): Promise<ApiResponse<T>> {')
  lines.push('  const headers: Record<string, string> = {')
  lines.push('    \'Content-Type\': \'application/json\',')
  lines.push('  }')
  lines.push('')
  lines.push('  if (config.token) {')
  lines.push('    headers[\'Authorization\'] = `Bearer ${config.token}`')
  lines.push('  }')
  lines.push('')
  lines.push('  const url = `${config.baseUrl}${path}`')
  lines.push('')
  lines.push('  try {')
  lines.push('    const response = await fetch(url, {')
  lines.push('      method,')
  lines.push('      headers,')
  lines.push('      body: body ? JSON.stringify(body) : undefined,')
  lines.push('    })')
  lines.push('')
  lines.push('    const data = await response.json()')
  lines.push('')
  lines.push('    if (!response.ok) {')
  lines.push('      return {')
  lines.push('        ok: false,')
  lines.push('        error: data.error || { code: \'request_failed\', message: `HTTP ${response.status}` },')
  lines.push('      }')
  lines.push('    }')
  lines.push('')
  lines.push('    return data')
  lines.push('  } catch (error) {')
  lines.push('    return {')
  lines.push('      ok: false,')
  lines.push('      error: {')
  lines.push('        code: \'network_error\',')
  lines.push('        message: error instanceof Error ? error.message : \'Network error\',')
  lines.push('      },')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')

  // Generate client for each model
  for (const model of models) {
    lines.push(...generateModelClient(model))
  }

  // Generate combined API client
  lines.push(...generateCombinedClient(models))

  return lines.join('\n')
}

/**
 * Generate API client methods for a single model
 */
function generateModelClient(model: PrismaModel): string[] {
  const name = model.name
  const nameLower = toCamelCase(name)
  const routePath = toRoutePath(name)
  const idField = getIdField(model)

  if (!idField) {
    return [`// Skipped ${name} - no @id field found`, '']
  }

  return [
    `// ============================================================================`,
    `// ${name} API Client`,
    `// ============================================================================`,
    '',
    `export const ${nameLower}Api = {`,
    `  /**`,
    `   * List all ${name} records`,
    `   * @param options - Query options including where filters, pagination, and custom query params`,
    `   * @param options.where - Filter conditions (passed as query params to the API)`,
    `   * @param options.limit - Maximum number of records to return`,
    `   * @param options.offset - Number of records to skip`,
    `   * @param options.params - Additional query parameters to append to the request`,
    `   */`,
    `  async list(options?: { where?: Record<string, unknown>; limit?: number; offset?: number; params?: Record<string, string | number | boolean> }): Promise<ApiListResponse<${name}Type>> {`,
    `    const params = new URLSearchParams()`,
    `    `,
    `    // Add where filters as query params`,
    `    if (options?.where) {`,
    `      for (const [key, value] of Object.entries(options.where)) {`,
    `        if (value !== undefined && value !== null) {`,
    `          params.set(key, String(value))`,
    `        }`,
    `      }`,
    `    }`,
    `    `,
    `    // Add additional params`,
    `    if (options?.params) {`,
    `      for (const [key, value] of Object.entries(options.params)) {`,
    `        if (value !== undefined && value !== null) {`,
    `          params.set(key, String(value))`,
    `        }`,
    `      }`,
    `    }`,
    `    `,
    `    // Add pagination`,
    `    if (options?.limit) params.set('limit', String(options.limit))`,
    `    if (options?.offset) params.set('offset', String(options.offset))`,
    `    if (config.userId) params.set('userId', config.userId)`,
    `    `,
    `    const query = params.toString() ? \`?\${params.toString()}\` : ''`,
    `    return request<${name}Type>('GET', \`/${routePath}\${query}\`) as Promise<ApiListResponse<${name}Type>>`,
    `  },`,
    '',
    `  /**`,
    `   * Get a single ${name} by ID`,
    `   */`,
    `  async get(id: string): Promise<ApiResponse<${name}Type>> {`,
    `    return request<${name}Type>('GET', \`/${routePath}/\${id}\`)`,
    `  },`,
    '',
    `  /**`,
    `   * Create a new ${name}`,
    `   */`,
    `  async create(input: ${name}CreateInput): Promise<ApiResponse<${name}Type>> {`,
    `    const body = config.userId ? { ...input, userId: config.userId } : input`,
    `    return request<${name}Type>('POST', \`/${routePath}\`, body)`,
    `  },`,
    '',
    `  /**`,
    `   * Update an existing ${name}`,
    `   */`,
    `  async update(id: string, input: ${name}UpdateInput): Promise<ApiResponse<${name}Type>> {`,
    `    return request<${name}Type>('PATCH', \`/${routePath}/\${id}\`, input)`,
    `  },`,
    '',
    `  /**`,
    `   * Delete a ${name}`,
    `   */`,
    `  async delete(id: string): Promise<ApiResponse<void>> {`,
    `    return request<void>('DELETE', \`/${routePath}/\${id}\`)`,
    `  },`,
    `}`,
    '',
  ]
}

/**
 * Generate combined API client object
 */
function generateCombinedClient(models: PrismaModel[]): string[] {
  const lines: string[] = [
    '// ============================================================================',
    '// Combined API Client',
    '// ============================================================================',
    '',
    '/**',
    ' * Combined API client with all model endpoints',
    ' */',
    'export const api = {',
  ]

  for (const model of models) {
    const nameLower = toCamelCase(model.name)
    const idField = getIdField(model)
    if (!idField) continue
    lines.push(`  ${nameLower}: ${nameLower}Api,`)
  }

  lines.push('}')
  lines.push('')
  lines.push('export default api')
  lines.push('')

  return lines
}
