// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * API Domain Store Generator
 *
 * Generates MobX stores that use HTTP API client instead of server functions.
 * Used by Expo/React Native apps.
 */

import type { PrismaModel } from './prisma-generator'
import { toCamelCase, getIdField } from './prisma-generator'
import { GENERATED_FILE_LICENSE_HEADER } from './generated-file-license-header'

/**
 * Generate domain store code that uses API client
 */
export function generateApiDomainStore(models: PrismaModel[]): string {
  const lines: string[] = [
    GENERATED_FILE_LICENSE_HEADER,
    '/**',
    ' * Auto-generated Domain Store (API-based)',
    ' *',
    ' * MobX store with collections for each model.',
    ' * Uses HTTP API client instead of server functions.',
    ' * Generated by `shogo generate` - DO NOT EDIT',
    ' */',
    '',
    'import { makeAutoObservable, runInAction } from \'mobx\'',
    'import {',
  ]

  // Import API client methods
  for (const model of models) {
    const nameLower = toCamelCase(model.name)
    lines.push(`  ${nameLower}Api,`)
  }
  lines.push('} from \'./api-client\'')
  lines.push('')

  // Import types
  lines.push('import type {')
  for (const model of models) {
    lines.push(`  ${model.name}Type,`)
    lines.push(`  ${model.name}CreateInput,`)
    lines.push(`  ${model.name}UpdateInput,`)
  }
  lines.push('} from \'./types\'')
  lines.push('')

  // Generate store class for each model
  for (const model of models) {
    lines.push(...generateApiModelStore(model))
  }

  // Generate root store
  lines.push(...generateApiRootStore(models))

  // Export factory function
  lines.push(...generateApiFactory(models))

  return lines.join('\n')
}

/**
 * Generate store class for a single model using API client
 */
function generateApiModelStore(model: PrismaModel): string[] {
  const name = model.name
  const nameLower = toCamelCase(name)

  return [
    `// ============================================================================`,
    `// ${name} Store (API-based)`,
    `// ============================================================================`,
    '',
    `export class ${name}Store {`,
    `  items: Map<string, ${name}Type> = new Map()`,
    `  isLoading = false`,
    `  error: string | null = null`,
    ``,
    `  // Track pending operations for optimistic updates`,
    `  private pendingDeletes = new Set<string>()`,
    `  private pendingUpdates = new Set<string>()`,
    ``,
    `  constructor() {`,
    `    makeAutoObservable(this, {`,
    `      pendingDeletes: false,`,
    `      pendingUpdates: false,`,
    `    })`,
    `  }`,
    ``,
    `  // === Getters ===`,
    ``,
    `  /** Get all items as array */`,
    `  get all(): ${name}Type[] {`,
    `    return Array.from(this.items.values())`,
    `  }`,
    ``,
    `  /** Get item by ID */`,
    `  get(id: string): ${name}Type | undefined {`,
    `    return this.items.get(id)`,
    `  }`,
    ``,
    `  /** Check if item has pending operation */`,
    `  isPending(id: string): boolean {`,
    `    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)`,
    `  }`,
    ``,
    `  // === Actions ===`,
    ``,
    `  /** Load all items from API */`,
    `  async loadAll(where?: Record<string, unknown>) {`,
    `    runInAction(() => {`,
    `      this.isLoading = true`,
    `      this.error = null`,
    `    })`,
    ``,
    `    try {`,
    `      const result = await ${nameLower}Api.list({ where })`,
    ``,
    `      if (!result.ok || !result.items) {`,
    `        throw new Error(result.error?.message || 'Failed to load')`,
    `      }`,
    ``,
    `      runInAction(() => {`,
    `        this.items.clear()`,
    `        for (const item of result.items!) {`,
    `          this.items.set(item.id, item)`,
    `        }`,
    `        this.isLoading = false`,
    `      })`,
    `    } catch (e) {`,
    `      runInAction(() => {`,
    `        this.error = e instanceof Error ? e.message : 'Failed to load'`,
    `        this.isLoading = false`,
    `      })`,
    `      throw e`,
    `    }`,
    `  }`,
    ``,
    `  /** Load single item by ID */`,
    `  async loadById(id: string) {`,
    `    try {`,
    `      const result = await ${nameLower}Api.get(id)`,
    ``,
    `      if (!result.ok || !result.data) {`,
    `        throw new Error(result.error?.message || '${name} not found')`,
    `      }`,
    ``,
    `      runInAction(() => {`,
    `        this.items.set(result.data!.id, result.data!)`,
    `      })`,
    ``,
    `      return result.data`,
    `    } catch (e) {`,
    `      runInAction(() => {`,
    `        this.error = e instanceof Error ? e.message : 'Failed to load'`,
    `      })`,
    `      throw e`,
    `    }`,
    `  }`,
    ``,
    `  /** Create new item with optimistic update */`,
    `  async create(input: ${name}CreateInput) {`,
    `    // Create optimistic item`,
    `    const tempId = \`temp-\${crypto.randomUUID()}\``,
    `    const optimisticItem: ${name}Type = {`,
    `      id: tempId,`,
    `      ...input,`,
    `      createdAt: new Date(),`,
    `      updatedAt: new Date(),`,
    `    } as ${name}Type`,
    ``,
    `    // Add optimistically`,
    `    runInAction(() => {`,
    `      this.items.set(tempId, optimisticItem)`,
    `    })`,
    ``,
    `    try {`,
    `      const result = await ${nameLower}Api.create(input)`,
    ``,
    `      if (!result.ok || !result.data) {`,
    `        throw new Error(result.error?.message || 'Failed to create')`,
    `      }`,
    ``,
    `      runInAction(() => {`,
    `        // Remove temp, add real`,
    `        this.items.delete(tempId)`,
    `        this.items.set(result.data!.id, result.data!)`,
    `      })`,
    ``,
    `      return result.data`,
    `    } catch (e) {`,
    `      runInAction(() => {`,
    `        // Rollback`,
    `        this.items.delete(tempId)`,
    `        this.error = e instanceof Error ? e.message : 'Failed to create'`,
    `      })`,
    `      throw e`,
    `    }`,
    `  }`,
    ``,
    `  /** Update item with optimistic update */`,
    `  async update(id: string, input: ${name}UpdateInput) {`,
    `    // Validate id to prevent undefined from reaching the API`,
    `    if (!id || typeof id !== 'string') {`,
    `      console.error('[${name}Store] update called with invalid id:', id)`,
    `      return`,
    `    }`,
    `    const existing = this.items.get(id)`,
    `    if (!existing || this.pendingUpdates.has(id)) return`,
    ``,
    `    const previousState = { ...existing }`,
    `    this.pendingUpdates.add(id)`,
    ``,
    `    // Optimistically update`,
    `    runInAction(() => {`,
    `      this.items.set(id, {`,
    `        ...existing,`,
    `        ...input,`,
    `        updatedAt: new Date(),`,
    `      } as ${name}Type)`,
    `    })`,
    ``,
    `    try {`,
    `      const result = await ${nameLower}Api.update(id, input)`,
    ``,
    `      if (!result.ok || !result.data) {`,
    `        throw new Error(result.error?.message || 'Failed to update')`,
    `      }`,
    ``,
    `      runInAction(() => {`,
    `        this.items.set(id, result.data!)`,
    `        this.pendingUpdates.delete(id)`,
    `      })`,
    ``,
    `      return result.data`,
    `    } catch (e) {`,
    `      runInAction(() => {`,
    `        // Rollback`,
    `        this.items.set(id, previousState)`,
    `        this.pendingUpdates.delete(id)`,
    `        this.error = e instanceof Error ? e.message : 'Failed to update'`,
    `      })`,
    `      throw e`,
    `    }`,
    `  }`,
    ``,
    `  /** Delete item with optimistic update */`,
    `  async delete(id: string) {`,
    `    // Validate id to prevent undefined from reaching the API`,
    `    if (!id || typeof id !== 'string') {`,
    `      console.error('[${name}Store] delete called with invalid id:', id)`,
    `      return`,
    `    }`,
    `    const existing = this.items.get(id)`,
    `    if (!existing || this.pendingDeletes.has(id)) return`,
    ``,
    `    this.pendingDeletes.add(id)`,
    ``,
    `    // Optimistically remove`,
    `    runInAction(() => {`,
    `      this.items.delete(id)`,
    `    })`,
    ``,
    `    try {`,
    `      const result = await ${nameLower}Api.delete(id)`,
    ``,
    `      if (!result.ok) {`,
    `        throw new Error(result.error?.message || 'Failed to delete')`,
    `      }`,
    ``,
    `      runInAction(() => {`,
    `        this.pendingDeletes.delete(id)`,
    `      })`,
    `    } catch (e) {`,
    `      runInAction(() => {`,
    `        // Rollback`,
    `        this.items.set(id, existing)`,
    `        this.pendingDeletes.delete(id)`,
    `        this.error = e instanceof Error ? e.message : 'Failed to delete'`,
    `      })`,
    `      throw e`,
    `    }`,
    `  }`,
    ``,
    `  /** Clear error state */`,
    `  clearError() {`,
    `    this.error = null`,
    `  }`,
    ``,
    `  /** Clear all data */`,
    `  clear() {`,
    `    this.items.clear()`,
    `    this.error = null`,
    `    this.isLoading = false`,
    `  }`,
    `}`,
    '',
  ]
}

/**
 * Generate root store that combines all model stores
 */
function generateApiRootStore(models: PrismaModel[]): string[] {
  const lines: string[] = [
    '// ============================================================================',
    '// Root Store',
    '// ============================================================================',
    '',
    'export class RootStore {',
  ]

  // Properties
  for (const model of models) {
    const nameLower = toCamelCase(model.name)
    lines.push(`  ${nameLower}: ${model.name}Store`)
  }

  lines.push('')
  lines.push('  constructor() {')

  // Initialize stores
  for (const model of models) {
    const nameLower = toCamelCase(model.name)
    lines.push(`    this.${nameLower} = new ${model.name}Store()`)
  }

  lines.push('    makeAutoObservable(this)')
  lines.push('  }')
  lines.push('')

  // Clear all
  lines.push('  /** Clear all stores */')
  lines.push('  clearAll() {')
  for (const model of models) {
    const nameLower = toCamelCase(model.name)
    lines.push(`    this.${nameLower}.clear()`)
  }
  lines.push('  }')

  lines.push('}')
  lines.push('')

  return lines
}

/**
 * Generate factory function and singleton
 */
function generateApiFactory(models: PrismaModel[]): string[] {
  return [
    '// ============================================================================',
    '// Factory & Singleton',
    '// ============================================================================',
    '',
    'let rootStore: RootStore | null = null',
    '',
    '/**',
    ' * Get or create the root store singleton',
    ' */',
    'export function getStore(): RootStore {',
    '  if (!rootStore) {',
    '    rootStore = new RootStore()',
    '  }',
    '  return rootStore',
    '}',
    '',
    '/**',
    ' * Create a new root store (for testing or SSR)',
    ' */',
    'export function createStore(): RootStore {',
    '  return new RootStore()',
    '}',
    '',
    '/**',
    ' * Reset the singleton store',
    ' */',
    'export function resetStore(): void {',
    '  rootStore = null',
    '}',
    '',
  ]
}
