// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auth Store Generator
 *
 * Generates a MobX-based authentication store that integrates with
 * the User model API. Provides signIn, signUp, signOut functionality
 * with localStorage persistence.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { GENERATED_FILE_LICENSE_HEADER } from './generated-file-license-header'

export interface AuthStoreGeneratorOptions {
  /** The User model from Prisma schema */
  userModel: PrismaModel
  /** Storage key for localStorage (default: 'shogo-auth-user') */
  storageKey?: string
  /** API base path (default: '/api') */
  apiBase?: string
}

/**
 * Find the email field in the User model
 */
function findEmailField(model: PrismaModel): PrismaField | undefined {
  return model.fields.find(f => 
    f.name === 'email' || 
    f.name === 'emailAddress' || 
    f.type === 'String' && f.name.toLowerCase().includes('email')
  )
}

/**
 * Find the name field in the User model
 */
function findNameField(model: PrismaModel): PrismaField | undefined {
  return model.fields.find(f => 
    f.name === 'name' || 
    f.name === 'displayName' || 
    f.name === 'fullName' ||
    f.name === 'username'
  )
}

/**
 * Generate the AuthStore code
 */
export function generateAuthStore(options: AuthStoreGeneratorOptions): string {
  const { userModel, storageKey = 'shogo-auth-user', apiBase = '/api' } = options
  
  const emailField = findEmailField(userModel)
  const nameField = findNameField(userModel)
  
  if (!emailField) {
    throw new Error(`User model "${userModel.name}" must have an email field for auth generation`)
  }
  
  const emailFieldName = emailField.name
  const nameFieldName = nameField?.name || null
  const userModelName = userModel.name
  const userEndpoint = userModelName.toLowerCase() + 's' // e.g., 'users'

  const lines: string[] = [
    GENERATED_FILE_LICENSE_HEADER,
    '/**',
    ' * Auth Store',
    ' *',
    ' * MobX authentication store with localStorage persistence.',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    "import { makeAutoObservable, runInAction } from 'mobx'",
    '',
    `const API_BASE = '${apiBase}'`,
    `const STORAGE_KEY = '${storageKey}'`,
    '',
    '// ============================================================================',
    '// Types',
    '// ============================================================================',
    '',
    'export interface AuthUser {',
    '  id: string',
    `  ${emailFieldName}: string`,
  ]

  // Add name field if it exists
  if (nameFieldName) {
    const nameRequired = nameField?.isRequired
    lines.push(`  ${nameFieldName}: string${nameRequired ? '' : ' | null'}`)
  }

  lines.push(
    '  createdAt: string | Date',
    '  updatedAt: string | Date',
    '}',
    '',
    'export interface SignUpInput {',
    `  ${emailFieldName}: string`,
    '  password?: string',
  )

  if (nameFieldName) {
    lines.push(`  ${nameFieldName}?: string`)
  }

  lines.push(
    '}',
    '',
    'export interface SignInInput {',
    `  ${emailFieldName}: string`,
    '  password?: string',
    '}',
    '',
    '// ============================================================================',
    '// AuthStore',
    '// ============================================================================',
    '',
    'export class AuthStore {',
    '  user: AuthUser | null = null',
    '  isLoading = false',
    '  error: string | null = null',
    '',
    '  constructor() {',
    '    makeAutoObservable(this)',
    '    this.loadFromStorage()',
    '  }',
    '',
    '  // === Getters ===',
    '',
    '  get isAuthenticated(): boolean {',
    '    return this.user !== null',
    '  }',
    '',
    '  get userId(): string | null {',
    '    return this.user?.id ?? null',
    '  }',
    '',
    '  // === Storage ===',
    '',
    '  private loadFromStorage() {',
    '    try {',
    '      if (typeof window === "undefined") return',
    '      const stored = localStorage.getItem(STORAGE_KEY)',
    '      if (stored) {',
    '        this.user = JSON.parse(stored)',
    '      }',
    '    } catch {',
    '      // Ignore storage errors',
    '    }',
    '  }',
    '',
    '  private saveToStorage(user: AuthUser | null) {',
    '    try {',
    '      if (typeof window === "undefined") return',
    '      if (user) {',
    '        localStorage.setItem(STORAGE_KEY, JSON.stringify(user))',
    '      } else {',
    '        localStorage.removeItem(STORAGE_KEY)',
    '      }',
    '    } catch {',
    '      // Ignore storage errors',
    '    }',
    '  }',
    '',
    '  // === Actions ===',
    '',
    '  /**',
    '   * Sign in with email',
    `   * Looks up user by ${emailFieldName} in the database`,
    '   */',
    '  async signIn(input: SignInInput): Promise<AuthUser> {',
    '    this.isLoading = true',
    '    this.error = null',
    '',
    '    try {',
    `      // Find user by ${emailFieldName}`,
    `      const res = await fetch(\`\${API_BASE}/${userEndpoint}?${emailFieldName}=\${encodeURIComponent(input.${emailFieldName})}\`)`,
    '      const data = await res.json()',
    '',
    '      if (!data.ok) {',
    "        throw new Error(data.error?.message || 'Failed to sign in')",
    '      }',
    '',
    '      const users = data.items || []',
    '      if (users.length === 0) {',
    "        throw new Error('No account found with this email. Please sign up first.')",
    '      }',
    '',
    '      const user = users[0] as AuthUser',
    '',
    '      runInAction(() => {',
    '        this.user = user',
    '        this.isLoading = false',
    '        this.saveToStorage(user)',
    '      })',
    '',
    '      return user',
    '    } catch (err: unknown) {',
    "      const message = err instanceof Error ? err.message : 'Sign in failed'",
    '      runInAction(() => {',
    '        this.error = message',
    '        this.isLoading = false',
    '      })',
    '      throw err',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Sign up with email',
    '   * Creates a new user in the database',
    '   */',
    '  async signUp(input: SignUpInput): Promise<AuthUser> {',
    '    this.isLoading = true',
    '    this.error = null',
    '',
    '    try {',
    '      // Check if user already exists',
    `      const checkRes = await fetch(\`\${API_BASE}/${userEndpoint}?${emailFieldName}=\${encodeURIComponent(input.${emailFieldName})}\`)`,
    '      const checkData = await checkRes.json()',
    '',
    '      if (checkData.ok && checkData.items?.length > 0) {',
    "        throw new Error('An account with this email already exists. Please sign in.')",
    '      }',
    '',
    '      // Create new user',
    `      const res = await fetch(\`\${API_BASE}/${userEndpoint}\`, {`,
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    '        body: JSON.stringify({',
    `          ${emailFieldName}: input.${emailFieldName},`,
  )

  if (nameFieldName) {
    lines.push(`          ${nameFieldName}: input.${nameFieldName} ?? null,`)
  }

  lines.push(
    '        }),',
    '      })',
    '      const data = await res.json()',
    '',
    '      if (!data.ok) {',
    "        throw new Error(data.error?.message || 'Failed to create account')",
    '      }',
    '',
    '      const user = data.data as AuthUser',
    '',
    '      runInAction(() => {',
    '        this.user = user',
    '        this.isLoading = false',
    '        this.saveToStorage(user)',
    '      })',
    '',
    '      return user',
    '    } catch (err: unknown) {',
    "      const message = err instanceof Error ? err.message : 'Sign up failed'",
    '      runInAction(() => {',
    '        this.error = message',
    '        this.isLoading = false',
    '      })',
    '      throw err',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Sign out',
    '   * Clears user from state and localStorage',
    '   */',
    '  signOut() {',
    '    this.user = null',
    '    this.error = null',
    '    this.saveToStorage(null)',
    '  }',
    '',
    '  /**',
    '   * Clear error state',
    '   */',
    '  clearError() {',
    '    this.error = null',
    '  }',
    '',
    '  /**',
    '   * Refresh user data from server',
    '   */',
    '  async refresh(): Promise<AuthUser | null> {',
    '    if (!this.user) return null',
    '',
    '    try {',
    `      const res = await fetch(\`\${API_BASE}/${userEndpoint}/\${this.user.id}\`)`,
    '      const data = await res.json()',
    '',
    '      if (data.ok && data.data) {',
    '        runInAction(() => {',
    '          this.user = data.data',
    '          this.saveToStorage(data.data)',
    '        })',
    '        return data.data',
    '      }',
    '',
    '      // User not found, sign out',
    '      this.signOut()',
    '      return null',
    '    } catch {',
    '      return this.user',
    '    }',
    '  }',
    '}',
    '',
    '// ============================================================================',
    '// Singleton & Factory',
    '// ============================================================================',
    '',
    'let authStore: AuthStore | null = null',
    '',
    '/**',
    ' * Get or create the auth store singleton',
    ' */',
    'export function getAuthStore(): AuthStore {',
    '  if (!authStore) {',
    '    authStore = new AuthStore()',
    '  }',
    '  return authStore',
    '}',
    '',
    '/**',
    ' * Create a new auth store (for testing or SSR)',
    ' */',
    'export function createAuthStore(): AuthStore {',
    '  return new AuthStore()',
    '}',
    '',
    '/**',
    ' * Reset the singleton auth store',
    ' */',
    'export function resetAuthStore(): void {',
    '  authStore = null',
    '}',
    '',
  )

  return lines.join('\n')
}

/**
 * Check if schema has a User model suitable for auth
 */
export function hasUserModel(models: PrismaModel[]): boolean {
  const userModel = models.find(m => 
    m.name === 'User' || 
    m.name === 'Account' || 
    m.name.toLowerCase() === 'user'
  )
  
  if (!userModel) return false
  
  // Must have an email field
  return !!findEmailField(userModel)
}

/**
 * Get the User model from the schema
 */
export function getUserModel(models: PrismaModel[]): PrismaModel | undefined {
  return models.find(m => 
    m.name === 'User' || 
    m.name === 'Account' || 
    m.name.toLowerCase() === 'user'
  )
}
