// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom Routes File Helper
 *
 * `custom-routes.ts` is the editable surface where pod authors mount
 * non-CRUD routes — proxies, aggregations, webhooks, auth flows.
 * `generateServer()` imports + mounts it under `/api/` automatically,
 * but only when `serverConfig.customRoutesPath` is set in
 * `shogo.config.json`.
 *
 * Many workspaces (and the SDK's own example apps) ship a
 * `shogo.config.json` that doesn't declare `customRoutesPath`. When
 * `shogo generate` runs, the produced `server.tsx` then has no
 * import / mount and the agent's `/api/...` calls fall through to
 * the SPA's static catch-all — a silent 200 OK that looks like a
 * routing problem rather than the missing import it actually is.
 *
 * `ensureCustomRoutes(projectDir)` makes the regen path robust to
 * that gap by guaranteeing two invariants:
 *
 *   1. A `custom-routes.{ts,tsx}` file always exists at the project
 *      root after regen. The first call writes a minimal Hono
 *      scaffold; subsequent calls are no-ops.
 *
 *   2. The function returns a stable `customRoutesPath` (`./custom-routes`)
 *      that the generate script can plug into the `serverConfig`
 *      passed to `generateServer()`, even when `shogo.config.json`
 *      doesn't declare one.
 *
 * Idempotent — safe to call on every regen.
 */

import { existsSync, writeFileSync } from 'fs'
import { join } from 'path'

/**
 * Minimal scaffold for a fresh `custom-routes.ts`. Kept short on
 * purpose — the runtime-template ships a richer doc-heavy version
 * for greenfield workspaces; this is the recovery scaffold used when
 * `shogo generate` runs on a workspace that's missing the file. The
 * agent-facing docs in `AGENTS.md` / system prompt cover the
 * patterns; the scaffold just needs to be a working Hono app.
 */
export const CUSTOM_ROUTES_SCAFFOLD = `// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * Mount custom non-CRUD routes (proxies, aggregations, webhooks, etc.)
 * on the exported Hono \`app\`. They show up at \`/api/...\` alongside
 * the generated CRUD routes.
 *
 * Examples:
 *   app.get('/dashboard', async (c) => c.json({ ... }))
 *   app.post('/webhooks/stripe', async (c) => { ... })
 *
 * The Prisma client is available — import it from \`./src/lib/db\`:
 *   import { prisma } from './src/lib/db'
 *
 * Saving this file triggers a fast restart of server.tsx so changes
 * are live in under a second. Do NOT edit server.tsx; it is
 * auto-generated by \`bun x shogo generate\`.
 */

import { Hono } from 'hono'

const app = new Hono()

// Add your custom routes here. Example:
//   app.get('/hello', (c) => c.json({ message: 'Hello!' }))

export default app
`

export interface EnsureCustomRoutesResult {
  /** Relative path suitable for `serverConfig.customRoutesPath` (always `./custom-routes`). */
  path: string
  /** True iff the call wrote a new `custom-routes.ts` file. */
  created: boolean
  /** Absolute path to the file that exists on disk after the call. */
  absolutePath: string
}

/**
 * Guarantee `custom-routes.{ts,tsx}` exists at the project root and
 * return the relative path the SDK's `generateServer()` should mount.
 *
 * If both `.ts` and `.tsx` are absent, writes
 * `<projectDir>/custom-routes.ts` with {@link CUSTOM_ROUTES_SCAFFOLD}.
 * If either already exists, leaves it alone. Returns:
 *
 *   - `path`: `'./custom-routes'` — the value to plug into
 *     `serverConfig.customRoutesPath`.
 *   - `created`: whether this call wrote the file.
 *   - `absolutePath`: the file that's present after the call.
 *
 * Pure I/O — no module-level side effects. Safe to call from inside
 * a regen script that runs on every `shogo generate` invocation.
 */
export function ensureCustomRoutes(projectDir: string): EnsureCustomRoutesResult {
  const tsPath = join(projectDir, 'custom-routes.ts')
  const tsxPath = join(projectDir, 'custom-routes.tsx')

  if (existsSync(tsPath)) {
    return { path: './custom-routes', created: false, absolutePath: tsPath }
  }
  if (existsSync(tsxPath)) {
    return { path: './custom-routes', created: false, absolutePath: tsxPath }
  }

  writeFileSync(tsPath, CUSTOM_ROUTES_SCAFFOLD, 'utf-8')
  return { path: './custom-routes', created: true, absolutePath: tsPath }
}
