// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Docusaurus Site Scaffolding Generator
 *
 * Generates the Docusaurus 3.9 site structure:
 *   - docusaurus.config.ts
 *   - sidebars.ts
 *   - package.json
 *   - Intro page (docs/intro.md)
 *   - Static landing page (src/pages/index.md)
 *
 * All scaffolding files use skipIfExists so they won't overwrite user edits.
 */

import type { GeneratedDocFile } from './docs-generator'

export interface DocsSiteConfig {
  /** Project name (used in title, navbar) */
  projectName?: string
  /** Tagline */
  tagline?: string
  /** Base URL for the site (default: '/') */
  baseUrl?: string
  /** URL of the production site (for SEO) */
  url?: string
}

/**
 * Generate all Docusaurus site scaffolding files
 */
export function generateDocsSiteScaffold(
  config: DocsSiteConfig = {},
): GeneratedDocFile[] {
  const files: GeneratedDocFile[] = []

  files.push(generatePackageJson(config))
  files.push(generateDocusaurusConfig(config))
  files.push(generateSidebars())
  files.push(generateIntroPage(config))
  files.push(generateLandingPage(config))

  return files
}

// ============================================================================
// package.json
// ============================================================================

function generatePackageJson(config: DocsSiteConfig): GeneratedDocFile {
  const projectName = config.projectName || 'my-app'
  const slug = projectName.toLowerCase().replace(/\s+/g, '-')

  const pkg = {
    name: `${slug}-dev-docs`,
    version: '0.0.0',
    private: true,
    scripts: {
      docusaurus: 'docusaurus',
      start: 'docusaurus start',
      build: 'docusaurus build',
      swizzle: 'docusaurus swizzle',
      deploy: 'docusaurus deploy',
      clear: 'docusaurus clear',
      serve: 'docusaurus serve',
      'write-translations': 'docusaurus write-translations',
      'write-heading-ids': 'docusaurus write-heading-ids',
    },
    dependencies: {
      '@docusaurus/core': '3.9.0',
      '@docusaurus/preset-classic': '3.9.0',
      '@mdx-js/react': '^3.0.0',
      'clsx': '^2.0.0',
      'prism-react-renderer': '^2.3.0',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@docusaurus/module-type-aliases': '3.9.0',
      '@docusaurus/tsconfig': '3.9.0',
      'typescript': '~5.6.0',
    },
    browserslist: {
      production: ['>0.5%', 'not dead', 'not op_mini all'],
      development: [
        'last 3 chrome version',
        'last 3 firefox version',
        'last 5 safari version',
      ],
    },
    engines: {
      node: '>=20.0',
    },
  }

  return {
    path: 'package.json',
    content: JSON.stringify(pkg, null, 2) + '\n',
    skipIfExists: true,
  }
}

// ============================================================================
// docusaurus.config.ts
// ============================================================================

function generateDocusaurusConfig(config: DocsSiteConfig): GeneratedDocFile {
  const projectName = config.projectName || 'My App'
  const tagline = config.tagline || 'Auto-generated developer reference'
  const baseUrl = config.baseUrl || '/'
  const url = config.url || 'https://your-docs-site.example.com'

  const content = `import { themes as prismThemes } from 'prism-react-renderer'
import type { Config } from '@docusaurus/types'
import type * as Preset from '@docusaurus/preset-classic'

const config: Config = {
  title: '${projectName} Developer Docs',
  tagline: '${tagline}',
  favicon: 'img/favicon.ico',

  url: '${url}',
  baseUrl: '${baseUrl}',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: '${projectName} Developer Docs',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Developer Reference',
        },
      ],
    },
    footer: {
      style: 'dark',
      copyright: \`Built with Docusaurus. Generated by Shogo SDK.\`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'http'],
    },
  } satisfies Preset.ThemeConfig,
}

export default config
`

  return {
    path: 'docusaurus.config.ts',
    content,
    skipIfExists: true,
  }
}

// ============================================================================
// sidebars.ts
// ============================================================================

function generateSidebars(): GeneratedDocFile {
  const content = `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'models-overview',
    'api-reference',
    {
      type: 'autogenerated',
      dirName: 'models',
    },
  ],
}

export default sidebars
`

  return {
    path: 'sidebars.ts',
    content,
    skipIfExists: true,
  }
}

// ============================================================================
// docs/intro.md
// ============================================================================

function generateIntroPage(config: DocsSiteConfig): GeneratedDocFile {
  const projectName = config.projectName || 'My App'

  const content = `---
title: Introduction
sidebar_label: Introduction
sidebar_position: 0
slug: /
---

# ${projectName} Developer Docs

Welcome to the auto-generated developer documentation for **${projectName}**.

This documentation is generated from your Prisma schema by the [Shogo SDK](https://github.com/shogo-ai/shogo-ai) and includes:

- **Models** — Field definitions, types, and relationships
- **API Reference** — REST endpoints with request/response examples
- **TypeScript Types** — Generated interfaces for type-safe development
- **Stores** — Client-side data store usage examples
- **Hooks** — Server-side customization points

## Getting Started

Browse the sidebar to explore your models, or check the [Models Overview](./models-overview) for a summary.

## Regenerating Docs

These docs are generated automatically. To update them after changing your Prisma schema:

\`\`\`bash
shogo generate
\`\`\`

> **Note:** Files marked with \`skipIfExists\` (like this intro page) won't be overwritten, so your edits are safe.
`

  return {
    path: 'docs/intro.md',
    content,
    skipIfExists: true,
  }
}

// ============================================================================
// src/pages/index.md (landing page - redirects to docs)
// ============================================================================

function generateLandingPage(config: DocsSiteConfig): GeneratedDocFile {
  return {
    path: 'src/css/custom.css',
    content: `:root {
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
}

[data-theme='dark'] {
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-darker: #1fa588;
  --ifm-color-primary-darkest: #1a8870;
  --ifm-color-primary-lighter: #29d5b0;
  --ifm-color-primary-lightest: #32d8b4;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
}
`,
    skipIfExists: true,
  }
}

// ============================================================================
// tsconfig.json for the docs site
// ============================================================================

export function generateDocsTsConfig(): GeneratedDocFile {
  const content = {
    extends: '@docusaurus/tsconfig',
    compilerOptions: {
      baseUrl: '.',
    },
  }

  return {
    path: 'tsconfig.json',
    content: JSON.stringify(content, null, 2) + '\n',
    skipIfExists: true,
  }
}
