/**
 * MST Domain Generator
 *
 * Generates the root store (domain) that combines all collections.
 * Provides createStore() factory function.
 */

import type { PrismaModel } from './prisma-generator'
import { toCamelCase, getIdField } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface GeneratedMSTDomainFile {
  /** File name */
  fileName: string
  /** Generated code */
  code: string
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to file name (kebab-case)
 */
function toFileName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

// ============================================================================
// MST Domain Generator
// ============================================================================

/**
 * Generate MST domain (root store) file
 */
export function generateMSTDomain(models: PrismaModel[]): GeneratedMSTDomainFile {
  const validModels = models.filter(model => getIdField(model))

  const lines: string[] = [
    '/**',
    ' * Auto-generated Domain Store',
    ' *',
    ' * Root MST store combining all collections.',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"',
    'import type { HttpClient } from "@shogo-ai/sdk"',
    '',
    '// Collection imports',
  ]

  // Import all collections
  for (const model of validModels) {
    const fileName = toFileName(model.name)
    lines.push(`import { ${model.name}Collection, type I${model.name}Collection } from "./${fileName}.collection"`)
  }

  lines.push('')
  lines.push('// Model imports (for type re-exports)')

  for (const model of validModels) {
    const fileName = toFileName(model.name)
    lines.push(`export { ${model.name}Model, type I${model.name}, type I${model.name}SnapshotIn, type I${model.name}SnapshotOut } from "./${fileName}.model"`)
  }

  lines.push('')
  lines.push('// Collection type re-exports')

  for (const model of validModels) {
    lines.push(`export { ${model.name}Collection, type I${model.name}Collection }`)
  }

  lines.push('')
  lines.push('// ============================================================================')
  lines.push('// SDK Environment Type')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('/**')
  lines.push(' * Environment interface for SDK MST stores.')
  lines.push(' * Inject this when creating the store.')
  lines.push(' */')
  lines.push('export interface ISDKEnvironment {')
  lines.push('  /** HTTP client for API calls */')
  lines.push('  http: HttpClient')
  lines.push('  /** Optional context for authorization */')
  lines.push('  context?: {')
  lines.push('    userId?: string')
  lines.push('    workspaceId?: string')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('// ============================================================================')
  lines.push('// Root Store')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('/**')
  lines.push(' * Root domain store combining all collections.')
  lines.push(' */')
  lines.push('export const DomainStore = types')
  lines.push('  .model("DomainStore", {')

  // Add collection properties
  for (const model of validModels) {
    const propName = toCamelCase(model.name) + 'Collection'
    lines.push(`    ${propName}: types.optional(${model.name}Collection, { items: {} }),`)
  }

  lines.push('  })')
  lines.push('')
  lines.push('  .views(self => ({')
  lines.push('    /** Get all collection names */')
  lines.push('    get collectionNames(): string[] {')
  lines.push('      return [')
  for (const model of validModels) {
    lines.push(`        "${toCamelCase(model.name)}Collection",`)
  }
  lines.push('      ]')
  lines.push('    },')
  lines.push('  }))')
  lines.push('')
  lines.push('  .actions(self => ({')
  lines.push('    /** Clear all collections */')
  lines.push('    clearAll() {')
  for (const model of validModels) {
    const propName = toCamelCase(model.name) + 'Collection'
    lines.push(`      self.${propName}.clear()`)
  }
  lines.push('    },')
  lines.push('')
  lines.push('    /** Clear all errors */')
  lines.push('    clearAllErrors() {')
  for (const model of validModels) {
    const propName = toCamelCase(model.name) + 'Collection'
    lines.push(`      self.${propName}.clearError()`)
  }
  lines.push('    },')
  lines.push('  }))')
  lines.push('')
  lines.push('// Type exports')
  lines.push('export type IDomainStore = Instance<typeof DomainStore>')
  lines.push('export type IDomainStoreSnapshotIn = SnapshotIn<typeof DomainStore>')
  lines.push('export type IDomainStoreSnapshotOut = SnapshotOut<typeof DomainStore>')
  lines.push('')
  lines.push('// ============================================================================')
  lines.push('// Factory Functions')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('/** Singleton store instance */')
  lines.push('let _store: IDomainStore | null = null')
  lines.push('')
  lines.push('/**')
  lines.push(' * Create a new domain store instance.')
  lines.push(' *')
  lines.push(' * @param env - SDK environment with HttpClient')
  lines.push(' * @returns New domain store instance')
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * ```typescript')
  lines.push(' * import { createDomainStore, type ISDKEnvironment } from "./generated/domain"')
  lines.push(' * import { HttpClient } from "@shogo-ai/sdk"')
  lines.push(' *')
  lines.push(' * const http = new HttpClient({ baseUrl: "http://localhost:3000" })')
  lines.push(' * const store = createDomainStore({ http })')
  lines.push(' *')
  lines.push(' * // Load data')
  lines.push(' * await store.workspaceCollection.loadAll()')
  lines.push(' * console.log(store.workspaceCollection.all)')
  lines.push(' * ```')
  lines.push(' */')
  lines.push('export function createDomainStore(env: ISDKEnvironment): IDomainStore {')
  lines.push('  return DomainStore.create({}, env)')
  lines.push('}')
  lines.push('')
  lines.push('/**')
  lines.push(' * Get or create singleton domain store.')
  lines.push(' *')
  lines.push(' * @param env - SDK environment (required on first call)')
  lines.push(' * @returns Singleton domain store instance')
  lines.push(' */')
  lines.push('export function getDomainStore(env?: ISDKEnvironment): IDomainStore {')
  lines.push('  if (!_store) {')
  lines.push('    if (!env) {')
  lines.push('      throw new Error("SDK environment required to initialize domain store")')
  lines.push('    }')
  lines.push('    _store = createDomainStore(env)')
  lines.push('  }')
  lines.push('  return _store')
  lines.push('}')
  lines.push('')
  lines.push('/**')
  lines.push(' * Reset singleton store (for testing or auth changes)')
  lines.push(' */')
  lines.push('export function resetDomainStore(): void {')
  lines.push('  _store = null')
  lines.push('}')
  lines.push('')

  return {
    fileName: 'domain.ts',
    code: lines.join('\n'),
  }
}
