/**
 * MST Model Generator
 *
 * Generates MobX-State-Tree types.model() definitions from Prisma schema.
 * Each model gets its own file with proper typing and references.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { toCamelCase, getIdField, getScalarFields, getRelationFields } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface GeneratedMSTModelFile {
  /** Model name (e.g., 'Workspace') */
  modelName: string
  /** File name (e.g., 'workspace.model.ts') */
  fileName: string
  /** Generated code */
  code: string
}

export interface PrismaEnum {
  name: string
  values: { name: string }[]
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to file name (kebab-case)
 */
function toFileName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/**
 * Map Prisma type to MST type
 */
function mapPrismaToMSTType(field: PrismaField, enums: PrismaEnum[]): string {
  // Handle enums
  if (field.kind === 'enum') {
    // Find the enum definition to get actual values
    const enumDef = enums.find(e => e.name === field.type)
    const enumType = (enumDef && enumDef.values.length > 0)
      ? `types.enumeration("${field.type}", [${enumDef.values.map(v => `"${v.name}"`).join(', ')}])`
      : `types.string`
    
    // Handle array of enums
    if (field.isList) {
      return `types.array(${enumType})`
    }
    return enumType
  }

  // Handle relations (references to other models)
  if (field.kind === 'object') {
    if (field.isList) {
      return `types.array(types.safeReference(types.late(() => ${field.type}Model)))`
    }
    return `types.safeReference(types.late(() => ${field.type}Model))`
  }

  // Handle scalars
  let baseType: string
  switch (field.type) {
    case 'String':
      baseType = 'types.string'
      break
    case 'Int':
    case 'Float':
    case 'Decimal':
      baseType = 'types.number'
      break
    case 'Boolean':
      baseType = 'types.boolean'
      break
    case 'DateTime':
      baseType = 'types.number' // Store as timestamp
      break
    case 'Json':
      baseType = 'types.frozen()'
      break
    case 'BigInt':
      baseType = 'types.string' // BigInt as string for JSON compatibility
      break
    case 'Bytes':
      baseType = 'types.string' // Base64 encoded
      break
    default:
      baseType = 'types.frozen()'
  }

  // Handle arrays of scalars
  if (field.isList) {
    return `types.array(${baseType})`
  }

  return baseType
}

/**
 * Wrap MST type with optional/maybe if field is not required
 */
function wrapOptional(mstType: string, field: PrismaField): string {
  if (field.isId) {
    return 'types.identifier' // ID fields use types.identifier
  }
  if (!field.isRequired) {
    return `types.maybe(${mstType})`
  }
  return mstType
}

// ============================================================================
// MST Model Generator
// ============================================================================

/**
 * Generate MST model file for a single Prisma model
 *
 * @param model - The Prisma model to generate
 * @param allModels - All Prisma models (for reference resolution)
 * @param enums - All Prisma enums (for enum field values)
 * @param includedModelNames - Set of model names included in config (only import these)
 */
export function generateMSTModel(
  model: PrismaModel,
  allModels: PrismaModel[],
  enums: PrismaEnum[],
  includedModelNames?: Set<string>
): GeneratedMSTModelFile {
  const modelName = model.name
  const fileName = `${toFileName(modelName)}.model.ts`
  
  const scalarFields = getScalarFields(model)
  const relationFields = getRelationFields(model)
  
  // Find which models we need to import for references
  // Only include models that are in the configuration
  const referencedModels = new Set<string>()
  const includedRelationFields: PrismaField[] = []

  for (const field of relationFields) {
    const isIncluded = !includedModelNames || includedModelNames.has(field.type)
    if (field.type !== modelName && isIncluded) {
      referencedModels.add(field.type)
      includedRelationFields.push(field)
    }
  }

  const lines: string[] = [
    '/**',
    ` * Auto-generated ${modelName} MST Model`,
    ' *',
    ' * Generated by @shogo/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"',
  ]

  // Import referenced models (using late() for circular refs)
  // Only import models that are in the configuration
  if (referencedModels.size > 0) {
    lines.push('')
    lines.push('// Referenced models (use types.late() to avoid circular imports)')
    for (const refModel of referencedModels) {
      const refFileName = toFileName(refModel)
      lines.push(`import { ${refModel}Model } from "./${refFileName}.model"`)
    }
  }

  lines.push('')
  lines.push('// ============================================================================')
  lines.push(`// ${modelName} Model`)
  lines.push('// ============================================================================')
  lines.push('')

  // Generate the model definition
  lines.push(`export const ${modelName}Model = types`)
  lines.push(`  .model("${modelName}", {`)

  // Add scalar fields
  for (const field of scalarFields) {
    const mstType = mapPrismaToMSTType(field, enums)
    const wrappedType = wrapOptional(mstType, field)
    
    // Handle array fields - always use types.optional with [] default
    if (field.isList) {
      lines.push(`    ${field.name}: types.optional(${mstType}, []),`)
    }
    // Handle DateTime fields with database defaults (e.g., @default(now()))
    // These should be optional since the server provides the real value
    else if (field.type === 'DateTime' && field.hasDefaultValue && !field.isId) {
      lines.push(`    ${field.name}: types.optional(${mstType}, 0),`)
    }
    // Handle non-array optional fields
    else if (!field.isRequired && !field.isId) {
      // For optional enums, use maybeNull instead of optional with undefined
      if (field.kind === 'enum') {
        lines.push(`    ${field.name}: types.maybeNull(${mstType}),`)
      } else {
        lines.push(`    ${field.name}: types.optional(${mstType}, ${getDefaultValue(field)}),`)
      }
    } else {
      lines.push(`    ${field.name}: ${wrappedType},`)
    }
  }

  // Add relation fields as references (only for included models)
  for (const field of includedRelationFields) {
    const mstType = mapPrismaToMSTType(field, enums)
    if (field.isList) {
      lines.push(`    ${field.name}: types.optional(${mstType}, []),`)
    } else if (!field.isRequired) {
      lines.push(`    ${field.name}: ${mstType},`)
    } else {
      lines.push(`    ${field.name}: ${mstType},`)
    }
  }

  lines.push('  })')

  // Add views
  lines.push('  .views(self => ({')
  lines.push('    /** Check if this is a new/unsaved entity */')
  lines.push('    get isNew(): boolean {')
  lines.push('      return self.id.startsWith("temp-")')
  lines.push('    },')
  lines.push('  }))')

  // Add actions
  lines.push('  .actions(self => ({')
  lines.push('    /** Update entity fields */')
  lines.push('    update(changes: Partial<SnapshotIn<typeof self>>) {')
  lines.push('      Object.assign(self, changes)')
  lines.push('    },')
  lines.push('  }))')

  lines.push('')

  // Export types
  lines.push('// Type exports')
  lines.push(`export interface I${modelName} extends Instance<typeof ${modelName}Model> {}`)
  lines.push(`export interface I${modelName}SnapshotIn extends SnapshotIn<typeof ${modelName}Model> {}`)
  lines.push(`export interface I${modelName}SnapshotOut extends SnapshotOut<typeof ${modelName}Model> {}`)
  lines.push('')

  return {
    modelName,
    fileName,
    code: lines.join('\n'),
  }
}

/**
 * Get default value for optional field
 */
function getDefaultValue(field: PrismaField): string {
  switch (field.type) {
    case 'String':
      return '""'
    case 'Int':
    case 'Float':
    case 'Decimal':
      return '0'
    case 'Boolean':
      return 'false'
    case 'DateTime':
      return '0'
    case 'Json':
      return '{}'
    default:
      return 'undefined'
  }
}

/**
 * Generate MST models for all Prisma models
 *
 * @param models - Prisma models to generate (already filtered to config)
 * @param allModels - All Prisma models (for reference resolution)
 * @param enums - All Prisma enums (for enum field values)
 */
export function generateMSTModels(
  models: PrismaModel[],
  allModels?: PrismaModel[],
  enums: PrismaEnum[] = []
): GeneratedMSTModelFile[] {
  // Create a set of included model names for reference filtering
  const includedModelNames = new Set(models.map(m => m.name))
  const modelsForReference = allModels ?? models

  return models
    .filter(model => getIdField(model)) // Only models with @id
    .map(model => generateMSTModel(model, modelsForReference, enums, includedModelNames))
}
