/**
 * MST Model Generator
 *
 * Generates MobX-State-Tree types.model() definitions from Prisma schema.
 * Each model gets its own file with proper typing and references.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { toCamelCase, getIdField, getScalarFields, getRelationFields } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface GeneratedMSTModelFile {
  /** Model name (e.g., 'Workspace') */
  modelName: string
  /** File name (e.g., 'workspace.model.ts') */
  fileName: string
  /** Generated code */
  code: string
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to file name (kebab-case)
 */
function toFileName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/**
 * Map Prisma type to MST type
 */
function mapPrismaToMSTType(field: PrismaField): string {
  // Handle enums
  if (field.kind === 'enum') {
    return `types.enumeration("${field.type}", [/* enum values */])`
  }

  // Handle relations (references to other models)
  if (field.kind === 'object') {
    if (field.isList) {
      return `types.array(types.safeReference(types.late(() => ${field.type}Model)))`
    }
    return `types.safeReference(types.late(() => ${field.type}Model))`
  }

  // Handle scalars
  switch (field.type) {
    case 'String':
      return 'types.string'
    case 'Int':
    case 'Float':
    case 'Decimal':
      return 'types.number'
    case 'Boolean':
      return 'types.boolean'
    case 'DateTime':
      return 'types.number' // Store as timestamp
    case 'Json':
      return 'types.frozen()'
    case 'BigInt':
      return 'types.string' // BigInt as string for JSON compatibility
    case 'Bytes':
      return 'types.string' // Base64 encoded
    default:
      return 'types.frozen()'
  }
}

/**
 * Wrap MST type with optional/maybe if field is not required
 */
function wrapOptional(mstType: string, field: PrismaField): string {
  if (field.isId) {
    return 'types.identifier' // ID fields use types.identifier
  }
  if (!field.isRequired) {
    return `types.maybe(${mstType})`
  }
  return mstType
}

// ============================================================================
// MST Model Generator
// ============================================================================

/**
 * Generate MST model file for a single Prisma model
 */
export function generateMSTModel(
  model: PrismaModel,
  allModels: PrismaModel[]
): GeneratedMSTModelFile {
  const modelName = model.name
  const fileName = `${toFileName(modelName)}.model.ts`
  
  const scalarFields = getScalarFields(model)
  const relationFields = getRelationFields(model)
  
  // Find which models we need to import for references
  const referencedModels = new Set<string>()
  for (const field of relationFields) {
    if (field.type !== modelName) { // Don't import self
      referencedModels.add(field.type)
    }
  }

  const lines: string[] = [
    '/**',
    ` * Auto-generated ${modelName} MST Model`,
    ' *',
    ' * Generated by @shogo/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { types, Instance, SnapshotIn, SnapshotOut } from "mobx-state-tree"',
  ]

  // Import referenced models (using late() for circular refs)
  if (referencedModels.size > 0) {
    lines.push('')
    lines.push('// Referenced models (use types.late() to avoid circular imports)')
    for (const refModel of referencedModels) {
      const refFileName = toFileName(refModel)
      lines.push(`import { ${refModel}Model } from "./${refFileName}.model"`)
    }
  }

  lines.push('')
  lines.push('// ============================================================================')
  lines.push(`// ${modelName} Model`)
  lines.push('// ============================================================================')
  lines.push('')

  // Generate the model definition
  lines.push(`export const ${modelName}Model = types`)
  lines.push(`  .model("${modelName}", {`)

  // Add scalar fields
  for (const field of scalarFields) {
    const mstType = mapPrismaToMSTType(field)
    const wrappedType = wrapOptional(mstType, field)
    
    // Add default value for optional fields
    if (!field.isRequired && !field.isId) {
      lines.push(`    ${field.name}: types.optional(${mstType}, ${getDefaultValue(field)}),`)
    } else {
      lines.push(`    ${field.name}: ${wrappedType},`)
    }
  }

  // Add relation fields as references
  for (const field of relationFields) {
    const mstType = mapPrismaToMSTType(field)
    if (field.isList) {
      lines.push(`    ${field.name}: types.optional(${mstType}, []),`)
    } else if (!field.isRequired) {
      lines.push(`    ${field.name}: ${mstType},`)
    } else {
      lines.push(`    ${field.name}: ${mstType},`)
    }
  }

  lines.push('  })')

  // Add views
  lines.push('  .views(self => ({')
  lines.push('    /** Check if this is a new/unsaved entity */')
  lines.push('    get isNew(): boolean {')
  lines.push('      return self.id.startsWith("temp-")')
  lines.push('    },')
  lines.push('  }))')

  // Add actions
  lines.push('  .actions(self => ({')
  lines.push('    /** Update entity fields */')
  lines.push('    update(changes: Partial<SnapshotIn<typeof self>>) {')
  lines.push('      Object.assign(self, changes)')
  lines.push('    },')
  lines.push('  }))')

  lines.push('')

  // Export types
  lines.push('// Type exports')
  lines.push(`export interface I${modelName} extends Instance<typeof ${modelName}Model> {}`)
  lines.push(`export interface I${modelName}SnapshotIn extends SnapshotIn<typeof ${modelName}Model> {}`)
  lines.push(`export interface I${modelName}SnapshotOut extends SnapshotOut<typeof ${modelName}Model> {}`)
  lines.push('')

  return {
    modelName,
    fileName,
    code: lines.join('\n'),
  }
}

/**
 * Get default value for optional field
 */
function getDefaultValue(field: PrismaField): string {
  switch (field.type) {
    case 'String':
      return '""'
    case 'Int':
    case 'Float':
    case 'Decimal':
      return '0'
    case 'Boolean':
      return 'false'
    case 'DateTime':
      return '0'
    case 'Json':
      return '{}'
    default:
      return 'undefined'
  }
}

/**
 * Generate MST models for all Prisma models
 */
export function generateMSTModels(models: PrismaModel[]): GeneratedMSTModelFile[] {
  return models
    .filter(model => getIdField(model)) // Only models with @id
    .map(model => generateMSTModel(model, models))
}
