/**
 * Hono Routes Generator (Per-Model)
 *
 * Generates one route file per Prisma model with CRUD operations.
 * Adapted from @shogo/state-api for SDK consolidation.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { toCamelCase, getIdField } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface RouteGeneratorConfig {
  /** Base path for routes (default: '/api') */
  basePath?: string
  /** File extension: 'ts' or 'tsx' (default: 'tsx') */
  fileExtension?: 'ts' | 'tsx'
}

export interface GeneratedRouteFile {
  /** Model name (e.g., 'Workspace') */
  modelName: string
  /** File name (e.g., 'workspace.routes.ts') */
  fileName: string
  /** Generated code */
  code: string
}

export interface GeneratedHooksFile {
  /** Model name (e.g., 'Workspace') */
  modelName: string
  /** File name (e.g., 'workspace.hooks.ts') */
  fileName: string
  /** Generated code */
  code: string
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to route path (kebab-case, plural)
 */
function toRoutePath(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  // Simple pluralization
  if (kebab.endsWith('y')) return kebab.slice(0, -1) + 'ies'
  if (kebab.endsWith('s') || kebab.endsWith('x') || kebab.endsWith('ch') || kebab.endsWith('sh')) {
    return kebab + 'es'
  }
  return kebab + 's'
}

/**
 * Convert model name to file name (kebab-case)
 */
function toFileName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

// ============================================================================
// Route Generator (Per-Model)
// ============================================================================

/**
 * Generate route file for a single model
 */
export function generateModelRoutes(
  model: PrismaModel,
  config: RouteGeneratorConfig = {}
): GeneratedRouteFile | null {
  const idField = getIdField(model)
  if (!idField) {
    return null // Skip models without @id
  }

  const modelName = model.name
  const modelLower = toCamelCase(modelName)
  const ext = config.fileExtension || 'tsx'
  const fileName = `${toFileName(modelName)}.routes.${ext}`

  const lines: string[] = [
    '/**',
    ` * Auto-generated ${modelName} Routes`,
    ' *',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { Hono } from "hono"',
    'import { PrismaClient } from "./prisma/client"',
    `import type { ${modelName}Hooks } from "./${toFileName(modelName)}.hooks"`,
    '',
    '// Prisma client instance (injected)',
    'let prisma: PrismaClient | null = null',
    '',
    `let hooks: ${modelName}Hooks = {}`,
    '',
    '/**',
    ' * Set the Prisma client instance',
    ' */',
    'export function setPrisma(client: PrismaClient) {',
    '  prisma = client',
    '}',
    '',
    '/**',
    ` * Set hooks for ${modelName} routes`,
    ' */',
    `export function set${modelName}Hooks(h: ${modelName}Hooks) {`,
    '  hooks = h',
    '}',
    '',
    '/**',
    ' * Get Prisma client (throws if not set)',
    ' */',
    'function getPrisma(): PrismaClient {',
    '  if (!prisma) {',
    '    throw new Error("Prisma client not set. Call setPrisma() first.")',
    '  }',
    '  return prisma',
    '}',
    '',
    '/**',
    ' * Build route context from Hono context',
    ' */',
    'function buildContext(c: any, body?: any) {',
    '  return {',
    '    body: body || {},',
    '    params: c.req.param() || {},',
    '    query: Object.fromEntries(new URL(c.req.url).searchParams),',
    '    userId: c.get("auth")?.userId,',
    '    prisma: getPrisma(),',
    '  }',
    '}',
    '',
    '/**',
    ` * Create ${modelName} CRUD routes`,
    ' */',
    `export function create${modelName}Routes(): Hono {`,
    '  const router = new Hono()',
    '',
  ]

  // LIST route
  lines.push('  // GET / - List all')
  lines.push('  router.get("/", async (c) => {')
  lines.push('    try {')
  lines.push('      const ctx = buildContext(c)')
  lines.push('      const prisma = getPrisma()')
  lines.push('      const query = ctx.query')
  lines.push('      ')
  lines.push('      // Build initial where from query params (exclude pagination/meta params)')
  lines.push('      const reservedParams = ["limit", "offset", "userId", "include", "orderBy"]')
  lines.push('      let where: any = {}')
  lines.push('      ')
  lines.push('      for (const [key, value] of Object.entries(query)) {')
  lines.push('        if (!reservedParams.includes(key) && value !== undefined && value !== null && value !== "") {')
  lines.push('          // Try to parse as number or boolean')
  lines.push('          let parsedValue: any = value')
  lines.push('          if (value === "true") parsedValue = true')
  lines.push('          else if (value === "false") parsedValue = false')
  lines.push('          else if (!isNaN(Number(value)) && value !== "") parsedValue = Number(value)')
  lines.push('          ')
  lines.push('          where[key] = parsedValue')
  lines.push('        }')
  lines.push('      }')
  lines.push('      ')
  lines.push('      let include: any = undefined')
  lines.push('')
  lines.push('      // Apply beforeList hook (can override where/include)')
  lines.push('      if (hooks.beforeList) {')
  lines.push('        const result = await hooks.beforeList(ctx)')
  lines.push('        if (result && !result.ok) {')
  lines.push('          return c.json({ error: result.error }, 400)')
  lines.push('        }')
  lines.push('        if (result?.data) {')
  lines.push('          where = result.data.where || where')
  lines.push('          include = result.data.include || include')
  lines.push('        }')
  lines.push('      }')
  lines.push('')
  lines.push(`      const items = await prisma.${modelLower}.findMany({`)
  lines.push('        where,')
  lines.push('        include,')
  lines.push('        take: query.limit ? parseInt(query.limit) : undefined,')
  lines.push('        skip: query.offset ? parseInt(query.offset) : undefined,')
  lines.push('      })')
  lines.push('')
  lines.push('      return c.json({ ok: true, items })')
  lines.push('    } catch (error: any) {')
  lines.push(`      console.error("[${modelName}] List error:", error)`)
  lines.push('      return c.json({ error: { code: "list_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  // GET route
  lines.push('  // GET /:id - Get by ID')
  lines.push('  router.get("/:id", async (c) => {')
  lines.push('    try {')
  lines.push('      const id = c.req.param("id")')
  lines.push('      const ctx = buildContext(c)')
  lines.push('      const prisma = getPrisma()')
  lines.push('')
  lines.push('      // Apply beforeGet hook')
  lines.push('      if (hooks.beforeGet) {')
  lines.push('        const result = await hooks.beforeGet(id, ctx)')
  lines.push('        if (result && !result.ok) {')
  lines.push('          return c.json({ error: result.error }, result.error?.code === "not_found" ? 404 : 400)')
  lines.push('        }')
  lines.push('      }')
  lines.push('')
  lines.push(`      const item = await prisma.${modelLower}.findUnique({`)
  lines.push('        where: { id },')
  lines.push('      })')
  lines.push('')
  lines.push('      if (!item) {')
  lines.push(`        return c.json({ error: { code: "not_found", message: "${modelName} not found" } }, 404)`)
  lines.push('      }')
  lines.push('')
  lines.push('      return c.json({ ok: true, data: item })')
  lines.push('    } catch (error: any) {')
  lines.push(`      console.error("[${modelName}] Get error:", error)`)
  lines.push('      return c.json({ error: { code: "get_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  // CREATE route
  lines.push('  // POST / - Create')
  lines.push('  router.post("/", async (c) => {')
  lines.push('    try {')
  lines.push('      let body = await c.req.json()')
  lines.push('      const ctx = buildContext(c, body)')
  lines.push('      const prisma = getPrisma()')
  lines.push('')
  lines.push('      // Apply beforeCreate hook')
  lines.push('      if (hooks.beforeCreate) {')
  lines.push('        const result = await hooks.beforeCreate(body, ctx)')
  lines.push('        if (result && !result.ok) {')
  lines.push('          return c.json({ error: result.error }, 400)')
  lines.push('        }')
  lines.push('        if (result?.data) {')
  lines.push('          body = result.data')
  lines.push('        }')
  lines.push('      }')
  lines.push('')
  lines.push(`      const item = await prisma.${modelLower}.create({`)
  lines.push('        data: body,')
  lines.push('      })')
  lines.push('')
  lines.push('      // Apply afterCreate hook')
  lines.push('      if (hooks.afterCreate) {')
  lines.push('        await hooks.afterCreate(item, ctx)')
  lines.push('      }')
  lines.push('')
  lines.push('      return c.json({ ok: true, data: item }, 201)')
  lines.push('    } catch (error: any) {')
  lines.push(`      console.error("[${modelName}] Create error:", error)`)
  lines.push('      return c.json({ error: { code: "create_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  // UPDATE route
  lines.push('  // PATCH /:id - Update')
  lines.push('  router.patch("/:id", async (c) => {')
  lines.push('    try {')
  lines.push('      const id = c.req.param("id")')
  lines.push('      let body = await c.req.json()')
  lines.push('      const ctx = buildContext(c, body)')
  lines.push('      const prisma = getPrisma()')
  lines.push('')
  lines.push('      // Apply beforeUpdate hook')
  lines.push('      if (hooks.beforeUpdate) {')
  lines.push('        const result = await hooks.beforeUpdate(id, body, ctx)')
  lines.push('        if (result && !result.ok) {')
  lines.push('          return c.json({ error: result.error }, 400)')
  lines.push('        }')
  lines.push('        if (result?.data) {')
  lines.push('          body = result.data')
  lines.push('        }')
  lines.push('      }')
  lines.push('')
  lines.push(`      const item = await prisma.${modelLower}.update({`)
  lines.push('        where: { id },')
  lines.push('        data: body,')
  lines.push('      })')
  lines.push('')
  lines.push('      // Apply afterUpdate hook')
  lines.push('      if (hooks.afterUpdate) {')
  lines.push('        await hooks.afterUpdate(item, ctx)')
  lines.push('      }')
  lines.push('')
  lines.push('      return c.json({ ok: true, data: item })')
  lines.push('    } catch (error: any) {')
  lines.push(`      console.error("[${modelName}] Update error:", error)`)
  lines.push('      return c.json({ error: { code: "update_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  // DELETE route
  lines.push('  // DELETE /:id - Delete')
  lines.push('  router.delete("/:id", async (c) => {')
  lines.push('    try {')
  lines.push('      const id = c.req.param("id")')
  lines.push('      const ctx = buildContext(c)')
  lines.push('      const prisma = getPrisma()')
  lines.push('')
  lines.push('      // Apply beforeDelete hook')
  lines.push('      if (hooks.beforeDelete) {')
  lines.push('        const result = await hooks.beforeDelete(id, ctx)')
  lines.push('        if (result && !result.ok) {')
  lines.push('          return c.json({ error: result.error }, 400)')
  lines.push('        }')
  lines.push('      }')
  lines.push('')
  lines.push(`      await prisma.${modelLower}.delete({`)
  lines.push('        where: { id },')
  lines.push('      })')
  lines.push('')
  lines.push('      // Apply afterDelete hook')
  lines.push('      if (hooks.afterDelete) {')
  lines.push('        await hooks.afterDelete(id, ctx)')
  lines.push('      }')
  lines.push('')
  lines.push('      return c.json({ ok: true })')
  lines.push('    } catch (error: any) {')
  lines.push(`      console.error("[${modelName}] Delete error:", error)`)
  lines.push('      return c.json({ error: { code: "delete_failed", message: error.message } }, 500)')
  lines.push('    }')
  lines.push('  })')
  lines.push('')

  lines.push('  return router')
  lines.push('}')
  lines.push('')

  return {
    modelName,
    fileName,
    code: lines.join('\n'),
  }
}

/**
 * Generate hooks file for a single model
 */
export function generateModelHooks(model: PrismaModel, config: RouteGeneratorConfig = {}): GeneratedHooksFile {
  const modelName = model.name
  const ext = config.fileExtension || 'tsx'
  const fileName = `${toFileName(modelName)}.hooks.${ext}`

  const lines: string[] = [
    '/**',
    ` * ${modelName} Hooks`,
    ' *',
    ' * Customize business logic for CRUD operations.',
    ' * This file is safe to edit - it will not be overwritten.',
    ' */',
    '',
    '/**',
    ' * Result from a hook that can modify or reject the operation',
    ' */',
    'export interface HookResult<T = any> {',
    '  ok: boolean',
    '  error?: { code: string; message: string }',
    '  data?: T',
    '}',
    '',
    '/**',
    ` * Hook context with Prisma client`,
    ' */',
    'export interface HookContext {',
    '  body: any',
    '  params: Record<string, string>',
    '  query: Record<string, string>',
    '  userId?: string',
    '  prisma: any',
    '}',
    '',
    '/**',
    ` * Hooks for ${modelName} routes`,
    ' */',
    `export interface ${modelName}Hooks {`,
    '  /**',
    '   * Called before listing records. Can modify where/include.',
    '   * Note: Query parameters (except limit, offset, userId, include, orderBy) are automatically',
    '   * added to the where clause. This hook receives them and can override/extend them.',
    '   */',
    '  beforeList?: (ctx: HookContext) => Promise<HookResult<{ where?: any; include?: any }> | void>',
    '  /** Called before getting a single record. Can reject access. */',
    '  beforeGet?: (id: string, ctx: HookContext) => Promise<HookResult | void>',
    '  /** Called before creating a record. Can modify input or reject. */',
    '  beforeCreate?: (input: any, ctx: HookContext) => Promise<HookResult<any> | void>',
    '  /** Called after creating a record. Can perform side effects. */',
    '  afterCreate?: (record: any, ctx: HookContext) => Promise<void>',
    '  /** Called before updating a record. Can modify input or reject. */',
    '  beforeUpdate?: (id: string, input: any, ctx: HookContext) => Promise<HookResult<any> | void>',
    '  /** Called after updating a record. Can perform side effects. */',
    '  afterUpdate?: (record: any, ctx: HookContext) => Promise<void>',
    '  /** Called before deleting a record. Can reject deletion. */',
    '  beforeDelete?: (id: string, ctx: HookContext) => Promise<HookResult | void>',
    '  /** Called after deleting a record. Can perform cleanup. */',
    '  afterDelete?: (id: string, ctx: HookContext) => Promise<void>',
    '}',
    '',
    '/**',
    ` * Default ${modelName} hooks (customize as needed)`,
    ' */',
    `export const ${toCamelCase(modelName)}Hooks: ${modelName}Hooks = {`,
    '  // beforeList: async (ctx) => {',
    '  //   // Query params are automatically added to where clause',
    '  //   // Example: GET /api/projects?workspaceId=123 => where: { workspaceId: "123" }',
    '  //   ',
    '  //   // You can override or extend the where clause:',
    '  //   // return { ok: true, data: { where: { ...ctx.query, userId: ctx.userId } } }',
    '  // },',
    '  // beforeCreate: async (input, ctx) => {',
    '  //   // Set userId on create',
    '  //   return { ok: true, data: { ...input, userId: ctx.userId } }',
    '  // },',
    '}',
    '',
  ]

  return {
    modelName,
    fileName,
    code: lines.join('\n'),
  }
}

/**
 * Generate routes for all models
 */
export function generateRoutes(
  models: PrismaModel[],
  config: RouteGeneratorConfig = {}
): { routes: GeneratedRouteFile[]; hooks: GeneratedHooksFile[] } {
  const routes: GeneratedRouteFile[] = []
  const hooks: GeneratedHooksFile[] = []

  for (const model of models) {
    const routeFile = generateModelRoutes(model, config)
    if (routeFile) {
      routes.push(routeFile)
      hooks.push(generateModelHooks(model, config))
    }
  }

  return { routes, hooks }
}

/**
 * Generate index file for routes
 */
export function generateRoutesIndex(models: PrismaModel[]): string {
  // Filter to only models with @id field (skip composite key models)
  const routeModels = models.filter(model => getIdField(model) !== undefined)

  const lines: string[] = [
    '/**',
    ' * Auto-generated Routes Index',
    ' *',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { Hono } from "hono"',
    'import { PrismaClient } from "./prisma/client"',
    '',
    '// Route imports',
  ]

  for (const model of routeModels) {
    const fileName = toFileName(model.name)
    lines.push(`import { create${model.name}Routes, setPrisma as setPrisma${model.name}, set${model.name}Hooks } from "./${fileName}.routes"`)
  }

  lines.push('')
  lines.push('// Hook imports')

  for (const model of routeModels) {
    const fileName = toFileName(model.name)
    const hookVarName = toCamelCase(model.name) + 'Hooks'
    lines.push(`import { ${hookVarName} } from "./${fileName}.hooks"`)
  }

  lines.push('')
  lines.push('// Re-export route creators and setters')
  lines.push('export {')
  
  const routeExports: string[] = []
  for (const model of routeModels) {
    routeExports.push(`  create${model.name}Routes`)
    routeExports.push(`  setPrisma${model.name}`)
    routeExports.push(`  set${model.name}Hooks`)
  }
  lines.push(routeExports.join(',\n'))
  lines.push('}')

  lines.push('')
  lines.push('// Re-export hooks (model-specific)')
  lines.push('export {')
  
  const hookExports: string[] = []
  for (const model of routeModels) {
    const hookVarName = toCamelCase(model.name) + 'Hooks'
    hookExports.push(`  ${hookVarName}`)
  }
  lines.push(hookExports.join(',\n'))
  lines.push('}')

  lines.push('')
  lines.push('// Re-export hook types')
  for (const model of routeModels) {
    const fileName = toFileName(model.name)
    lines.push(`export type { ${model.name}Hooks } from "./${fileName}.hooks"`)
  }

  lines.push('')
  lines.push('/**')
  lines.push(' * Create all routes and mount them on a single Hono app')
  lines.push(' */')
  lines.push('export function createAllRoutes(prisma: PrismaClient): Hono {')
  lines.push('  const app = new Hono()')
  lines.push('')
  lines.push('  // Set Prisma client for all routes')

  for (const model of routeModels) {
    lines.push(`  setPrisma${model.name}(prisma)`)
  }

  lines.push('')
  lines.push('  // Set hooks for all routes')

  for (const model of routeModels) {
    const hookVarName = toCamelCase(model.name) + 'Hooks'
    lines.push(`  set${model.name}Hooks(${hookVarName})`)
  }

  lines.push('')
  lines.push('  // Mount routes')

  for (const model of routeModels) {
    const routePath = toRoutePath(model.name)
    lines.push(`  app.route("/${routePath}", create${model.name}Routes())`)
  }

  lines.push('')
  lines.push('  return app')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
