/**
 * Hono Server Generator
 *
 * Generates a complete Hono server entry point that:
 * - Sets up CORS middleware
 * - Adds health endpoint
 * - Mounts SDK-generated routes at /api
 * - Serves static files for production
 * - Exports Bun-compatible server
 */

export interface ServerGeneratorConfig {
  /** Port to run server on (default: 3000) */
  port?: number
  /** Enable CORS (default: true) */
  cors?: boolean
  /** CORS origins (default: localhost:5173, localhost:3000) */
  corsOrigins?: string[]
  /** Path to generated routes (default: './src/generated') */
  routesPath?: string
  /** Path to Prisma db module (default: './src/lib/db') */
  dbPath?: string
  /** API base path (default: '/api') */
  apiBasePath?: string
  /** Static files directory (default: './dist') */
  staticDir?: string
}

/**
 * Generate Hono server entry point
 */
export function generateServer(config: ServerGeneratorConfig = {}): string {
  const {
    port = 3000,
    cors = true,
    corsOrigins = ['http://localhost:5173', 'http://localhost:3000'],
    routesPath = './src/generated',
    dbPath = './src/lib/db',
    apiBasePath = '/api',
    staticDir = './dist',
  } = config

  const lines: string[] = [
    '/**',
    ' * Hono Server',
    ' *',
    ' * Auto-generated by @shogo-ai/sdk',
    ' * This file can be customized - it will not be overwritten if it exists.',
    ' */',
    '',
    "import { Hono } from 'hono'",
  ]

  if (cors) {
    lines.push("import { cors } from 'hono/cors'")
  }

  lines.push("import { serveStatic } from 'hono/bun'")
  lines.push(`import { createAllRoutes } from '${routesPath}'`)
  lines.push(`import { prisma } from '${dbPath}'`)
  lines.push('')
  lines.push('const app = new Hono()')
  lines.push('')

  if (cors) {
    lines.push('// CORS middleware')
    lines.push('app.use(')
    lines.push("  '*',")
    lines.push('  cors({')
    lines.push(`    origin: ${JSON.stringify(corsOrigins)},`)
    lines.push("    allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],")
    lines.push("    allowHeaders: ['Content-Type', 'Authorization'],")
    lines.push('    credentials: true,')
    lines.push('  })')
    lines.push(')')
    lines.push('')
  }

  lines.push('// Health check endpoint')
  lines.push("app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))")
  lines.push('')

  lines.push('// Mount SDK-generated API routes')
  lines.push(`app.route('${apiBasePath}', createAllRoutes(prisma))`)
  lines.push('')

  lines.push('// Serve static files in production')
  lines.push(`app.use('/*', serveStatic({ root: '${staticDir}' }))`)
  lines.push(`app.get('*', serveStatic({ path: '${staticDir}/index.html' }))`)
  lines.push('')

  lines.push(`const port = Number(process.env.PORT) || ${port}`)
  lines.push('console.log(`🚀 Server running on http://localhost:${port}`)')
  lines.push('')

  lines.push('export default {')
  lines.push('  port,')
  lines.push('  fetch: app.fetch,')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate Prisma database module
 */
export function generateDbModule(): string {
  return `/**
 * Prisma Database Client
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../generated/prisma/client'

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
}

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
})

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    adapter,
    log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
`
}
