/**
 * Client-Side Server Functions Generator
 *
 * Generates fetch-based CRUD client functions for each Prisma model.
 * These functions call the Hono REST API routes (e.g., /api/users, /api/todos)
 * instead of importing Prisma directly, keeping Node.js modules out of the
 * browser bundle.
 *
 * The generated functions maintain the same call signature as the previous
 * createServerFn-based versions so domain.ts doesn't need changes.
 */

import type { PrismaModel, PrismaField } from './prisma-generator'
import { toCamelCase, getIdField, getScalarFields } from './prisma-generator'

/**
 * Simple pluralization matching the routes-generator convention
 */
function toRoutePath(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  if (kebab.endsWith('y')) return kebab.slice(0, -1) + 'ies'
  if (kebab.endsWith('s') || kebab.endsWith('x') || kebab.endsWith('ch') || kebab.endsWith('sh')) {
    return kebab + 'es'
  }
  return kebab + 's'
}

/**
 * Generate server functions code for all models
 */
export function generateServerFunctions(models: PrismaModel[]): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated Client Functions',
    ' *',
    ' * Fetch-based CRUD operations that call the Hono REST API.',
    ' * No server-side imports — safe for browser bundles.',
    ' * Generated by `shogo generate` - DO NOT EDIT',
    ' */',
    '',
    'import type {',
  ]

  // Import types
  for (const model of models) {
    lines.push(`  ${model.name}Type,`)
    lines.push(`  ${model.name}CreateInput,`)
    lines.push(`  ${model.name}UpdateInput,`)
  }
  lines.push('} from \'./types\'')
  lines.push('')

  // Helper function for API base URL
  lines.push('/** Get the API base URL */') 
  lines.push('function getApiBase(): string {')
  lines.push('  if (typeof window !== \'undefined\') {')
  lines.push('    return window.location.origin')
  lines.push('  }')
  lines.push('  return process.env.API_URL || \'http://localhost:3001\'')
  lines.push('}')
  lines.push('')

  // Generate functions for each model
  for (const model of models) {
    lines.push(...generateModelFunctions(model))
  }

  return lines.join('\n')
}

/**
 * Generate CRUD functions for a single model
 */
function generateModelFunctions(model: PrismaModel): string[] {
  const name = model.name
  const nameLower = toCamelCase(name)
  const routePath = toRoutePath(name)
  const idField = getIdField(model)
  
  if (!idField) {
    return [`// Skipped ${name} - no @id field found`, '']
  }

  const lines: string[] = [
    `// ============================================================================`,
    `// ${name} Client Functions`,
    `// ============================================================================`,
    '',
  ]

  // LIST function
  lines.push(...generateListFunction(model, routePath))

  // GET function
  lines.push(...generateGetFunction(model, routePath))

  // CREATE function
  lines.push(...generateCreateFunction(model, routePath))

  // UPDATE function
  lines.push(...generateUpdateFunction(model, routePath))

  // DELETE function
  lines.push(...generateDeleteFunction(model, routePath))

  return lines
}

function generateListFunction(model: PrismaModel, routePath: string): string[] {
  const name = model.name

  return [
    `/**`,
    ` * List all ${name} records`,
    ` */`,
    `export async function get${name}List(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<${name}Type[]> {`,
    `  const params = new URLSearchParams()`,
    `  if (args.data.userId) params.set('userId', args.data.userId)`,
    `  if (args.data.where) {`,
    `    for (const [key, value] of Object.entries(args.data.where)) {`,
    `      if (value !== undefined && value !== null) params.set(key, String(value))`,
    `    }`,
    `  }`,
    `  const qs = params.toString()`,
    `  const url = \`\${getApiBase()}/api/${routePath}\${qs ? \`?\${qs}\` : ''}\``,
    `  const response = await fetch(url)`,
    `  if (!response.ok) {`,
    `    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))`,
    `    throw new Error(err.error?.message || 'Failed to list ${name}')`,
    `  }`,
    `  const json = await response.json()`,
    `  return (json.items || []) as ${name}Type[]`,
    `}`,
    '',
  ]
}

function generateGetFunction(model: PrismaModel, routePath: string): string[] {
  const name = model.name

  return [
    `/**`,
    ` * Get a single ${name} by ID`,
    ` */`,
    `export async function get${name}ById(args: { data: { id: string; userId?: string } }): Promise<${name}Type> {`,
    `  const url = \`\${getApiBase()}/api/${routePath}/\${args.data.id}\``,
    `  const response = await fetch(url)`,
    `  if (!response.ok) {`,
    `    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))`,
    `    throw new Error(err.error?.message || '${name} not found')`,
    `  }`,
    `  const json = await response.json()`,
    `  return json.data as ${name}Type`,
    `}`,
    '',
  ]
}

function generateCreateFunction(model: PrismaModel, routePath: string): string[] {
  const name = model.name

  return [
    `/**`,
    ` * Create a new ${name}`,
    ` */`,
    `export async function create${name}(args: { data: { input: ${name}CreateInput; userId?: string } }): Promise<${name}Type> {`,
    `  const url = \`\${getApiBase()}/api/${routePath}\``,
    `  const response = await fetch(url, {`,
    `    method: 'POST',`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `    body: JSON.stringify(args.data.input),`,
    `  })`,
    `  if (!response.ok) {`,
    `    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))`,
    `    throw new Error(err.error?.message || 'Failed to create ${name}')`,
    `  }`,
    `  const json = await response.json()`,
    `  return json.data as ${name}Type`,
    `}`,
    '',
  ]
}

function generateUpdateFunction(model: PrismaModel, routePath: string): string[] {
  const name = model.name

  return [
    `/**`,
    ` * Update an existing ${name}`,
    ` */`,
    `export async function update${name}(args: { data: { id: string; input: ${name}UpdateInput; userId?: string } }): Promise<${name}Type> {`,
    `  const url = \`\${getApiBase()}/api/${routePath}/\${args.data.id}\``,
    `  const response = await fetch(url, {`,
    `    method: 'PATCH',`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `    body: JSON.stringify(args.data.input),`,
    `  })`,
    `  if (!response.ok) {`,
    `    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))`,
    `    throw new Error(err.error?.message || 'Failed to update ${name}')`,
    `  }`,
    `  const json = await response.json()`,
    `  return json.data as ${name}Type`,
    `}`,
    '',
  ]
}

function generateDeleteFunction(model: PrismaModel, routePath: string): string[] {
  const name = model.name

  return [
    `/**`,
    ` * Delete a ${name}`,
    ` */`,
    `export async function delete${name}(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {`,
    `  const url = \`\${getApiBase()}/api/${routePath}/\${args.data.id}\``,
    `  const response = await fetch(url, {`,
    `    method: 'DELETE',`,
    `  })`,
    `  if (!response.ok) {`,
    `    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))`,
    `    throw new Error(err.error?.message || 'Failed to delete ${name}')`,
    `  }`,
    `  return { success: true }`,
    `}`,
    '',
  ]
}
