// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Hono Server Generator
 *
 * Generates a complete Hono server entry point that:
 * - Sets up CORS middleware
 * - Adds health endpoint
 * - Mounts SDK-generated routes at /api
 * - Serves static files for production
 * - Exports Bun-compatible server
 */

export interface ServerGeneratorConfig {
  /** Port to run server on (default: 3000) */
  port?: number
  /** Enable CORS (default: true) */
  cors?: boolean
  /** CORS origins (default: localhost:5173, localhost:3000) */
  corsOrigins?: string[]
  /** Path to generated routes (default: './src/generated') */
  routesPath?: string
  /** Path to Prisma db module (default: './src/lib/db') */
  dbPath?: string
  /** API base path (default: '/api') */
  apiBasePath?: string
  /** Static files directory (default: './dist') */
  staticDir?: string
  /** Skip static file serving (useful for API-only servers) */
  skipStatic?: boolean
}

/**
 * Generate Hono server entry point
 */
export function generateServer(config: ServerGeneratorConfig = {}): string {
  const {
    port = 3000,
    cors = true,
    corsOrigins = ['http://localhost:5173', 'http://localhost:3000'],
    routesPath = './src/generated',
    dbPath = './src/lib/db',
    apiBasePath = '/api',
    staticDir = './dist',
    skipStatic = false,
  } = config

  const lines: string[] = [
    '/**',
    ' * Hono Server',
    ' *',
    ' * Auto-generated by @shogo-ai/sdk',
    ' * This file can be customized - it will not be overwritten if it exists.',
    ' */',
    '',
    "import { Hono } from 'hono'",
  ]

  // cors import intentionally omitted — using manual middleware for reliable wildcard support

  if (!skipStatic) {
    lines.push("import { serveStatic } from 'hono/bun'")
  }
  lines.push(`import { createAllRoutes } from '${routesPath}'`)
  lines.push(`import { prisma } from '${dbPath}'`)
  lines.push('')
  lines.push('const app = new Hono()')
  lines.push('')

  if (cors) {
    lines.push('// CORS — manual middleware so the wildcard always propagates')
    lines.push("app.use('*', async (c, next) => {")
    lines.push("  c.res.headers.set('Access-Control-Allow-Origin', '*')")
    lines.push("  c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')")
    lines.push("  c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization')")
    lines.push("  if (c.req.method === 'OPTIONS') return c.text('', 204)")
    lines.push('  await next()')
    lines.push('})')
    lines.push('')
  }

  lines.push('// Health check endpoint')
  lines.push("app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))")
  lines.push('')

  lines.push('// Mount SDK-generated API routes')
  lines.push(`app.route('${apiBasePath}', createAllRoutes(prisma))`)
  lines.push('')

  if (!skipStatic) {
    lines.push('// Serve static files in production')
    lines.push(`app.use('/*', serveStatic({ root: '${staticDir}' }))`)
    lines.push(`app.get('*', serveStatic({ path: '${staticDir}/index.html' }))`)
    lines.push('')
  }

  lines.push(`const port = Number(process.env.PORT) || ${port}`)
  lines.push('console.log(`🚀 Server running on http://localhost:${port}`)')
  lines.push('')

  lines.push('export default {')
  lines.push('  port,')
  lines.push('  fetch: app.fetch,')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate Prisma database module (PostgreSQL with adapter)
 */
export function generateDbModule(): string {
  const lines = [
    '/**',
    ' * Prisma Database Client',
    ' *',
    ' * Auto-generated by @shogo-ai/sdk',
    ' * This file can be customized - it will not be overwritten if it exists.',
    ' */',
    '',
    "import { PrismaPg } from '@prisma/adapter-pg'",
    "import { PrismaClient } from '../generated/prisma/client'",
    '',
    'const globalForPrisma = globalThis as unknown as {',
    '  prisma: PrismaClient | undefined',
    '}',
    '',
    'const adapter = new PrismaPg({',
    '  connectionString: process.env.DATABASE_URL,',
    '})',
    '',
    'export const prisma =',
    '  globalForPrisma.prisma ??',
    '  new PrismaClient({',
    '    adapter,',
    "    log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],",
    '  })',
    '',
    "if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma",
    '',
  ]
  return lines.join('\n')
}

/**
 * Generate Prisma database module for SQLite using prisma-adapter-bun-sqlite (Prisma 7)
 */
export function generateSqliteDbModule(): string {
  const lines = [
    '/**',
    ' * Prisma Database Client (SQLite via Bun adapter)',
    ' *',
    ' * Auto-generated by @shogo-ai/sdk',
    ' * This file can be customized - it will not be overwritten if it exists.',
    ' */',
    '',
    "import { PrismaBunSqlite } from 'prisma-adapter-bun-sqlite'",
    "import { PrismaClient } from './generated/prisma/client'",
    '',
    'const globalForPrisma = globalThis as unknown as {',
    '  prisma: PrismaClient | undefined',
    '}',
    '',
    'const adapter = new PrismaBunSqlite({',
    "  url: process.env.DATABASE_URL ?? 'file:./skill.db',",
    '})',
    '',
    'export const prisma =',
    '  globalForPrisma.prisma ??',
    '  new PrismaClient({',
    '    adapter,',
    "    log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],",
    '  })',
    '',
    "if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma",
    '',
  ]
  return lines.join('\n')
}
