/**
 * Stores Generator (Per-Model)
 *
 * Generates one OptimisticStore file per Prisma model.
 */

import type { PrismaModel } from './prisma-generator'
import { toCamelCase, getIdField } from './prisma-generator'

// ============================================================================
// Types
// ============================================================================

export interface StoreGeneratorConfig {
  /** Base API path (default: '/api') */
  basePath?: string
}

export interface GeneratedStoreFile {
  /** Model name (e.g., 'Workspace') */
  modelName: string
  /** File name (e.g., 'workspace.store.ts') */
  fileName: string
  /** Generated code */
  code: string
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Convert model name to file name (kebab-case)
 */
function toFileName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/**
 * Convert model name to route path (kebab-case, plural)
 */
function toRoutePath(name: string): string {
  const kebab = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  // Simple pluralization
  if (kebab.endsWith('y')) return kebab.slice(0, -1) + 'ies'
  if (kebab.endsWith('s') || kebab.endsWith('x') || kebab.endsWith('ch') || kebab.endsWith('sh')) {
    return kebab + 'es'
  }
  return kebab + 's'
}

// ============================================================================
// Store Generator (Per-Model)
// ============================================================================

/**
 * Generate store file for a single model
 */
export function generateModelStore(
  model: PrismaModel,
  config: StoreGeneratorConfig = {}
): GeneratedStoreFile | null {
  const idField = getIdField(model)
  if (!idField) {
    return null // Skip models without @id
  }

  const basePath = config.basePath || '/api'
  const modelName = model.name
  const modelLower = toCamelCase(modelName)
  const fileName = `${toFileName(modelName)}.store.tsx`
  const routePath = toRoutePath(modelName)
  const endpoint = `${basePath}/${routePath}`

  const lines: string[] = [
    '/**',
    ` * Auto-generated ${modelName} Store`,
    ' *',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { OptimisticStore } from "@shogo-ai/sdk"',
    'import type { HttpClient } from "@shogo-ai/sdk"',
    `import type { ${modelName}Type } from "./${toFileName(modelName)}.types"`,
    '',
    '// Store instance (singleton)',
    `let _store: OptimisticStore<${modelName}Type> | null = null`,
    '',
    '/**',
    ` * Get or create the ${modelName} store`,
    ' *',
    ' * @param http - HttpClient instance (required on first call)',
    ' */',
    `export function get${modelName}Store(http?: HttpClient): OptimisticStore<${modelName}Type> {`,
    '  if (!_store) {',
    '    if (!http) {',
    `      throw new Error("HttpClient required to initialize ${modelName}Store")`,
    '    }',
    `    _store = new OptimisticStore<${modelName}Type>({`,
    '      http,',
    `      endpoint: "${endpoint}",`,
    '    })',
    '  }',
    '  return _store',
    '}',
    '',
    '/**',
    ` * Reset the ${modelName} store (for testing)`,
    ' */',
    `export function reset${modelName}Store(): void {`,
    '  _store = null',
    '}',
    '',
    `// Convenience export for direct import`,
    `export type { ${modelName}Type }`,
    '',
  ]

  return {
    modelName,
    fileName,
    code: lines.join('\n'),
  }
}

/**
 * Generate stores for all models
 */
export function generateStores(
  models: PrismaModel[],
  config: StoreGeneratorConfig = {}
): GeneratedStoreFile[] {
  const stores: GeneratedStoreFile[] = []

  for (const model of models) {
    const storeFile = generateModelStore(model, config)
    if (storeFile) {
      stores.push(storeFile)
    }
  }

  return stores
}

/**
 * Generate index file for stores
 */
export function generateStoresIndex(
  models: PrismaModel[],
  config: StoreGeneratorConfig = {}
): string {
  const basePath = config.basePath || '/api'

  const lines: string[] = [
    '/**',
    ' * Auto-generated Stores Index',
    ' *',
    ' * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY',
    ' */',
    '',
    'import { OptimisticStore } from "@shogo-ai/sdk"',
    'import type { HttpClient } from "@shogo-ai/sdk"',
    '',
    '// Type imports',
  ]

  for (const model of models) {
    const fileName = toFileName(model.name)
    lines.push(`import type { ${model.name}Type } from "./${fileName}.types"`)
  }

  lines.push('')
  lines.push('// Store imports')

  for (const model of models) {
    const fileName = toFileName(model.name)
    lines.push(`export { get${model.name}Store, reset${model.name}Store } from "./${fileName}.store"`)
  }

  lines.push('')
  lines.push('// Re-export types')

  for (const model of models) {
    const fileName = toFileName(model.name)
    lines.push(`export type { ${model.name}Type } from "./${fileName}.types"`)
  }

  lines.push('')
  lines.push('/**')
  lines.push(' * All stores as an object (for convenience)')
  lines.push(' */')
  lines.push('export interface AllStores {')

  for (const model of models) {
    lines.push(`  ${toCamelCase(model.name)}: OptimisticStore<${model.name}Type>`)
  }

  lines.push('}')
  lines.push('')

  lines.push('/**')
  lines.push(' * Create all stores with the given HttpClient')
  lines.push(' */')
  lines.push('export function createAllStores(http: HttpClient): AllStores {')
  lines.push('  return {')

  for (const model of models) {
    const modelLower = toCamelCase(model.name)
    lines.push(`    ${modelLower}: get${model.name}Store(http),`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
