-- Migration: add_infra_snapshot_region
-- Generated: 2026-09-22T03:01:10.885Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_infra_snapshot_region`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "infra_snapshots" ADD COLUMN "region" TEXT;

-- CreateIndex
CREATE INDEX "infra_snapshots_region_timestamp_idx" ON "infra_snapshots"("region", "timestamp");

-- NOTE: the auto-generated diff also included a `RedefineIndex` for
-- `signup_attributions` (DROP the autogenerated unique index, recreate it
-- explicitly). That's pre-existing, unrelated drift already documented in
-- ACCEPTED_DRIFT (scripts/check-desktop-schema-drift.ts) — and it isn't
-- actually replayable as emitted: SQLite refuses to
-- `DROP INDEX sqlite_autoindex_...` while the UNIQUE constraint it backs is
-- still live, which `bun run check:migrations` caught on the fresh-install
-- checkpoint. Deliberately dropped from this migration; left for a future,
-- dedicated fix.

