-- Migration: add_huddles
-- Generated: 2026-10-05T08:01:44.812Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_huddles`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- CreateTable
CREATE TABLE "huddles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "activeKey" TEXT,
    "roomName" TEXT NOT NULL,
    "startedById" TEXT NOT NULL,
    "messageId" TEXT,
    "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" DATETIME,
    CONSTRAINT "huddles_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "huddle_participants" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "huddleId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "joinedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "leftAt" DATETIME,
    CONSTRAINT "huddle_participants_huddleId_fkey" FOREIGN KEY ("huddleId") REFERENCES "huddles" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "huddles_activeKey_key" ON "huddles"("activeKey");

-- CreateIndex
CREATE UNIQUE INDEX "huddles_roomName_key" ON "huddles"("roomName");

-- CreateIndex
CREATE INDEX "huddles_workspaceId_endedAt_idx" ON "huddles"("workspaceId", "endedAt");

-- CreateIndex
CREATE INDEX "huddles_conversationId_startedAt_idx" ON "huddles"("conversationId", "startedAt");

-- CreateIndex
CREATE INDEX "huddle_participants_huddleId_leftAt_idx" ON "huddle_participants"("huddleId", "leftAt");

-- CreateIndex
CREATE INDEX "huddle_participants_userId_idx" ON "huddle_participants"("userId");

