apiVersion: v1
kind: Namespace
metadata:
  name: shogo-staging-system
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: shogo-staging-workspaces
  labels:
    environment: staging
