apiVersion: v1
kind: Namespace
metadata:
  name: shogo-production-system
  labels:
    environment: production
    region: us-ashburn-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: shogo-production-workspaces
  labels:
    environment: production
    region: us-ashburn-1
