-- Migration: add_credential_approvals_audit
-- Generated: 2026-10-05T02:14:42.021Z by scripts/db-migrate-desktop.ts
-- Source:    prisma/schema.local.prisma
--
-- This file was generated by `bun run db:migrate:desktop --name add_credential_approvals_audit`.
-- The SQL below was emitted verbatim by
--   prisma migrate diff --from-migrations apps/desktop/prisma/migrations --to-schema prisma/schema.local.prisma --script
-- and is safe to edit by hand BUT consider regenerating via the script
-- instead if the schema changes again — that keeps the migration in lockstep
-- with Prisma's SQLite SQL generator (which handles enums, JSONB, String[],
-- FK inlining, partial indexes, etc. uniformly).

-- AlterTable
ALTER TABLE "integration_credential_policies" ADD COLUMN "delegateUserId" TEXT;
ALTER TABLE "integration_credential_policies" ADD COLUMN "delegatedAt" DATETIME;

-- CreateTable
CREATE TABLE "integration_credential_approvals" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "op" TEXT NOT NULL,
    "toolName" TEXT,
    "summary" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "requesterUserId" TEXT,
    "origin" TEXT,
    "conversationId" TEXT,
    "messageId" TEXT,
    "decidedByUserId" TEXT,
    "decidedAt" DATETIME,
    "expiresAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "integration_credential_approvals_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "integration_credential_audit" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "op" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "actingAs" TEXT NOT NULL,
    "actingUserId" TEXT,
    "requesterUserId" TEXT,
    "origin" TEXT,
    "approvalId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "integration_credential_audit_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "integration_credential_approvals_projectId_status_idx" ON "integration_credential_approvals"("projectId", "status");

-- CreateIndex
CREATE INDEX "integration_credential_audit_projectId_createdAt_idx" ON "integration_credential_audit"("projectId", "createdAt");

